---
openapi: 3.0.3
info:
  title: Business Partner certificate
  version: v2
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/business-partner-certificate:
    get:
      tags:
      - BusinessPartnerCertificate
      operationId: getBusinessPartnerCertificate
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/BusinessPartnerCertificate'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/BusinessPartnerCertificate'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnlTrait:
      type: string
      description: "The provided regular expression ensures that the BPNL is composed\
        \ of prefix 'BPNL', 10 digits and two alphanumeric letters."
      pattern: "^BPNL[a-zA-Z0-9]{12}$"
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text:
      type: string
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    urn_samm_io.catenax.business_partner_certificate_2.0.0_CertificateTypeEntity:
      description: "Detailed entity of the certificate like IS09001:2015, IATF 16949:2015\
        \ or other, valid types are registered at BPN metadatacontroller"
      type: object
      properties:
        certificateType:
          description: "Type of the certificate as defined on the document,valid types\
            \ are registered at BPN metadatacontroller"
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        certificateVersion:
          description: "Version of the certificate as defined on the document, usually\
            \ the specific version of a certification standard"
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
      required:
      - certificateType
    urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnsTrait:
      type: string
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two alphanumeric letters."
      pattern: "^BPNS[a-zA-Z0-9]{12}$"
    urn_samm_io.catenax.business_partner_certificate_2.0.0_EnclosedSiteEntity:
      description: "Entity representing an enclosed site, can be BPNS or BPNA"
      type: object
      properties:
        enclosedSiteBpn:
          description: The BPN of an enclosed site
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnsTrait'
        areaOfApplication:
          description: Details on which areas / application types a certificate is
            valid for a company
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
      required:
      - enclosedSiteBpn
    EnclosedSitesList:
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.business_partner_certificate_2.0.0_EnclosedSiteEntity'
    urn_samm_io.catenax.business_partner_certificate_2.0.0_Date:
      type: string
      format: date
      description: Describes a property which contains the date in english format.
    urn_samm_io.catenax.business_partner_certificate_2.0.0_TrustLevelValue:
      type: string
      description: The possible trust level values of certificate
      enum:
      - none
      - low
      - high
      - trusted
    urn_samm_io.catenax.business_partner_certificate_2.0.0_TrustValidatorCharacteristic:
      description: The BPN of the data service provider who validated the given certificate
      type: object
      properties:
        validatorName:
          description: The optional name of the data service provider who validated
            the given certificate
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        validatorBpn:
          description: The BPN of the data service provider who validated the given
            certificate
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnlTrait'
    BusinessPartnerCertificate:
      description: "A business partner certifcate describes a certificate (eg ISO9001,\
        \ IATF-16949) via a certifcate document  of a Catena-X business partner"
      type: object
      properties:
        businessPartnerNumber:
          description: 'The BPN of the certified legal entity '
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnlTrait'
        type:
          description: "Type of the certificate as defined on the document like IS09001,\
            \ IATF 16949 or other"
          $ref: '#/components/schemas/urn_samm_io.catenax.business_partner_certificate_2.0.0_CertificateTypeEntity'
        registrationNumber:
          description: Registration number of the certificate as defined on the certificate
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        areaOfApplication:
          description: Details on which areas / application types a certificate is
            valid for a company
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        enclosedSites:
          description: "Additional sites covered by the certificate, which can be\
            \ either BPNS or BPNA"
          $ref: '#/components/schemas/EnclosedSitesList'
        validFrom:
          description: Valid from date as defined on the certificate.
          $ref: '#/components/schemas/urn_samm_io.catenax.business_partner_certificate_2.0.0_Date'
        validUntil:
          description: Valid valid until as defined on the certificate. If certificate
            never expires value until expected to be 9999-12-31
          $ref: '#/components/schemas/urn_samm_io.catenax.business_partner_certificate_2.0.0_Date'
        issuer:
          description: 'The BPN of the issuing authority e.g. TUEV Sued '
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnlTrait'
        trustLevel:
          description: "The trust level of the given certificate - none,low, high,\
            \ trusted"
          $ref: '#/components/schemas/urn_samm_io.catenax.business_partner_certificate_2.0.0_TrustLevelValue'
        validator:
          description: The BPN of the data service provider who validate the given
            certificate
          $ref: '#/components/schemas/urn_samm_io.catenax.business_partner_certificate_2.0.0_TrustValidatorCharacteristic'
        uploader:
          description: The BPN of the business partner who originally provided the
            certifcate data or document e.g. Mercedes Benz AG
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnlTrait'
        documentID:
          description: The id of the certificate document as stored by the data service
            provider for physical download via API
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
      required:
      - businessPartnerNumber
      - type
      - registrationNumber
      - validFrom
      - validUntil
      - trustLevel
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BusinessPartnerCertificate:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    BusinessPartnerCertificate:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BusinessPartnerCertificate'
