---
openapi: 3.0.3
info:
  title: Asset Tracker Links
  version: v1
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/asset-tracker-links:
    get:
      tags:
      - AssetTrackerLinks
      operationId: getAssetTrackerLinks
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/AssetTrackerLinks'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/AssetTrackerLinks'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_bamm_io.catenax.asset_tracker_links_1.0.0_CatenaXIdTraitCharacteristic:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_bamm_io.catenax.asset_tracker_links_1.0.0_PairedCharacteristic:
      type: boolean
      description: Characteristic describing the property paired.
    urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    urn_bamm_io.catenax.asset_tracker_links_1.0.0_ResourcePath:
      type: string
      format: uri
      description: The path of a resource.
    urn_bamm_io.catenax.asset_tracker_links_1.0.0_ChildData:
      description: Catena-X ID and meta data of the child part.
      type: object
      properties:
        childCatenaXId:
          description: The Catena-X ID of the child object which is linked to the
            given parent part.
          $ref: '#/components/schemas/urn_bamm_io.catenax.asset_tracker_links_1.0.0_CatenaXIdTraitCharacteristic'
        paired:
          description: Currently paired when set to true.
          $ref: '#/components/schemas/urn_bamm_io.catenax.asset_tracker_links_1.0.0_PairedCharacteristic'
        pairedOn:
          description: Timestamp of pairing of an IoT Device to an Asset.
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp'
        unpairedOn:
          description: Timestamp of the unpairing of an IoT Device from an Asset.
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp'
        historicalData:
          description: 'Describes the location where the historical sensor data can
            be found. '
          $ref: '#/components/schemas/urn_bamm_io.catenax.asset_tracker_links_1.0.0_ResourcePath'
      required:
      - childCatenaXId
      - paired
      - pairedOn
      - unpairedOn
      - historicalData
    urn_bamm_io.catenax.asset_tracker_links_1.0.0_SetOfChildPartsCharacteristic:
      description: Set of child parts the parent object consist of.
      type: array
      items:
        $ref: '#/components/schemas/urn_bamm_io.catenax.asset_tracker_links_1.0.0_ChildData'
      uniqueItems: true
    AssetTrackerLinks:
      description: Represent the link between Asset and IoT Device (tracker) with
        timestamps of pairing and unpairing.
      type: object
      properties:
        catenaXId:
          description: "The Catena-X ID of the givenasset, valid for the Catena-X\
            \ dataspace."
          $ref: '#/components/schemas/urn_bamm_io.catenax.asset_tracker_links_1.0.0_CatenaXIdTraitCharacteristic'
        childParts:
          description: "Set of child parts, of which the given parent object consist\
            \ of."
          $ref: '#/components/schemas/urn_bamm_io.catenax.asset_tracker_links_1.0.0_SetOfChildPartsCharacteristic'
      required:
      - catenaXId
      - childParts
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    AssetTrackerLinks:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    AssetTrackerLinks:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AssetTrackerLinks'
