---
openapi: 3.0.3
info:
  title: Individual Asset Definition
  version: v2
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/individual-asset-definition:
    get:
      tags:
      - IndividualAssetDefinition
      operationId: getIndividualAssetDefinition
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: '#/components/responses/IndividualAssetDefinition'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    urn_samm_io.catenax.individual_asset_definition_2.0.0_CatenaXIdTrait:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_samm_io.catenax.individual_asset_definition_2.0.0_AssetOwnerCharacteristic:
      type: string
      description: Characteristic describing the property asset owner.
    urn_samm_io.catenax.individual_asset_definition_2.0.0_AssetSerialNumberCharacteristic:
      type: string
      description: Characteristic describing the property serial number.
    urn_samm_io.catenax.individual_asset_definition_2.0.0_AssetTypeCharacteristic:
      type: string
      description: Characteristic describing the property asset type.
    urn_samm_io.catenax.shared.physical_dimension_3.0.0_KilogramCharacteristic:
      type: number
      description: a measurement value given in the unit kilogram
    urn_samm_io.catenax.shared.physical_dimension_3.0.0_MillimetreCharacteristic:
      type: number
      description: a measurement for a lenght given in the unit millimetre
    urn_samm_io.catenax.shared.physical_dimension_3.0.0_PhysicalDimensionsCharacteristic:
      description: Describes the physical dimensions of then entity.
      type: object
      properties:
        weight:
          description: Weight of the item
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.physical_dimension_3.0.0_KilogramCharacteristic'
        diameter:
          description: Diameter of the item.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.physical_dimension_3.0.0_MillimetreCharacteristic'
        height:
          description: Height of the item.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.physical_dimension_3.0.0_MillimetreCharacteristic'
        width:
          description: Width of the item.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.physical_dimension_3.0.0_MillimetreCharacteristic'
        length:
          description: Length of the item.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.physical_dimension_3.0.0_MillimetreCharacteristic'
    IndividualAssetDefinition:
      description: Permanent characteristics of an individual asset.
      type: object
      properties:
        catenaXId:
          description: "The fully anonymous Catena-X ID of the asset, valid for the\
            \ Catena-X dataspace."
          $ref: '#/components/schemas/urn_samm_io.catenax.individual_asset_definition_2.0.0_CatenaXIdTrait'
        assetOwnerId:
          description: BPNL of the asset owner.
          $ref: '#/components/schemas/urn_samm_io.catenax.individual_asset_definition_2.0.0_AssetOwnerCharacteristic'
        assetSerialNumber:
          description: The serial number of the asset.
          $ref: '#/components/schemas/urn_samm_io.catenax.individual_asset_definition_2.0.0_AssetSerialNumberCharacteristic'
        assetType:
          description: The type of an asset.
          $ref: '#/components/schemas/urn_samm_io.catenax.individual_asset_definition_2.0.0_AssetTypeCharacteristic'
        physicalDimensionsProperty:
          description: Describes the physical dimensions of then entity.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.physical_dimension_3.0.0_PhysicalDimensionsCharacteristic'
      required:
      - catenaXId
      - assetOwnerId
      - assetSerialNumber
      - assetType
      - physicalDimensionsProperty
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    IndividualAssetDefinition:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IndividualAssetDefinition'
      description: The request was successful.
  requestBodies:
    IndividualAssetDefinition:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IndividualAssetDefinition'
