---
openapi: 3.0.3
info:
  title: Batch
  version: v2
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/batch:
    get:
      tags:
      - Batch
      operationId: getBatch
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/Batch'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Batch'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_samm_io.catenax.batch_2.0.0_CatenaXIdTrait:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_samm_io.catenax.batch_2.0.0_KeyTrait:
      type: string
      description: Constraint that ensures that the predefined keys are used.
      pattern: ^(manufacturerId|batchId)$
    urn_samm_io.catenax.batch_2.0.0_ValueCharacteristic:
      type: string
      description: The value of an identifier.
    urn_samm_io.catenax.batch_2.0.0_KeyValueList:
      description: "A list of key value pairs for local identifiers, which are composed\
        \ of a key and a corresponding value."
      type: object
      properties:
        key:
          description: The key of a local identifier.
          $ref: '#/components/schemas/urn_samm_io.catenax.batch_2.0.0_KeyTrait'
        value:
          description: The value of an identifier.
          $ref: '#/components/schemas/urn_samm_io.catenax.batch_2.0.0_ValueCharacteristic'
      required:
      - key
      - value
    urn_samm_io.catenax.batch_2.0.0_LocalIdentifierCharacteristic:
      description: "A batch may have multiple attributes, which uniquely identify\
        \ that batch in a specific dataspace (e.g. the manufacturer`s dataspace)"
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.batch_2.0.0_KeyValueList'
      uniqueItems: true
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    urn_samm_io.catenax.batch_2.0.0_ProductionCountryCodeTrait:
      type: string
      description: Regular Expression that ensures a three-letter code
      pattern: "^[A-Z]{3}$"
    urn_samm_io.catenax.batch_2.0.0_ManufacturingCharacteristic:
      description: Characteristic to describe manufacturing related data
      type: object
      properties:
        date:
          description: "Timestamp of the manufacturing date as the final step in production\
            \ process (e.g. final quality check, ready-for-shipment event)"
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
        country:
          description: Country code where the part was manufactured
          $ref: '#/components/schemas/urn_samm_io.catenax.batch_2.0.0_ProductionCountryCodeTrait'
      required:
      - date
    urn_samm_io.catenax.batch_2.0.0_PartIdCharacteristic:
      type: string
      description: "The part ID is a multi-character string, ususally assigned by\
        \ an ERP system"
    urn_samm_io.catenax.batch_2.0.0_PartNameCharacteristic:
      type: string
      description: Part Name in string format from the respective system in the value
        chain
    urn_samm_io.catenax.batch_2.0.0_ClassificationCharacteristic:
      type: string
      description: "A part type must be placed into one of the following classes:\
        \ 'component', 'product', 'software', 'assembly', 'tool', or 'raw material'."
      enum:
      - product
      - raw material
      - software
      - assembly
      - tool
      - component
    urn_samm_io.catenax.batch_2.0.0_PartTypeInformationCharacteristic:
      description: The characteristics of the part type
      type: object
      properties:
        manufacturerPartId:
          description: Part ID as assigned by the manufacturer of the part. The Part
            ID identifies the part (as designed) in the manufacturer`s dataspace.
            The Part ID does not reference a specific instance of a part and thus
            should not be confused with the serial number or batch number.
          $ref: '#/components/schemas/urn_samm_io.catenax.batch_2.0.0_PartIdCharacteristic'
        nameAtManufacturer:
          description: Name of the part as assigned by the manufacturer
          $ref: '#/components/schemas/urn_samm_io.catenax.batch_2.0.0_PartNameCharacteristic'
        classification:
          description: The classification of the part type according to STEP standard
            definition
          $ref: '#/components/schemas/urn_samm_io.catenax.batch_2.0.0_ClassificationCharacteristic'
      required:
      - manufacturerPartId
      - nameAtManufacturer
      - classification
    Batch:
      description: "A batch is a quantity of (semi-) finished products or (raw) material\
        \ product that have been produced under the same circumstances (e.g. same\
        \ production location), as specified groups or amounts, within a certain time\
        \ frame. Every batch can differ in the number or amount of products. Different\
        \ batches can have varied specifications, e.g., different colors. A batch\
        \ is identified via a Batch ID."
      type: object
      properties:
        catenaXId:
          description: "The fully anonymous Catena-X ID of the batch, valid for the\
            \ Catena-X dataspace."
          $ref: '#/components/schemas/urn_samm_io.catenax.batch_2.0.0_CatenaXIdTrait'
        localIdentifiers:
          description: "A local identifier enables identification of a part in a specific\
            \ dataspace, but is not unique in Catena-X dataspace. Multiple local identifiers\
            \ may exist."
          $ref: '#/components/schemas/urn_samm_io.catenax.batch_2.0.0_LocalIdentifierCharacteristic'
        manufacturingInformation:
          description: "Information from manufacturing process, such as manufacturing\
            \ date and manufacturing country"
          $ref: '#/components/schemas/urn_samm_io.catenax.batch_2.0.0_ManufacturingCharacteristic'
        partTypeInformation:
          description: The part type of which the batch has been instantiated of.
          $ref: '#/components/schemas/urn_samm_io.catenax.batch_2.0.0_PartTypeInformationCharacteristic'
      required:
      - catenaXId
      - localIdentifiers
      - manufacturingInformation
      - partTypeInformation
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Batch:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    Batch:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Batch'
