---
openapi: 3.0.3
info:
  title: Shopfloor Information Types
  version: v2
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/shopfloor-information-types:
    get:
      tags:
      - ShopfloorInformationTypes
      operationId: getShopfloorInformationTypes
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: '#/components/responses/ShopfloorInformationTypes'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    urn_samm_io.catenax.shared.shopfloor_information_types_2.0.0_CommunicationModeEnum:
      type: string
      description: Enumerates all possible communication modes
      enum:
      - synchronous
      - cyclic
      - notification
    urn_samm_io.catenax.shared.shopfloor_information_types_2.0.0_TimeUnitEnum:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      description: Enumerates all time units
      enum:
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hour
      - unit:day
      - unit:week
      - unit:month
      - unit:year
    urn_samm_io.catenax.shared.shopfloor_information_types_2.0.0_IntegerValueCharacteristic:
      type: number
      description: The value of the specified timeUnit as an integer value
    urn_samm_io.catenax.shared.shopfloor_information_types_2.0.0_TimeValueCharacteristic:
      description: Link to the  TimeUnit Data Type
      type: object
      properties:
        timeUnit:
          description: Specifies the unit in which the time is represented
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_2.0.0_TimeUnitEnum'
        value:
          description: The amount of timeUnits considered
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_2.0.0_IntegerValueCharacteristic'
      required:
      - timeUnit
      - value
    ShopfloorInformationTypes:
      description: Collection of types used in multiple data models of the Shopfloor
        Information Service
      type: object
      properties:
        communicationMode:
          description: Specification of the communication mode
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_2.0.0_CommunicationModeEnum'
        timeValue:
          description: A time Value property
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_2.0.0_TimeValueCharacteristic'
      required:
      - communicationMode
      - timeValue
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ShopfloorInformationTypes:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ShopfloorInformationTypes'
      description: The request was successful.
  requestBodies:
    ShopfloorInformationTypes:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ShopfloorInformationTypes'
