---
openapi: 3.0.3
info:
  title: Get Production Forecast
  version: v1
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/get-production-forecast:
    get:
      tags:
      - GetProductionForecast
      operationId: getGetProductionForecast
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: '#/components/responses/GetProductionForecast'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_TimeUnitEnum:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      description: Enumerates all time units
      enum:
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hour
      - unit:day
      - unit:week
      - unit:month
      - unit:year
    urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_IntegerValueCharacteristic:
      type: number
      description: The value of the specified timeUnit as an integer value
    urn_samm_io.catenax.shopfloor_information.get_production_forecast_1.0.0_TimeValueCharacteristic:
      description: Link to the  TimeUnit Data Type
      type: object
      properties:
        timeUnit:
          description: Specifies the unit in which the time is represented
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_TimeUnitEnum'
        value:
          description: The amount of timeUnits considered
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_IntegerValueCharacteristic'
      required:
      - timeUnit
      - value
    urn_samm_io.catenax.shared.message_header_1.0.0_BpnCharacteristic:
      type: string
      description: Characteristic for defining BPN values
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean:
      type: boolean
      description: Represents a boolean value (i.e. a "flag").
    urn_samm_io.catenax.shared.message_header_1.0.0_UuidCharacteristic:
      type: string
      description: Structured Value for defining a property which requires an UUID
    urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_CommunicationModeEnum:
      type: string
      description: Enumerates all possible communication modes
      enum:
      - synchronous
      - cyclic
      - notification
    urn_samm_io.catenax.shopfloor_information.get_production_forecast_1.0.0_RequestCharacteristic:
      description: Data type for a request
      type: object
      properties:
        offset:
          description: |-
            Send/start time of the first message/notification
            - "0" ==> immediate response
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.get_production_forecast_1.0.0_TimeValueCharacteristic'
        customerId:
          description: Internal customerId
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.message_header_1.0.0_BpnCharacteristic'
        precisionOfForecast:
          description: |-
            Accuracy of the time specification of the completion date.
            - default: implicitly defined by production
            - only as a REQUEST of the requester since it cannot be guaranteed that the store floor can provide the data in this accuracy.
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.get_production_forecast_1.0.0_TimeValueCharacteristic'
        productionForecastForAll:
          description: "Boolean variable that detemines whether the customer request\
            \ information about each position of an order, or information about the\
            \ complete order"
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean'
        orderId:
          description: The Id identifying subject of the request
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.message_header_1.0.0_UuidCharacteristic'
        deviationOfSchedule:
          description: |-
            Mandatory property for the notification mode. The property specifies the deviation from targeted delivery date that must be met to send a notification to a subscriber

            mandatory for CommunicationMode = "notification"
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.get_production_forecast_1.0.0_TimeValueCharacteristic'
        notificationInterval:
          description: |-
            Interval time that either specifies the cyclic send time or limits the notification time
            mandatory for CommunicationMode = "cyclic"
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.get_production_forecast_1.0.0_TimeValueCharacteristic'
        communicationMode:
          description: Specification of the communication mode
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.shopfloor_information_types_1.0.0_CommunicationModeEnum'
        versionDataModel:
          description: Specifies the used version of the data model
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.message_header_1.0.0_BpnCharacteristic'
      required:
      - offset
      - customerId
      - productionForecastForAll
      - orderId
      - communicationMode
      - versionDataModel
    urn_samm_io.catenax.shared.message_header_1.0.0_ContextCharacteristic:
      type: string
      description: Defining a string value for the context
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    urn_samm_io.catenax.shared.message_header_1.0.0_VersionCharacteristic:
      type: string
      description: Characteristic defining the value of version.
    urn_samm_io.catenax.shared.message_header_1.0.0_HeaderCharacteristic:
      description: Characteristic describing the common shared aspect Message Header
      type: object
      properties:
        messageId:
          description: "Unique ID identifying the message. The purpose of the ID is\
            \ to uniquely identify a single message, therefore it MUST not be reused."
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.message_header_1.0.0_UuidCharacteristic'
        context:
          description: |-
            Information about the context the message should be considered in.
            The value MUST consist of two parts: an identifier of the context (e.g. business domain, etc.) followed by a version number.
            Both the identifier and the version number MUST correspond to the content of the message.
            If the content of a message is described by an aspect model available in the Catena-X Semantic Hub, then the unique identifier of this semantic model (e.g. urn:samm:io.catenax.<ASPECT-MODEL-NAME>:1.x.x) MUST be used as a value of the context field. This is considered the default case.
            In all other cases the value of the context field MUST follow the pattern <domain>-<subdomain>-<object>:<[major] version> (e.g. TRACE-QM-Alert:1.x.x).
            Versioning only refers to major versions in both default and fallback cases.
            Note: The version of the message's header is specified in the version field.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.message_header_1.0.0_ContextCharacteristic'
        sentDateTime:
          description: Time zone aware timestamp holding the date and the time the
            message was sent by the sending party. The value MUST be formatted according
            to the ISO 8601 standard
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
        senderBpn:
          description: The Business Partner Number of the sending party. The value
            MUST be a valid BPN. BPNA and BPNS are not allowed. Applicable constraints
            are defined in the corresponding standard
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.message_header_1.0.0_BpnCharacteristic'
        receiverBpn:
          description: The Business Partner Number of the receiving party. The value
            MUST be a valid BPN. BPNA and BPNS are not allowed. Applicable constraints
            are defined in the corresponding standard.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.message_header_1.0.0_BpnCharacteristic'
        expectedResponseBy:
          description: Time zone aware timestamp holding the date and time by which
            the sending party expects a certain type of response from the receiving
            party. The meaning and interpretation of the fields's value are context-bound
            and MUST therefore be defined by any business domain or platform capability
            making use of it. The value MUST be formatted according to the ISO 8601
            standard
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
        relatedMessageId:
          description: Unique ID identifying a message somehow related to the current
            one
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.message_header_1.0.0_UuidCharacteristic'
        version:
          description: The unique identifier of the aspect model defining the structure
            and the semantics of the message's header. The version number should reflect
            the versioning schema of aspect models in Catena-X.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.message_header_1.0.0_VersionCharacteristic'
      required:
      - messageId
      - context
      - sentDateTime
      - senderBpn
      - receiverBpn
      - version
    GetProductionForecast:
      description: Aspect Model to request a production forecast
      type: object
      properties:
        request:
          description: Data model for a request
          $ref: '#/components/schemas/urn_samm_io.catenax.shopfloor_information.get_production_forecast_1.0.0_RequestCharacteristic'
        header:
          description: Contains standardized attributes for message processing common
            across several use cases.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.message_header_1.0.0_HeaderCharacteristic'
      required:
      - header
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    GetProductionForecast:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetProductionForecast'
      description: The request was successful.
  requestBodies:
    GetProductionForecast:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetProductionForecast'
