---
openapi: 3.0.3
info:
  title: Get Production Forecast
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#GetProductionForecast"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/get-production-forecast:
    get:
      tags:
      - GetProductionForecast
      operationId: getGetProductionForecast
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: "#/components/responses/GetProductionForecast"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    TimeUnitEnum:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:1.0.0#TimeUnitEnum"
      description: Enumerates all time units
      enum:
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hour
      - unit:day
      - unit:week
      - unit:month
      - unit:year
    IntegerValueCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:1.0.0#IntegerValueCharacteristic"
      description: The value of the specified timeUnit as an integer value
    TimeValueCharacteristic:
      description: Link to the  TimeUnit Data Type
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#TimeValueCharacteristic"
      type: object
      properties:
        timeUnit:
          description: Specifies the unit in which the time is represented
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:1.0.0#timeUnit"
          $ref: "#/components/schemas/TimeUnitEnum"
        value:
          description: The amount of timeUnits considered
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:1.0.0#value"
          $ref: "#/components/schemas/IntegerValueCharacteristic"
      required:
      - timeUnit
      - value
    BpnCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#BpnCharacteristic"
      description: Characteristic for defining BPN values
    Boolean:
      type: boolean
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Boolean"
      description: Represents a boolean value (i.e. a "flag").
    UuidCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#UuidCharacteristic"
      description: Structured Value for defining a property which requires an UUID
    CommunicationModeEnum:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:1.0.0#CommunicationModeEnum"
      description: Enumerates all possible communication modes
      enum:
      - synchronous
      - cyclic
      - notification
    RequestCharacteristic:
      description: Data type for a request
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#RequestCharacteristic"
      type: object
      properties:
        offset:
          description: |-
            Send/start time of the first message/notification
            - "0" ==> immediate response
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#offset"
          $ref: "#/components/schemas/TimeValueCharacteristic"
        customerId:
          description: Internal customerId
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#customerId"
          $ref: "#/components/schemas/BpnCharacteristic"
        precisionOfForecast:
          description: |-
            Accuracy of the time specification of the completion date.
            - default: implicitly defined by production
            - only as a REQUEST of the requester since it cannot be guaranteed that the store floor can provide the data in this accuracy.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#precisionOfForecast"
          $ref: "#/components/schemas/TimeValueCharacteristic"
        productionForecastForAll:
          description: "Boolean variable that detemines whether the customer request\
            \ information about each position of an order, or information about the\
            \ complete order"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#productionForecastForAll"
          $ref: "#/components/schemas/Boolean"
        orderId:
          description: The Id identifying subject of the request
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#orderId"
          $ref: "#/components/schemas/UuidCharacteristic"
        deviationOfSchedule:
          description: |-
            Mandatory property for the notification mode. The property specifies the deviation from targeted delivery date that must be met to send a notification to a subscriber

            mandatory for CommunicationMode = "notification"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#deviationOfSchedule"
          $ref: "#/components/schemas/TimeValueCharacteristic"
        notificationInterval:
          description: |-
            Interval time that either specifies the cyclic send time or limits the notification time
            mandatory for CommunicationMode = "cyclic"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#notificationInterval"
          $ref: "#/components/schemas/TimeValueCharacteristic"
        communicationMode:
          description: Specification of the communication mode
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:1.0.0#communicationMode"
          $ref: "#/components/schemas/CommunicationModeEnum"
        versionDataModel:
          description: Specifies the used version of the data model
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:1.0.0#versionDataModel"
          $ref: "#/components/schemas/BpnCharacteristic"
      required:
      - offset
      - customerId
      - productionForecastForAll
      - orderId
      - communicationMode
      - versionDataModel
    ContextCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#ContextCharacteristic"
      description: Defining a string value for the context
    Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Timestamp"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    VersionCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#VersionCharacteristic"
      description: Characteristic defining the value of version.
    HeaderCharacteristic:
      description: Characteristic describing the common shared aspect Message Header
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#HeaderCharacteristic"
      type: object
      properties:
        messageId:
          description: "Unique ID identifying the message. The purpose of the ID is\
            \ to uniquely identify a single message, therefore it MUST not be reused."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#messageId"
          $ref: "#/components/schemas/UuidCharacteristic"
        context:
          description: |-
            Information about the context the message should be considered in.
            The value MUST consist of two parts: an identifier of the context (e.g. business domain, etc.) followed by a version number.
            Both the identifier and the version number MUST correspond to the content of the message.
            If the content of a message is described by an aspect model available in the Catena-X Semantic Hub, then the unique identifier of this semantic model (e.g. urn:samm:io.catenax.<ASPECT-MODEL-NAME>:1.x.x) MUST be used as a value of the context field. This is considered the default case.
            In all other cases the value of the context field MUST follow the pattern <domain>-<subdomain>-<object>:<[major] version> (e.g. TRACE-QM-Alert:1.x.x).
            Versioning only refers to major versions in both default and fallback cases.
            Note: The version of the message's header is specified in the version field.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#context"
          $ref: "#/components/schemas/ContextCharacteristic"
        sentDateTime:
          description: Time zone aware timestamp holding the date and the time the
            message was sent by the sending party. The value MUST be formatted according
            to the ISO 8601 standard
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#sentDateTime"
          $ref: "#/components/schemas/Timestamp"
        senderBpn:
          description: The Business Partner Number of the sending party. The value
            MUST be a valid BPN. BPNA and BPNS are not allowed. Applicable constraints
            are defined in the corresponding standard
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#senderBpn"
          $ref: "#/components/schemas/BpnCharacteristic"
        receiverBpn:
          description: The Business Partner Number of the receiving party. The value
            MUST be a valid BPN. BPNA and BPNS are not allowed. Applicable constraints
            are defined in the corresponding standard.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#receiverBpn"
          $ref: "#/components/schemas/BpnCharacteristic"
        expectedResponseBy:
          description: Time zone aware timestamp holding the date and time by which
            the sending party expects a certain type of response from the receiving
            party. The meaning and interpretation of the fields's value are context-bound
            and MUST therefore be defined by any business domain or platform capability
            making use of it. The value MUST be formatted according to the ISO 8601
            standard
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#expectedResponseBy"
          $ref: "#/components/schemas/Timestamp"
        relatedMessageId:
          description: Unique ID identifying a message somehow related to the current
            one
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#relatedMessageId"
          $ref: "#/components/schemas/UuidCharacteristic"
        version:
          description: The unique identifier of the aspect model defining the structure
            and the semantics of the message's header. The version number should reflect
            the versioning schema of aspect models in Catena-X.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#version"
          $ref: "#/components/schemas/VersionCharacteristic"
      required:
      - messageId
      - context
      - sentDateTime
      - senderBpn
      - receiverBpn
      - version
    GetProductionForecast:
      description: Aspect Model to request a production forecast
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#GetProductionForecast"
      properties:
        request:
          description: Data model for a request
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.get_production_forecast:1.0.0#request"
          $ref: "#/components/schemas/RequestCharacteristic"
        header:
          description: Contains standardized attributes for message processing common
            across several use cases.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:1.0.0#header"
          $ref: "#/components/schemas/HeaderCharacteristic"
      required:
      - header
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    GetProductionForecast:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GetProductionForecast"
      description: The request was successful.
  requestBodies:
    GetProductionForecast:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GetProductionForecast"
      required: true
