---
openapi: 3.0.3
info:
  title: Contact Information
  version: v4
  x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.contact_information:4.0.0#ContactInformation"
servers:
- url: catenax.io/api/v4
  variables:
    api-version:
      default: v4
paths:
  /{tenant-id}/contact-information:
    get:
      tags:
      - ContactInformation
      operationId: getContactInformation
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: "#/components/responses/ContactInformation"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    WebsiteCharacteristic:
      type: string
      format: uri
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.contact_information:4.0.0#WebsiteCharacteristic"
      description: Address of the website.
    PhoneNumberTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.contact_information:4.0.0#PhoneNumberTrait"
      description: "Constraint to allow only numbers, whitespaces and an optional\
        \ leading + sign."
      pattern: "^[+]?[0-9 ]+$"
    EMailTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.contact_information:4.0.0#EMailTrait"
      description: Regular expression for mail address as defined in W3C.
      pattern: "^[a-zA-Z0-9.!#$%&?*+\\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$"
    ContactCharacteristic:
      description: Characteristic describing information on how to contact an organization.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.contact_information:4.0.0#ContactCharacteristic"
      type: object
      properties:
        website:
          description: Website of the contact.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.contact_information:4.0.0#website"
          $ref: "#/components/schemas/WebsiteCharacteristic"
        phoneNumber:
          description: Phone number with country and area code.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.contact_information:4.0.0#phoneNumber"
          $ref: "#/components/schemas/PhoneNumberTrait"
        email:
          description: An email address.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.contact_information:4.0.0#email"
          $ref: "#/components/schemas/EMailTrait"
        faxNumber:
          description: Fax number with country and area code.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.contact_information:4.0.0#faxNumber"
          $ref: "#/components/schemas/PhoneNumberTrait"
    ContactInformation:
      description: Entity encapsulating the contact details.
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.contact_information:4.0.0#ContactInformation"
      properties:
        contactProperty:
          description: Property describing contact information for an organization.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.contact_information:4.0.0#contactProperty"
          $ref: "#/components/schemas/ContactCharacteristic"
      required:
      - contactProperty
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    ContactInformation:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ContactInformation"
      description: The request was successful.
  requestBodies:
    ContactInformation:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ContactInformation"
      required: true
