---
openapi: 3.0.3
info:
  title: Short Term Material Demand
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#ShortTermMaterialDemand"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/short-term-material-demand:
    get:
      tags:
      - ShortTermMaterialDemand
      operationId: getShortTermMaterialDemand
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/ShortTermMaterialDemand"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/ShortTermMaterialDemand"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    QuantityValueCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#QuantityValueCharacteristic"
      description: The quantity value associated with the unit expressed as float.
    ItemUnitEnumeration:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#ItemUnitEnumeration"
      description: Enumeration for common item units.
      enum:
      - unit:piece
      - unit:set
      - unit:pair
      - unit:page
      - unit:cycle
      - unit:kilowattHour
      - unit:gram
      - unit:kilogram
      - unit:tonneMetricTon
      - unit:tonUsOrShortTonUkorus
      - unit:ounceAvoirdupois
      - unit:pound
      - unit:metre
      - unit:centimetre
      - unit:kilometre
      - unit:inch
      - unit:foot
      - unit:yard
      - unit:squareCentimetre
      - unit:squareMetre
      - unit:squareInch
      - unit:squareFoot
      - unit:squareYard
      - unit:cubicCentimetre
      - unit:cubicMetre
      - unit:cubicInch
      - unit:cubicFoot
      - unit:cubicYard
      - unit:litre
      - unit:millilitre
      - unit:hectolitre
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hourUnitOfTime
      - unit:day
    DemandQuantityCharacteristic:
      description: Demand expressed as item quantity with a unit of measure.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#DemandQuantityCharacteristic"
      type: object
      properties:
        value:
          description: The quantity value associated with the unit.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#quantityValue"
          $ref: "#/components/schemas/QuantityValueCharacteristic"
        unit:
          description: "The unit of an item. Common units may be related to mass,\
            \ count, linear, area, volume or misc."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#itemUnit"
          $ref: "#/components/schemas/ItemUnitEnumeration"
      required:
      - value
      - unit
    DateCharacteristic:
      type: string
      format: date
      x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#DateCharacteristic"
      description: An ISO date on which a given demand is needed. Must be given as
        single day (consider the time zone of the customer's location).
    Demand:
      description: A single demand for a day.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#Demand"
      type: object
      properties:
        demand:
          description: Quantity of materials required on a specific day. This demand
            is not a call-off and should be as close as possible to the actual production
            program.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#demand"
          $ref: "#/components/schemas/DemandQuantityCharacteristic"
        day:
          description: Day of the demanded quantity.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#day"
          $ref: "#/components/schemas/DateCharacteristic"
      required:
      - demand
      - day
    DemandTimeSeries:
      description: The demands in a given time period.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#DemandTimeSeries"
      type: array
      items:
        $ref: "#/components/schemas/Demand"
      uniqueItems: true
    DemandCategoryDefault:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - '0001'
      required:
      - demandCategoryCode
    DemandCategoryAfterSales:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - A1S1
      required:
      - demandCategoryCode
    DemandCategorySeries:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - SR99
      required:
      - demandCategoryCode
    DemandCategoryPhaseInPeriod:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - PI01
      required:
      - demandCategoryCode
    DemandCategorySingleOrder:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - OS01
      required:
      - demandCategoryCode
    DemandCategorySmallSeries:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - OI01
      required:
      - demandCategoryCode
    DemandCategoryExtraordinaryDemand:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - ED01
      required:
      - demandCategoryCode
    DemandCategoryPhaseOutPeriod:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - PO01
      required:
      - demandCategoryCode
    DemandCategoryCharacteristic:
      description: The classification of demands used for prioritization or allocation.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#DemandCategoryCharacteristic"
      type: object
      oneOf:
      - $ref: "#/components/schemas/DemandCategoryDefault"
      - $ref: "#/components/schemas/DemandCategoryAfterSales"
      - $ref: "#/components/schemas/DemandCategorySeries"
      - $ref: "#/components/schemas/DemandCategoryPhaseInPeriod"
      - $ref: "#/components/schemas/DemandCategorySingleOrder"
      - $ref: "#/components/schemas/DemandCategorySmallSeries"
      - $ref: "#/components/schemas/DemandCategoryExtraordinaryDemand"
      - $ref: "#/components/schemas/DemandCategoryPhaseOutPeriod"
    BpnsTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnsTrait"
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two alphanumeric letters."
      pattern: "^BPNS[a-zA-Z0-9]{12}$"
    Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Timestamp"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    DemandSeries:
      description: Encapsulates the demand series related information.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#DemandSeries"
      type: object
      properties:
        demands:
          description: A time series on a daily basis along a given time period to
            describe the demand values for this demand series.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#demands"
          $ref: "#/components/schemas/DemandTimeSeries"
        demandCategory:
          description: Type of demand for this demand series.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#demandCategory"
          $ref: "#/components/schemas/DemandCategoryCharacteristic"
        expectedSupplierLocationBpns:
          description: The Business Partner Number Site (BPNS) of the site from where
            the customer expects the supplier to fulfill the demands of the demand
            series. The value is used for informational purposes only and is therefore
            not binding for the supplier.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#expectedSupplierLocationBpns"
          $ref: "#/components/schemas/BpnsTrait"
        customerLocationBpns:
          description: The Business Partner Number Site (BPNS) of the site at which
            the customer needs the specified material for this demand series.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#customerLocationBpns"
          $ref: "#/components/schemas/BpnsTrait"
        lastUpdatedOnDateTime:
          description: Date and time at which the DemandSeries has been updated by
            the reporting partner's system. Date and time are set according to a timezone.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#lastUpdatedOnDateTime"
          $ref: "#/components/schemas/Timestamp"
      required:
      - demands
      - demandCategory
      - customerLocationBpns
      - lastUpdatedOnDateTime
    DemandSeriesSet:
      description: A set of demand series belonging to a certain material demand.
        Each demand series in the set must have a unique combination of customer location
        and demand category.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#DemandSeriesSet"
      type: array
      items:
        $ref: "#/components/schemas/DemandSeries"
      uniqueItems: true
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    ShortTermMaterialDemand:
      description: "The requirements of a customer towards a specific supplier for\
        \ a specific material. Each material demand is unique by its Customer, Supplier\
        \ and Material Number."
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#ShortTermMaterialDemand"
      properties:
        demandSeries:
          description: "The demands for a dedicated material in a given time period,\
            \ distinguished by their demand location and demand category."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#demandSeries"
          $ref: "#/components/schemas/DemandSeriesSet"
        materialGlobalAssetId:
          description: Identifier used uniquely to identify part type twin.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.short_term_material_demand:1.0.0#materialGlobalAssetId"
          $ref: "#/components/schemas/UuidV4Trait"
      required:
      - demandSeries
      - materialGlobalAssetId
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    ShortTermMaterialDemand:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    ShortTermMaterialDemand:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ShortTermMaterialDemand"
      required: true
