---
openapi: 3.0.3
info:
  title: Vehicles
  version: v2
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/vehicles:
    get:
      tags:
      - Vehicles
      operationId: getVehicles
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/Vehicles'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Vehicles'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_samm_io.catenax.fleet.vehicles_2.0.0_RecordStatusEnumeration:
      type: string
      description: Defining the enumeration for the record status
      enum:
      - new
      - update
      - delete
      - same
    urn_samm_io.catenax.fleet.vehicles_2.0.0_UniqueID:
      type: string
      description: This Characteristic describes a property that is truly unique either
        inside the Company that is providing the data or even in Catena-X dataspace.
        Only one property in a semantic entity should be a uniqueID. Unique ids can
        be used to link a data set with other semantic models.
    urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text:
      type: string
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    urn_samm_io.catenax.fleet.vehicles_2.0.0_EnginePower:
      type: number
      description: Engine power expressed in kilowatt.
    urn_samm_io.catenax.fleet.vehicles_2.0.0_DriveTypeNHTSA:
      type: string
      description: "Enumeration of drive type according NHTSA, table [vPICList_lite].[dbo].[DriveType]"
      enum:
      - All-Wheel Drive
      - Front-Wheel Drive
      - Rear-Wheel Drive
    urn_samm_io.catenax.fleet.vehicles_2.0.0_PowerTrainTypes:
      type: string
      description: "This enumeration comes from NHTSA (US authority) database. Table\
        \ [vPICList_lite].[dbo].[ElectrificationLevel] extended by Gasoline and Diesel\
        \ as entry."
      enum:
      - BEV (Battery Electric Vehicle)
      - Diesel
      - FCEV (Fuel Cell Electric Vehicle)
      - Gasoline
      - HEV (Hybrid Electric Vehicle)
      - Mild HEV (Hybrid Electric Vehicle)
      - PHEV (Plug-in Hybrid Electric Vehicle)
      - Other
    urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnsTrait:
      type: string
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two uppercase letters."
      pattern: "^BPNS[0-9]{8}[a-zA-Z0-9]{4}$"
    urn_samm_io.catenax.fleet.vehicles_2.0.0_CountryCodeTrait:
      type: string
      description: 'Regular Expression that ensures a three-letter code '
      pattern: "^[A-Z][A-Z][A-Z]$"
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    urn_samm_io.catenax.fleet.vehicles_2.0.0_VehicleSteeringPos:
      type: string
      description: "Vehicle steering position enumeration from NHTSA, see table [vPICList_lite].[dbo].[Steering]"
      enum:
      - Left-Hand Drive
      - Right-Hand Drive
    urn_samm_io.catenax.fleet.vehicles_2.0.0_OemShortNameTrait:
      type: string
      description: Restricts the length of wmiCode to exactly 3 chars.
      maxLength: 3
      minLength: 3
    urn_samm_io.catenax.fleet.vehicles_2.0.0_CubicCapacity:
      type: number
      description: Cubic capacity of the engine
    urn_samm_io.catenax.fleet.vehicles_2.0.0_FuelTypesNHTSA:
      type: string
      description: "Enumeration from NHTSA vpic database, table [vPICList_lite].[dbo].[FuelType]"
      enum:
      - Compressed Hydrogen/Hydrogen
      - Compressed Natural Gas(CNG)
      - Diesel
      - Electric
      - Ethanol(E85)
      - Flexible Fuel Vehicle(FFV)
      - Fuel Cell
      - Gasoline
      - Liquefied Natural Gas(LNG)
      - Liquefied Petroleum Gas(propane or LPG)
      - Methanol(M85)
      - Natural Gas
      - Neat Ethanol(E100)
      - Neat Methanol(M100)
      - Unknown
    urn_samm_io.catenax.fleet.vehicles_2.0.0_Engine:
      description: Describing one installed engine
      type: object
      properties:
        engineId:
          description: OEM-specific identifier/type of the installed engine
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_UniqueID'
        engineDescription:
          description: Description of the engine
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        engineSeries:
          description: Engine series as defined by OEM
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        serialNumber:
          description: Serial number of the installed engine
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        size:
          description: Cubic capacity in a combustion engine  - not available in battery-electric
            vehicles
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_CubicCapacity'
        power:
          description: Engine power is the power that an engine can put out
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_EnginePower'
        engineProductionDate:
          description: Date when the engine was produced
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
        installDate:
          description: Date when the engine was installed
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
        nhtsaFuelType:
          description: Description of the fuel according US NHTSA
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_FuelTypesNHTSA'
      required:
      - engineId
    urn_samm_io.catenax.fleet.vehicles_2.0.0_EnginesList:
      description: A list of all installed engines in the vehicle
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_Engine'
    urn_samm_io.catenax.fleet.vehicles_2.0.0_Equipment:
      description: One equipment of the vehicle.
      type: object
      properties:
        equipmentIdentifier:
          description: The identifier of a specific equipment.
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_UniqueID'
        equipmentDescription:
          description: The equipment variants description.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        group:
          description: Bundels all equipment-oriented information into categories
            like Interior
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
      required:
      - equipmentIdentifier
    urn_samm_io.catenax.fleet.vehicles_2.0.0_EquipmentsList:
      description: List of equipments installed in the vehicle.
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_Equipment'
    urn_samm_io.catenax.fleet.vehicles_2.0.0_Vehicle:
      description: Vehicle data that does not fit into one of the other entities.
      type: object
      properties:
        recordStatus:
          description: |-
            The record operation enumeration can be used to realize delta update concept.
            Delta update concept means:
            - You transfer an initial load of data
            - After the first week only the delta to the initial load is transferred


            The record status describes whether this record is:
            - new=>This record is transferred the first time
            - update=> Some properties of this record have changed compared to a previous transfer
            - delete=> This record was transferred in the initial load or in a previous delta update, but is not used any more and therefore it should be deleted on data consumer side
            - same=> This record was transferred in the initial load or in a previous delta update
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_RecordStatusEnumeration'
        anonymizedVin:
          description: OEM-specific hashed VIN; link to car data over pseydomized/hashed
            VIN or Catena-X unique digital twin identifier.
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_UniqueID'
        catenaXVehicleId:
          description: A unique identifier for the vehicle in the Catena-X data space.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait'
        class:
          description: Class of the vehicle.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        driveSystemPower:
          description: Complete power of this vehicle in KW. This sums up the power
            of each individual engine installed in this vehicle.
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_EnginePower'
        driveType:
          description: Drive type of a vehicle according enumeration.
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_DriveTypeNHTSA'
        powerTrainType:
          description: Describes the installed powertrain in the vehicle.
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_PowerTrainTypes'
        modelDescription:
          description: Detail vehicle model like "Golf VIII"
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        modelIdentifier:
          description: OEM-specific model identifier or OEM-specific project name.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        plantCatenaXId:
          description: "Unique Catena-X plant identifier, also called BPNS."
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnsTrait'
        plantCountryCode:
          description: "Country code of the plant, where the vehicle was produced."
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_CountryCodeTrait'
        plantDescription:
          description: Long name of the production plant of the vehicle
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        plantIdentifier:
          description: Plant id of the final assembly of the vehicle
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_UniqueID'
        productionDate:
          description: Production date of the vehicle
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
        softwareCategory:
          description: |-
            Some OEMs bring in the software as complete package for all systems:
            To identify this software: software category and software version is needed.
            Software category when this car was built.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        softwareVersion:
          description: |-
            Some OEMs brings in the software as complete package for all systems:
            To identify this software: software category and software version is needed.
            Software version when this car was built
            .
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        soldCountryCode:
          description: The country code in 3 letter format where this vehicle was
            sold.
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_CountryCodeTrait'
        soldCountryGroup:
          description: The region where this car was sold.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        soldDate:
          description: Sold date of the vehicle = warranty start date for this vehicle
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
        steeringPos:
          description: "Position of vehicle steering wheel, Left or right."
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_VehicleSteeringPos'
        vehicleSeries:
          description: "vehicle series, normally one level above model. E.g. vehicle\
            \ series =\"Golf\", vehicle model=\"Golf VIII\""
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        wmiCode:
          description: The world manufacturer index are the first 3 letters of the
            VIN. IT describes a code for the vehicle manufacturer. Also see the description
            from NTHSA.
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_OemShortNameTrait'
        wmiNameNHTSA:
          description: "Name of the vehicle manufacturer according NHTSA: use https://vpic.nhtsa.dot.gov/api/vehicles/decodewmi/WVW?format=json\
            \ - entry to be used is CommonName."
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        engines:
          description: List of installed engines in the vehicle.
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_EnginesList'
        equipments:
          description: Equipments.
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_EquipmentsList'
      required:
      - anonymizedVin
    urn_samm_io.catenax.fleet.vehicles_2.0.0_VehiclesList:
      description: List of vehicles
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_Vehicle'
    urn_samm_io.catenax.fleet.vehicles_2.0.0_MetaCharacteristic:
      description: Characteristic for the meta information.
      type: object
      properties:
        selectionCriteria:
          description: Describes the selection criteria a Catena-X data provider has
            applied to create this data set.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        selectionStart:
          description: Describes the starting point for providing records in this
            data set.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        selectionEnd:
          description: Describes the end point for providing records in this data
            set.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
      required:
      - selectionCriteria
    Vehicles:
      description: "This aspect model was created in the Catena-X use case quality.\
        \ The purpose of this aspect model is to transfer general information of a\
        \ list/fleet of vehicles - primarily how the vehicles are equipped, when they\
        \ were built and which engines are installed."
      type: object
      properties:
        listOfVehicles:
          description: List of Vehicle.ProductDescription
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_VehiclesList'
        metaInformation:
          description: 'This meta information is valid for all entries in this data
            set. The meta information is used to tell the data consumer which selection
            criteria were applied by the data provider. '
          $ref: '#/components/schemas/urn_samm_io.catenax.fleet.vehicles_2.0.0_MetaCharacteristic'
      required:
      - listOfVehicles
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Vehicles:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    Vehicles:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Vehicles'
