---
openapi: 3.0.3
info:
  title: Parts Analysis
  version: v4
  x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:4.0.0#PartsAnalyses"
servers:
- url: catenax.io/api/v4
  variables:
    api-version:
      default: v4
paths:
  /{tenant-id}/parts-analyses:
    get:
      tags:
      - PartsAnalyses
      operationId: getPartsAnalyses
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/PartsAnalyses"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/PartsAnalyses"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    UniqueID:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#UniqueID"
      description: This Characteristic is linked to a property that is unique. Please
        see description of the linked property to get more details about uniqueness.
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    Boolean:
      type: boolean
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Boolean"
      description: Represents a boolean value (i.e. a "flag").
    Text:
      type: string
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text"
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    StatusCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:4.0.0#StatusCharacteristic"
      description: Enumeration of the different status values
      enum:
      - new
      - in progress
      - completed
      - closed
    RecordStatusEnumeration:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#RecordStatusEnumeration"
      description: Defining the enumeration for the record status
      enum:
      - new
      - updated
      - deleted
      - same
    AdditionalInformation:
      description: One key:value information pair
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#AdditionalInformation"
      type: object
      properties:
        key:
          description: Key identifier for this additional information
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#key"
          $ref: "#/components/schemas/Text"
        value:
          description: Value for this additional information
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#value"
          $ref: "#/components/schemas/Text"
      required:
      - key
      - value
    AdditionalInformationList:
      description: A list of additional information.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#AdditionalInformationList"
      type: array
      items:
        $ref: "#/components/schemas/AdditionalInformation"
    Part:
      description: "A collection of part/component properties. A Catena-X data provider\
        \ should provide the  properties that are useful for a Catena-X data consumer\
        \ to clearly identify the part/component. For example, this can be done by\
        \ using a serial number, data matrix code or delivery note"
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#Part"
      type: object
      properties:
        partName:
          description: The name of a part. A part name is not unique - same kinds
            of parts can have the same part name.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#partName"
          $ref: "#/components/schemas/Text"
        partDescription:
          description: A textual description of the part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#partDescription"
          $ref: "#/components/schemas/Text"
        assemblyPartNumberVersion:
          description: "Often vehicle manufacturer specific: An assembly part number\
            \ version. Assembly parts are often produced by a supplier that combines\
            \ his own parts with other parts from other suppliers and ships as one\
            \ assembly to a vehicle manufacturer."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#assemblyPartNumberVersion"
          $ref: "#/components/schemas/Text"
        batchNumber:
          description: A batch number describes all parts that were manufactured in
            the same run.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#batchNumber"
          $ref: "#/components/schemas/Text"
        calibrationInformation:
          description: Calibration for this ECU. This could be the result of a calibration
            process.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#calibrationInformation"
          $ref: "#/components/schemas/Text"
        partId:
          description: A unique part identifier in this data-space. Property is optional
            as of now not all parts have this identifier.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#partId"
          $ref: "#/components/schemas/UuidV4Trait"
        dataMatrixCode:
          description: "String that is encoded in a data matrix code. Data matrix\
            \ codes or short DMC are labelled/printed on parts. Example: A data matrix\
            \ code can combine supplier name, part type, manufacturing and many more\
            \ information. A DMC string is often unique within this data provider."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#dataMatrixCode"
          $ref: "#/components/schemas/UniqueID"
        deliveryNote:
          description: The delivery note of a package. A delivery note is unique within
            one logistics company.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#deliveryNote"
          $ref: "#/components/schemas/UniqueID"
        hwVersion:
          description: The hardware version of this part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#hwVersion"
          $ref: "#/components/schemas/Text"
        orderNumber:
          description: The order number of this order. This is a unique identifier
            defined by the supplier of the order. If you combine order number and
            BPNL of the supplier you get a unique identifier in this data-space.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#orderNumber"
          $ref: "#/components/schemas/UniqueID"
        partNumber:
          description: The number of a physical part. A part number is not unique
            - same kinds of parts can have same part numbers. Part numbers and part
            description normally relate to each other.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#partNumber"
          $ref: "#/components/schemas/Text"
        partVersion:
          description: The version of this hardware part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#partVersion"
          $ref: "#/components/schemas/Text"
        serialNumber:
          description: Serial number of one specific part. A serial number is unique
            within one company. If you combine serial number with BPNL of that company
            than you get a unique identifier for this part in this data-space.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#serialNumber"
          $ref: "#/components/schemas/UniqueID"
        swPartNumber:
          description: Software number installed in this electronic control unit.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#swPartNumber"
          $ref: "#/components/schemas/Text"
        swVersion:
          description: Software version installed in this electronic control unit.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#swVersion"
          $ref: "#/components/schemas/Text"
        variantInfomation:
          description: "An electronic control unit has many parameters that have to\
            \ be set to work correctly: Examples are target market (which functions\
            \ need to be activated for the target market) or the equipment of the\
            \ vehicle (e.g. navigation system is installed)."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#variantInfomation"
          $ref: "#/components/schemas/Text"
      required:
      - partName
    PartAnalysis:
      description: The analysis results of ONE part
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:4.0.0#PartAnalysis"
      type: object
      properties:
        componentManufacturerAnalysisID:
          description: Internal identifier for this analysis inside component manufacturer
            company.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:4.0.0#componentManufacturerAnalysisID"
          $ref: "#/components/schemas/UniqueID"
        anonymizedVIN:
          description: "Vehicle manufacturer-specific anonymized VIN, which is still\
            \ a unique identifier within this data provider."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#anonymizedVIN"
          $ref: "#/components/schemas/UniqueID"
        qualityTaskId:
          description: A unique quality task identifier within this data-space.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#qualityTaskId"
          $ref: "#/components/schemas/UuidV4Trait"
        catenaXPartnerAnalysisID:
          description: The analysis identifier of your Catena-X partner company. Catena-X
            partner could be a vehicle manufacturer.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:4.0.0#catenaXPartnerAnalysisID"
          $ref: "#/components/schemas/UniqueID"
        isDefect:
          description: "True: Analysis turned out that analysed part is defect according\
            \ part's specification."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:4.0.0#isDefect"
          $ref: "#/components/schemas/Boolean"
        resultsDescription:
          description: Detailed description of part analysis results.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:4.0.0#resultsDescription"
          $ref: "#/components/schemas/Text"
        status:
          description: Status of this part analysis
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:4.0.0#status"
          $ref: "#/components/schemas/StatusCharacteristic"
        recordStatus:
          description: "The record operation enumeration can be used to realize delta\
            \ update concept. An example using scenario that data delivery runs weekly:\
            \ Week0: All data is transferred -> all rows have recordStatus=new. Week1:\
            \ Only the changed data is transferred: That means new rows, or updated\
            \ or deleted rows: New rows get recordStatus=new, changed rows get recordStatus=changed\
            \ and deleted/removed rows get recordStatus=deleted."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#recordStatus"
          $ref: "#/components/schemas/RecordStatusEnumeration"
        additionalInformationList:
          description: You can use this key:value list for additional properties that
            were not defined in this aspect model.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#additionalInformationList"
          $ref: "#/components/schemas/AdditionalInformationList"
      required:
      - componentManufacturerAnalysisID
      - anonymizedVIN
      - qualityTaskId
      allOf:
      - $ref: "#/components/schemas/Part"
    PartsAnalysesList:
      description: A list for multiple part analyses
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:4.0.0#PartsAnalysesList"
      type: array
      items:
        $ref: "#/components/schemas/PartAnalysis"
    MetaCharacteristic:
      description: Characteristic for the meta information.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#MetaCharacteristic"
      type: object
      properties:
        selectionCriteria:
          description: Describes the selection criteria a Catena-X data provider has
            applied to create this data set.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#selectionCriteria"
          $ref: "#/components/schemas/Text"
        selectionStart:
          description: Describes the starting point for providing records in this
            data set.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#selectionStart"
          $ref: "#/components/schemas/Text"
        selectionEnd:
          description: Describes the end point for providing records in this data
            set.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#selectionEnd"
          $ref: "#/components/schemas/Text"
      required:
      - selectionCriteria
    PartsAnalyses:
      description: "For Catena-X(CX) business case Quality Management. Supported technical\
        \ features: delta update feature, meta information feature and additionalInformationList\
        \ key-value pairs. The supported model features are described in detail in\
        \ the Catena-X Quality KIT. PartsAnalyses (hint: analyses is plural of one\
        \ analysis) data model is usd to exchange analysis results of parts. Assumption:\
        \ If a Quality Task exist a random sample of parts are sent to parts manufacturer\
        \ to analyze these parts for potential malfunction."
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:4.0.0#PartsAnalyses"
      properties:
        partsAnalyses:
          description: A list of analysis result of several parts.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:4.0.0#partsAnalyses"
          $ref: "#/components/schemas/PartsAnalysesList"
        metaInformation:
          description: 'This meta information is valid for all entries in this data
            set. The meta information is used to tell the data consumer which selection
            criteria were applied by the data provider. '
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quality_core:1.0.0#metaInformation"
          $ref: "#/components/schemas/MetaCharacteristic"
      required:
      - partsAnalyses
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    PartsAnalyses:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    PartsAnalyses:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PartsAnalyses"
      required: true
