---
openapi: 3.0.3
info:
  title: material for homologation
  version: v1
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/material-for-homologation:
    get:
      tags:
      - MaterialForHomologation
      operationId: getMaterialForHomologation
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/MaterialForHomologation'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MaterialForHomologation'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_bamm_io.catenax.material_for_homologation_1.0.0_ItemNumber1Trait:
      type: string
      description: Characteristic to describe the individual component to which the
        materials belong.
      maxLength: 200
    urn_bamm_io.catenax.material_for_homologation_1.0.0_ShareCharacteristic:
      type: number
      description: Characteristic to represent the proportion of the material.
    urn_bamm_io.catenax.material_for_homologation_1.0.0_MainGroupTrait1:
      type: string
      description: Characteristic to describe the main group classification of the
        VDA standard 231-10.
      maxLength: 2
    urn_bamm_io.catenax.material_for_homologation_1.0.0_SubgroupTrait1:
      type: string
      description: Characteristic to describe the first subgroup classification of
        the VDA standard 231-11.
      maxLength: 3
    urn_bamm_io.catenax.material_for_homologation_1.0.0_VDAStandardIdCharacteristic:
      description: Characteristic to describe the classification of a VDA standard
        ID.
      type: object
      properties:
        mainGroup:
          description: Main group according to material classification VDA 231-10.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_homologation_1.0.0_MainGroupTrait1'
        subgroup:
          description: First subgroup according to material classification VDA 231-11.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_homologation_1.0.0_SubgroupTrait1'
      required:
      - mainGroup
      - subgroup
    urn_bamm_io.catenax.material_for_homologation_1.0.0_NameTrait1:
      type: string
      description: Characteristic to designate the material.
      maxLength: 50
    urn_bamm_io.catenax.material_for_homologation_1.0.0_StandardTrait1:
      type: string
      description: Describes the standard in which the material is listed.
      maxLength: 20
    urn_bamm_io.catenax.material_for_homologation_1.0.0_MaterialNumberTrait1:
      type: string
      description: Characteristic to represent the number of the material in the standard.
      maxLength: 20
    urn_bamm_io.catenax.material_for_homologation_1.0.0_MaterialForHomologationEntity:
      description: Entity that represents the material that describes and calculates
        the recycling quota for the homologation of a vehicle type.
      type: object
      properties:
        itemNumber:
          description: Individual component to which the materials belong (no materials
            are assigned to nodes).
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_homologation_1.0.0_ItemNumber1Trait'
        share:
          description: Proportion of the material.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_homologation_1.0.0_ShareCharacteristic'
        vdaStandardId:
          description: German quality management system standard.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_homologation_1.0.0_VDAStandardIdCharacteristic'
        name:
          description: Designation of the material.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_homologation_1.0.0_NameTrait1'
        standard:
          description: Standard in which the material is listed.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_homologation_1.0.0_StandardTrait1'
        materialNumber:
          description: The number of the material in the standard.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_homologation_1.0.0_MaterialNumberTrait1'
      required:
      - itemNumber
      - share
      - vdaStandardId
      - name
      - standard
      - materialNumber
    urn_bamm_io.catenax.material_for_homologation_1.0.0_MaterialForHomologationCharacteristic:
      description: Characteristic to describe a set of materials that describe and
        calculate the recycling quota for the homologation of a vehicle type.
      type: array
      items:
        $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_homologation_1.0.0_MaterialForHomologationEntity'
      uniqueItems: true
    MaterialForHomologation:
      description: Model to depict materials that describe and calculate the recycling
        quota for the homologation of a vehicle type.
      type: object
      properties:
        materialForHomologation:
          description: Property that references the material that describes and calculate
            the recycling quota for the homologation of a vehicle type.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_homologation_1.0.0_MaterialForHomologationCharacteristic'
      required:
      - materialForHomologation
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    MaterialForHomologation:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    MaterialForHomologation:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MaterialForHomologation'
