---
openapi: 3.0.3
info:
  title: Just in Sequence Part
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#JustInSequencePart"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/just-in-sequence-part:
    get:
      tags:
      - JustInSequencePart
      operationId: getJustInSequencePart
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/JustInSequencePart"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/JustInSequencePart"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    CatenaXIdTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#CatenaXIdTrait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    KeyCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#KeyCharacteristic"
      description: |-
        The key characteristic of a local identifier. A specific subset of keys is predefined, but additionally any other custom key is allowed. Predefined keys (to be used when applicable):
        - "manufacturerId" - The Business Partner Number (BPN) of the manufacturer. Value: BPN-Nummer
        - "jisNumber" - a number that is used to identify the call-off that can be assumed unique within the specific just-in-sequence process. This is typically not the sequence number, but the call-off number.
        - "jisCallDate" the date of the just-in-sequence call-off as stated on the call-off document itself. Value: following the ISO 8601 format as follows: "YYYY-MM-DD" or "YYYY-MM-DDThh:mm:ss" or "YYYY-MM-DDThh:mm:ss±hh:mm"
        - "parentOrderNumber" - a number identifying the just-in-sequence- part's destination parent part. The parent part is typically known upfront to the supplier for just-in-sequence parts. This might be a temporary unique identifier.
        Not all keys might be relevant for all just-in-sequence parts. It must be ensured that a combination of these identifiers and the optional manufacturer part ID or customer part ID leads to a unique just-in-sequence part.
    ValueCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#ValueCharacteristic"
      description: The value of an identifier.
    KeyValueList:
      description: "A list of key value pairs for local identifiers, which are composed\
        \ of a key and a corresponding value."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#KeyValueList"
      type: object
      properties:
        key:
          description: 'The key of a local identifier. '
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#key"
          $ref: "#/components/schemas/KeyCharacteristic"
        value:
          description: The value of an identifier.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#value"
          $ref: "#/components/schemas/ValueCharacteristic"
      required:
      - key
      - value
    LocalIdentifierCharacteristic:
      description: "A single just-in-sequence part may have multiple attributes, that\
        \ uniquely identify a that part in a specific dataspace (e.g. the manufacturer`s\
        \ dataspace)"
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#LocalIdentifierCharacteristic"
      type: array
      items:
        $ref: "#/components/schemas/KeyValueList"
      uniqueItems: true
    Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Timestamp"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    ProductionCountryCodeTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#ProductionCountryCodeTrait"
      description: 'Regular Expression that ensures a three-letter code '
      pattern: "^[A-Z][A-Z][A-Z]$"
    ManufacturingCharacteristic:
      description: Characteristic to describe manufacturing related data
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#ManufacturingCharacteristic"
      type: object
      properties:
        date:
          description: "Timestamp of the manufacturing date as the final step in production\
            \ process (e.g. final quality check, ready-for-shipment event)"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#date"
          $ref: "#/components/schemas/Timestamp"
        country:
          description: Country code where the part was manufactured
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#country"
          $ref: "#/components/schemas/ProductionCountryCodeTrait"
      required:
      - date
    PartIdCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#PartIdCharacteristic"
      description: "The part ID is a multi-character string, usually assigned by an\
        \ ERP system. Alternatively the ID of the part family can be used if no specific\
        \ part ID exists."
    PartNameCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#PartNameCharacteristic"
      description: Part Name in string format from the respective system in the value
        chain
    ClassificationCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#ClassificationCharacteristic"
      description: "A part type must be placed into one of the following classes:\
        \ 'component', 'product', 'software', 'assembly', 'tool', or 'raw material'."
      enum:
      - product
      - raw material
      - software
      - assembly
      - tool
      - component
    PartTypeInformationCharacteristic:
      description: The characteristics of the part type
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#PartTypeInformationCharacteristic"
      type: object
      properties:
        manufacturerPartId:
          description: "Part ID as assigned by the manufacturer of the part. The manufacturer\
            \ Part ID identifies the part (as designed) in the manufacturer`s dataspace.\
            \ The Part ID does not reference a specific instance of a part and thus\
            \ should not be confused with the serial number or any other instance\
            \ IDs. \nIf no specific part ID exists a part family ID may be substituted\
            \ for it."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#manufacturerPartId"
          $ref: "#/components/schemas/PartIdCharacteristic"
        customerPartId:
          description: "Part ID as assigned by the customer of the part. The customer\
            \ Part ID identifies the part (as designed) in the customer`s dataspace.\
            \ The Part ID does not reference a specific instance of a part and thus\
            \ should not be confused with the serial number or any other instance\
            \ IDs. \nIf no specific part ID exists a part family ID may be substituted\
            \ for it.\n"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#customerPartId"
          $ref: "#/components/schemas/PartIdCharacteristic"
        nameAtManufacturer:
          description: Name of the part as assigned by the manufacturer
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#nameAtManufacturer"
          $ref: "#/components/schemas/PartNameCharacteristic"
        nameAtCustomer:
          description: Name of the part as assigned by the customer
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#nameAtCustomer"
          $ref: "#/components/schemas/PartNameCharacteristic"
        classification:
          description: The classification of the part type according to STEP standard
            definition
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#classification"
          $ref: "#/components/schemas/ClassificationCharacteristic"
      required:
      - nameAtManufacturer
      - classification
    JustInSequencePart:
      description: "A just-in-sequence part is an instantiation of a (design-) part,\
        \ where the particular instantiation can be uniquely identified by means of\
        \ a combination of several IDs related to a just-in-sequence process."
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#JustInSequencePart"
      properties:
        catenaXId:
          description: "The fully anonymous Catena-X ID of the just-in-sequence part,\
            \ valid for the Catena-X dataspace."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#catenaXId"
          $ref: "#/components/schemas/CatenaXIdTrait"
        localIdentifiers:
          description: "A local identifier enables identification of a part in a specific\
            \ dataspace, but is not unique in Catena-X dataspace. Multiple local identifiers\
            \ may exist."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#localIdentifiers"
          $ref: "#/components/schemas/LocalIdentifierCharacteristic"
        manufacturingInformation:
          description: "Information from manufacturing process, such as manufacturing\
            \ date and manufacturing country"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#manufacturingInformation"
          $ref: "#/components/schemas/ManufacturingCharacteristic"
        partTypeInformation:
          description: The part type or part family from which the just-in-sequence
            part has been instantiated.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.just_in_sequence_part:1.0.0#partTypeInformation"
          $ref: "#/components/schemas/PartTypeInformationCharacteristic"
      required:
      - catenaXId
      - localIdentifiers
      - manufacturingInformation
      - partTypeInformation
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    JustInSequencePart:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    JustInSequencePart:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/JustInSequencePart"
      required: true
