---
openapi: 3.0.3
info:
  title: Single level bill of material as planned
  version: v1
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/single-level-bom-as-planned:
    get:
      tags:
      - SingleLevelBomAsPlanned
      operationId: getSingleLevelBomAsPlanned
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/SingleLevelBomAsPlanned'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SingleLevelBomAsPlanned'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_bamm_io.catenax.single_level_bom_as_planned_1.0.1_CatenaXIdTraitCharacteristic:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    urn_bamm_io.catenax.single_level_bom_as_planned_1.0.1_NumberofObjects:
      type: number
      description: Quantifiable number of objects in reference to the measurementUnit
    urn_bamm_io.openmanufacturing_characteristic_2.0.0_UnitReference:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      description: Describes a Property containing a reference to one of the units
        in the Unit Catalog.
    urn_bamm_io.catenax.single_level_bom_as_planned_1.0.1_QuantityCharacteristic:
      description: Describes the quantity in which the child part is assembled in
        the given parent object by providing a quantity value and the measurement
        unit in which the quantity is measured.
      type: object
      properties:
        quantityNumber:
          description: The number of objects related to the measurement unit
          $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_planned_1.0.1_NumberofObjects'
        measurementUnit:
          description: Unit of Measurement for the quantity of serialized objects
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_UnitReference'
      required:
      - quantityNumber
      - measurementUnit
    urn_bamm_io.catenax.single_level_bom_as_planned_1.0.1_ChildData:
      description: Catena-X ID and meta data of the child part.
      type: object
      properties:
        createdOn:
          description: Timestamp when the relation between the parent part and the
            child part was created
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp'
        quantity:
          description: Quantity of which the child part is assembled into the parent
            part.
          $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_planned_1.0.1_QuantityCharacteristic'
        lastModifiedOn:
          description: Timestamp when the relationship between parent part and child
            part was last modified.
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp'
        childCatenaXId:
          description: The Catena-X ID of the child object which is assembled into
            the given parent part.
          $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_planned_1.0.1_CatenaXIdTraitCharacteristic'
      required:
      - createdOn
      - quantity
      - childCatenaXId
    urn_bamm_io.catenax.single_level_bom_as_planned_1.0.1_SetOfChildPartsCharacteristic:
      description: Set of child parts the parent object is assembled by (one structural
        level down).
      type: array
      items:
        $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_planned_1.0.1_ChildData'
      uniqueItems: true
    SingleLevelBomAsPlanned:
      description: The single-level Bill of Material represents one sub-level of an
        assembly and does not include any lower-level subassemblies. In As-Planned
        lifecycle state all variants are covered ("120% BOM"). It includes multiple
        suppliers for the same component.
      type: object
      properties:
        catenaXId:
          description: "The Catena-X ID of the given part (e.g. the component), valid\
            \ for the Catena-X dataspace."
          $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_planned_1.0.1_CatenaXIdTraitCharacteristic'
        childParts:
          description: "Set of child parts in As-Planned lifecycle phase, of which\
            \ the given parent object is assembled by (one structural level down)."
          $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_planned_1.0.1_SetOfChildPartsCharacteristic'
      required:
      - catenaXId
      - childParts
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    SingleLevelBomAsPlanned:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    SingleLevelBomAsPlanned:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SingleLevelBomAsPlanned'
