---
openapi: 3.0.3
info:
  title: Provide Production Forecast
  version: v2
  x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#ProvideProductionForecast"
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/provide-production-forecast:
    get:
      tags:
      - ProvideProductionForecast
      operationId: getProvideProductionForecast
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: "#/components/responses/ProvideProductionForecast"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:1.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Timestamp"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    TimeUnitEnum:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:2.0.0#TimeUnitEnum"
      description: Enumerates all time units
      enum:
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hour
      - unit:day
      - unit:week
      - unit:month
      - unit:year
    IntegerValueCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:2.0.0#IntegerValueCharacteristic"
      description: The value of the specified timeUnit as an integer value
    TimeValueCharacteristic:
      description: Link to the  TimeUnit Data Type
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:2.0.0#TimeValueCharacteristic"
      type: object
      properties:
        timeUnit:
          description: Specifies the unit in which the time is represented
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:2.0.0#timeUnit"
          $ref: "#/components/schemas/TimeUnitEnum"
        value:
          description: The amount of timeUnits considered
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:2.0.0#value"
          $ref: "#/components/schemas/IntegerValueCharacteristic"
      required:
      - timeUnit
      - value
    ProductionStatusEnum:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#ProductionStatusEnum"
      description: Enumeration with all possible states of an order within modular
        production
      enum:
      - itemReceived
      - itemPlanned
      - itemInProduction
      - itemCompleted
      - statusUndefined
    ReasonsForDelayEnum:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#ReasonsForDelayEnum"
      description: Enum that specifies reasons for a delay of an order
      enum:
      - supplyProblems
      - otherCircumstances
      - internalProblems
      - noInformationAvailable
    ReturnCodeEnum:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#ReturnCodeEnum"
      description: Enumeration with all Return Codes
      enum:
      - ok
      - lowerAccuracyOfPrecision
      - noForecastAvailable
    ForecastItem:
      description: ForecastItem entry for the requested order
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#ForecastItem"
      type: object
      properties:
        positionId:
          description: Identifier of a position of an order
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#positionId"
          $ref: "#/components/schemas/UuidV4Trait"
        productionForecast:
          description: Date of completion
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#productionForecast"
          $ref: "#/components/schemas/Timestamp"
        precisionOfForecast:
          description: Accuracy of the prediction
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#precisionOfForecast"
          $ref: "#/components/schemas/TimeValueCharacteristic"
        productionStatus:
          description: Status of the order/position within MP
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#productionStatus"
          $ref: "#/components/schemas/ProductionStatusEnum"
        reasonsForDelay:
          description: Optional field to provide information to the customer why a
            delivery date is not met
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#reasonsForDelay"
          $ref: "#/components/schemas/ReasonsForDelayEnum"
        returnCode:
          description: Return code that indicates whether a single item of an order
            matches the customers desired request
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#returnCode"
          $ref: "#/components/schemas/ReturnCodeEnum"
        forecastDate:
          description: Date/time of the forecast calculation
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#forecastDate"
          $ref: "#/components/schemas/Timestamp"
      required:
      - positionId
      - productionForecast
      - precisionOfForecast
      - productionStatus
      - returnCode
      - forecastDate
    ForecastItemList:
      description: List with the forecast items
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#ForecastItemList"
      type: array
      items:
        $ref: "#/components/schemas/ForecastItem"
    CommunicationModeEnum:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:2.0.0#CommunicationModeEnum"
      description: Enumerates all possible communication modes
      enum:
      - synchronous
      - cyclic
      - notification
    SemanticVersioningTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#SemanticVersioningTrait"
      description: Constraint for defining a SemVer version.
      pattern: "^(0|[1-9][0-9]*).(0|[1-9][0-9]*).(0|[1-9][0-9]*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*)(.[0-9A-Za-z-]+)*)?([0-9A-Za-z-]+(.[0-9A-Za-z-]+)*)?$"
    ProductionForecastCharacteristic:
      description: All Data that is related to a production forecast
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#ProductionForecastCharacteristic"
      type: object
      properties:
        listOfForecastItems:
          description: List of ForecastItems matching the items to an order
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#listOfForecastItems"
          $ref: "#/components/schemas/ForecastItemList"
        iterationNumber:
          description: "Only set in CommunicationMode == \"notification/cyclic\" to\
            \ be able to check the order of the notifications. \n\nNot required for\
            \ communication mode = \"synchronous\""
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#iterationNumber"
          $ref: "#/components/schemas/IntegerValueCharacteristic"
        communicationMode:
          description: Specification of the communication mode
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.shopfloor_information_types:2.0.0#communicationMode"
          $ref: "#/components/schemas/CommunicationModeEnum"
        version:
          description: The unique identifier of the aspect model defining the structure
            and the semantics of the message's header. The version number should reflect
            the versioning schema of aspect models in Catena-X.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#version"
          $ref: "#/components/schemas/SemanticVersioningTrait"
      required:
      - listOfForecastItems
      - communicationMode
      - version
    ContextCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#ContextCharacteristic"
      description: Defining a string value for the context
    BpnlTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:1.0.0#BpnlTrait"
      description: "The provided regular expression ensures that the BPNL is composed\
        \ of prefix 'BPNL', 10 digits and two uppercase letters."
      pattern: "^BPNL[0-9]{8}[a-zA-Z0-9]{4}$"
    HeaderCharacteristic:
      description: Characteristic describing the common shared aspect Message Header
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#HeaderCharacteristic"
      type: object
      properties:
        messageId:
          description: "Unique ID identifying the message. The purpose of the ID is\
            \ to uniquely identify a single message, therefore it MUST not be reused."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#messageId"
          $ref: "#/components/schemas/UuidV4Trait"
        context:
          description: |-
            Information about the context the message should be considered in.
            The value MUST consist of two parts: an identifier of the context (e.g. business domain, etc.) followed by a version number.
            Both the identifier and the version number MUST correspond to the content of the message.
            If the content of a message is described by an aspect model available in the Catena-X Semantic Hub, then the unique identifier of this semantic model (e.g. urn:samm:io.catenax.<ASPECT-MODEL-NAME>:1.x.x) MUST be used as a value of the context field. This is considered the default case.
            In all other cases the value of the context field MUST follow the pattern <domain>-<subdomain>-<object>:<[major] version> (e.g. TRACE-QM-Alert:1.x.x).
            Versioning only refers to major versions in both default and fallback cases.
            Note: The version of the message's header is specified in the version field.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#context"
          $ref: "#/components/schemas/ContextCharacteristic"
        sentDateTime:
          description: Time zone aware timestamp holding the date and the time the
            message was sent by the sending party. The value MUST be formatted according
            to the ISO 8601 standard
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#sentDateTime"
          $ref: "#/components/schemas/Timestamp"
        senderBpn:
          description: The Business Partner Number of the sending party. The value
            MUST be a valid BPN. BPNA and BPNS are not allowed. Applicable constraints
            are defined in the corresponding standard
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#senderBpn"
          $ref: "#/components/schemas/BpnlTrait"
        receiverBpn:
          description: The Business Partner Number of the receiving party. The value
            MUST be a valid BPN. BPNA and BPNS are not allowed. Applicable constraints
            are defined in the corresponding standard.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#receiverBpn"
          $ref: "#/components/schemas/BpnlTrait"
        expectedResponseBy:
          description: Time zone aware timestamp holding the date and time by which
            the sending party expects a certain type of response from the receiving
            party. The meaning and interpretation of the fields's value are context-bound
            and MUST therefore be defined by any business domain or platform capability
            making use of it. The value MUST be formatted according to the ISO 8601
            standard
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#expectedResponseBy"
          $ref: "#/components/schemas/Timestamp"
        relatedMessageId:
          description: Unique ID identifying a message somehow related to the current
            one
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#relatedMessageId"
          $ref: "#/components/schemas/UuidV4Trait"
        version:
          description: The unique identifier of the aspect model defining the structure
            and the semantics of the message's header. The version number should reflect
            the versioning schema of aspect models in Catena-X.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#version"
          $ref: "#/components/schemas/SemanticVersioningTrait"
      required:
      - messageId
      - context
      - sentDateTime
      - senderBpn
      - receiverBpn
      - version
    ProvideProductionForecast:
      description: Answer to a customer with all information about the requested items
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#ProvideProductionForecast"
      properties:
        productionForecastResponse:
          description: The concrete information about a production forecast
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_forecast:2.0.0#productionForecastResponse"
          $ref: "#/components/schemas/ProductionForecastCharacteristic"
        header:
          description: Contains standardized attributes for message processing common
            across several use cases.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#header"
          $ref: "#/components/schemas/HeaderCharacteristic"
      required:
      - productionForecastResponse
      - header
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    ProvideProductionForecast:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProvideProductionForecast"
      description: The request was successful.
  requestBodies:
    ProvideProductionForecast:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProvideProductionForecast"
      required: true
