---
openapi: 3.0.3
info:
  title: Single Level Bill of Material as Built
  version: v1
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/single-level-bom-as-built:
    get:
      tags:
      - SingleLevelBomAsBuilt
      operationId: getSingleLevelBomAsBuilt
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/SingleLevelBomAsBuilt'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SingleLevelBomAsBuilt'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_CatenaXIdTraitCharacteristic:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_NumberOfObjects:
      type: number
      description: Quantifiable number of objects in reference to the measurementUnit
    urn_bamm_io.openmanufacturing_characteristic_2.0.0_UnitReference:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      description: Describes a Property containing a reference to one of the units
        in the Unit Catalog.
    urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_QuantityCharacteristic:
      description: Describes the quantity in which the child item is assembled in
        the given parent item by providing a quantity value and the measurement unit
        in which the quantity is measured.
      type: object
      properties:
        quantityNumber:
          description: The number of objects related to the measurement unit
          $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_NumberOfObjects'
        measurementUnit:
          description: Unit of Measurement for the quantity of serialized objects
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_UnitReference'
      required:
      - quantityNumber
      - measurementUnit
    urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_BpnTrait:
      type: string
      description: Business Partner Number Regular Expression allowing only BPNL which
        stands for a legal entity.
      pattern: "^(BPNL)([0-9]{8})([a-zA-Z0-9]{4})$"
    urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_ChildData:
      description: Catena-X ID and meta data of the assembled child item.
      type: object
      properties:
        createdOn:
          description: "Timestamp when the relation between the parent item and the\
            \ child item was created, e.g. when the serialized child part was assembled\
            \ into the given part."
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp'
        quantity:
          description: Quantity of which the child item is assembled into the parent
            item. In general it is '1' for serialized parts.
          $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_QuantityCharacteristic'
        lastModifiedOn:
          description: Timestamp when the assembly relationship between parent item
            and child item was last modified.
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Timestamp'
        catenaXId:
          description: "The Catena-X ID of the given part (e.g. the assembly), valid\
            \ for the Catena-X dataspace."
          $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_CatenaXIdTraitCharacteristic'
        businessPartner:
          description: The supplier of the given child item.
          $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_BpnTrait'
      required:
      - createdOn
      - quantity
      - catenaXId
    urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_SetOfChildItemsCharacteristic:
      description: Set of child items the parent item is assembled by (one structural
        level down).
      type: array
      items:
        $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_ChildData'
      uniqueItems: true
    SingleLevelBomAsBuilt:
      description: "The single-level bill of material represents one sub-level of\
        \ an assembly and does not include any lower-level subassemblies. The as-built\
        \ lifecycle references all child items as manufactured by the manufacturer\
        \ referencing only child items in an as built lifecycle themselves, e.g. serial\
        \ parts or batches."
      type: object
      properties:
        catenaXId:
          description: "The Catena-X ID of the given part (e.g. the assembly), valid\
            \ for the Catena-X dataspace."
          $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_CatenaXIdTraitCharacteristic'
        childItems:
          description: "Set of child items, of which the given parent item is assembled\
            \ by (one structural level down)."
          $ref: '#/components/schemas/urn_bamm_io.catenax.single_level_bom_as_built_1.0.0_SetOfChildItemsCharacteristic'
      required:
      - catenaXId
      - childItems
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    SingleLevelBomAsBuilt:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    SingleLevelBomAsBuilt:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SingleLevelBomAsBuilt'
