---
openapi: 3.0.3
info:
  title: Planned Production Output of a Supplier
  version: v2
  x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#PlannedProductionOutput"
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/planned-production-output:
    get:
      tags:
      - PlannedProductionOutput
      operationId: getPlannedProductionOutput
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/PlannedProductionOutput"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/PlannedProductionOutput"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    OrderIdCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#OrderIdCharacteristic"
      description: "This is a proprietary order ID, generated by either the supplier\
        \ side or customer side."
    OrderPositionIdCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#OrderPositionIdCharacteristic"
      description: The position ID is unique for an order and used within business
        context to refer to a position.
    OrderPositionReferenceCharacteristic:
      description: "The order position reference includes reference numbers for the\
        \ order and the position. As these information are meant for the customer,\
        \ the customer reference numbers are mandatory."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#OrderPositionReferenceCharacteristic"
      type: object
      properties:
        supplierOrderId:
          description: "This is the order number on the supplier side that is given\
            \ by e.g., the supplier's enterprise resource planning system."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#supplierOrderId"
          $ref: "#/components/schemas/OrderIdCharacteristic"
        customerOrderId:
          description: "This is the order number on the customer side that can be\
            \ given by e.g., the customer's enterprise resource planning system."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#customerOrderId"
          $ref: "#/components/schemas/OrderIdCharacteristic"
        customerOrderPositionId:
          description: "This is an identifier for the position of an order defined\
            \ by the customer. It's not a technical identifier, such as an UUID. This\
            \ identifier is used within the business context when talking about the\
            \ position."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#customerOrderPositionId"
          $ref: "#/components/schemas/OrderPositionIdCharacteristic"
      required:
      - customerOrderId
      - customerOrderPositionId
    QuantityValueCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#QuantityValueCharacteristic"
      description: The quantity value associated with the unit expressed as float.
    ItemUnitEnumeration:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#ItemUnitEnumeration"
      description: Enumeration for common item units.
      enum:
      - unit:piece
      - unit:set
      - unit:pair
      - unit:page
      - unit:cycle
      - unit:kilowattHour
      - unit:gram
      - unit:kilogram
      - unit:tonneMetricTon
      - unit:tonUsOrShortTonUkorus
      - unit:ounceAvoirdupois
      - unit:pound
      - unit:metre
      - unit:centimetre
      - unit:kilometre
      - unit:inch
      - unit:foot
      - unit:yard
      - unit:squareCentimetre
      - unit:squareMetre
      - unit:squareInch
      - unit:squareFoot
      - unit:squareYard
      - unit:cubicCentimetre
      - unit:cubicMetre
      - unit:cubicInch
      - unit:cubicFoot
      - unit:cubicYard
      - unit:litre
      - unit:millilitre
      - unit:hectolitre
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hourUnitOfTime
      - unit:day
    QuantityCharacteristic:
      description: Describes the quantity and the unit of measure with which the planned
        and allocated production output is measured.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#QuantityCharacteristic"
      type: object
      properties:
        value:
          description: The quantity value associated with the unit.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#quantityValue"
          $ref: "#/components/schemas/QuantityValueCharacteristic"
        unit:
          description: "The unit of an item. Common units may be related to mass,\
            \ count, linear, area, volume or misc."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#itemUnit"
          $ref: "#/components/schemas/ItemUnitEnumeration"
      required:
      - value
      - unit
    BpnsTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnsTrait"
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two alphanumeric letters."
      pattern: "^BPNS[a-zA-Z0-9]{12}$"
    Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Timestamp"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    AllocatedPlannedProductionOutput:
      description: "Quantity, site of the supplier and date with time at which a production\
        \ of a certain material for a certain customer is planned to be finished."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#AllocatedPlannedProductionOutput"
      type: object
      properties:
        plannedProductionQuantity:
          description: "Quantity of a product that a supplier plans to produce on\
            \ a certain date and time for a specific customer (that means that it\
            \ will be allocated to a specific customer's \"allocated item stock\"\
            ).\nQuantities that have already been produced are put on stock or are\
            \ considered for delivery. Therefore those quantities MUST NOT be considered\
            \ in the allocated production output to build a consistent view on the\
            \ supply situation. "
          x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#plannedProductionQuantity"
          $ref: "#/components/schemas/QuantityCharacteristic"
        productionSiteBpns:
          description: One planned and allocated production output has always one
            site. The site is identified by the BPNS.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#productionSiteBpns"
          $ref: "#/components/schemas/BpnsTrait"
        estimatedTimeOfCompletion:
          description: Date and time on which the planned and allocated production
            output is estimated to be completed. Date and time are set according to
            a timezone.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#estimatedTimeOfCompletion"
          $ref: "#/components/schemas/Timestamp"
        lastUpdatedOnDateTime:
          description: Date and time at which the allocated planned production output
            has been updated by the supplier's systems. Date and time are set according
            to the timezone.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#lastUpdatedOnDateTime"
          $ref: "#/components/schemas/Timestamp"
      required:
      - plannedProductionQuantity
      - productionSiteBpns
      - estimatedTimeOfCompletion
      - lastUpdatedOnDateTime
    AllocatedPlannedProductionOutputSet:
      description: Set of planned and allocated production outputs that may relate
        to different production locations and estimated time of completions.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#AllocatedPlannedProductionOutputSet"
      type: array
      items:
        $ref: "#/components/schemas/AllocatedPlannedProductionOutput"
      uniqueItems: true
    Position:
      description: The Position can be planned for production at several sites. A
        position may be anonymous or may reference a position within an order.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#Position"
      type: object
      properties:
        orderPositionReference:
          description: The order position reference contains information to identify
            a position within an order.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#orderPositionReference"
          $ref: "#/components/schemas/OrderPositionReferenceCharacteristic"
        allocatedPlannedProductionOutputs:
          description: Planned Production Outputs already allocated to the customer.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#allocatedPlannedProductionOutputs"
          $ref: "#/components/schemas/AllocatedPlannedProductionOutputSet"
      required:
      - allocatedPlannedProductionOutputs
    PositionsSet:
      description: "If any production for the customer is planned, then there is at\
        \ least one position. If the supplier does differentiate the planned production\
        \ according to the order positions (an OrderPositionReference is set), then\
        \ multiple positions can be given. Among the positions, there could be only\
        \ one position without an OrderPositionReference to either report the planned\
        \ production independently of orders or to report internal stock orders planned\
        \ for the customer."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#PositionsSet"
      type: array
      items:
        $ref: "#/components/schemas/Position"
      uniqueItems: true
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    PlannedProductionOutput:
      description: "This aspect represents the remaining and planned production outputs\
        \ of a supplier allocated to a customer. An allocated planned production output\
        \ is described by a quantity, the site of the supplier and the date with time\
        \ at which a production of a certain material for a certain customer is planned\
        \ to be finished. The allocated planned production outputs may be linked to\
        \ customer order position they have been scheduled for."
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#PlannedProductionOutput"
      properties:
        positions:
          description: "The positions refer to positions within an order of the given\
            \ product (see material number supplier, materialNumber customer and material\
            \ global Asset Id) for which the production outputs are transferred. The\
            \ positions can be differentiated by the order position reference. If\
            \ no order position reference is given, then there is only one position\
            \ containing all planned production outputs of the product."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#positions"
          $ref: "#/components/schemas/PositionsSet"
        materialGlobalAssetId:
          description: Identifier used uniquely to identify part type twin.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.planned_production_output:2.0.0#materialGlobalAssetId"
          $ref: "#/components/schemas/UuidV4Trait"
      required:
      - positions
      - materialGlobalAssetId
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    PlannedProductionOutput:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    PlannedProductionOutput:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PlannedProductionOutput"
      required: true
