---
openapi: 3.0.3
info:
  title: Id Based Comment
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#IdBasedComment"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/id-based-comment:
    get:
      tags:
      - IdBasedComment
      operationId: getIdBasedComment
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/IdBasedComment"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/IdBasedComment"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    AuthorCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#AuthorCharacteristic"
      description: Characteristic for an E-Mail or a BPNL
    Timestamp:
      type: string
      format: date-time
      x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#Timestamp"
      description: Point in time.
    CommentTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#CommentTrait"
      description: The provided regular expression ensures that the text of a comment
        is limited to the maximum length of 5.000 characters.
      pattern: "^[\\s\\S]{0,5000}$"
    CommentTypeCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#CommentTypeCharacteristic"
      description: The classification of a comment.
      enum:
      - information
      - warning
      - default
      - actionRequired
    Boolean:
      type: boolean
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.1.0#Boolean"
      description: Represents a boolean value (i.e. a "flag").
    ListOfReferenceDatesCharacteristic:
      description: Point in time.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#ListOfReferenceDatesCharacteristic"
      type: array
      items:
        type: string
        format: date
      uniqueItems: true
    ObjectTypeCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#ObjectTypeCharacteristic"
      description: Defining a string value for the objectType.
    BpnlTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnlTrait"
      description: "The provided regular expression ensures that the BPNL is composed\
        \ of prefix 'BPNL', 10 digits and two alphanumeric letters."
      pattern: "^BPNL[a-zA-Z0-9]{12}$"
    IdBasedComment:
      description: Aspect model for an exchange of comment belonging to a entity.
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#IdBasedComment"
      properties:
        commentId:
          description: The Comment ID uniquely identifies the entity within the business
            relationship between a customer and its supplier.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#commentId"
          $ref: "#/components/schemas/UuidV4Trait"
        objectId:
          description: The ID of the object to which the comment belongs.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#objectId"
          $ref: "#/components/schemas/UuidV4Trait"
        author:
          description: "The E-Mail address of the creator who wrote the comment. In\
            \ case comment creator wants to stay anonymous, show BPNL in app which\
            \ is sent the comment along."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#author"
          $ref: "#/components/schemas/AuthorCharacteristic"
        postedAt:
          description: Point in time when the comment was created.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#postedAt"
          $ref: "#/components/schemas/Timestamp"
        changedAt:
          description: Point in time when the comment was last changed.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#changedAt"
          $ref: "#/components/schemas/Timestamp"
        commentText:
          description: Text up to 5.000 characters in format "UTF-8" will be shared.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#commentText"
          $ref: "#/components/schemas/CommentTrait"
        commentType:
          description: Type of a comment to indicate a priority.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#commentType"
          $ref: "#/components/schemas/CommentTypeCharacteristic"
        requestDelete:
          description: Indicates that the deletion of the comment is requested by
            sender incl. all of it's history.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#requestDelete"
          $ref: "#/components/schemas/Boolean"
        listOfReferenceDates:
          description: Point in time the comment belongs to.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#listOfReferenceDates"
          $ref: "#/components/schemas/ListOfReferenceDatesCharacteristic"
        objectType:
          description: Aspect Model which the comment refers to. The value MUST consist
            of the Catena-X aspect model unique identifier of the referenced data
            model without a version.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#objectType"
          $ref: "#/components/schemas/ObjectTypeCharacteristic"
        simulationId:
          description: The simulation ID uniquely identifies a simulation scenario.
            All aspects that belong to the same simulation scenario share a simulation
            ID
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#simulationId"
          $ref: "#/components/schemas/UuidV4Trait"
        customer:
          description: The Business Partner Number Legal Entity (BPNL) of the party
            requesting materials from a supplier.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#customer"
          $ref: "#/components/schemas/BpnlTrait"
        supplier:
          description: The Business Partner Number Legal Entity (BPNL) of the party
            providing materials to a customer.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.id_based_comment:1.1.0#supplier"
          $ref: "#/components/schemas/BpnlTrait"
      required:
      - commentId
      - objectId
      - objectType
      - customer
      - supplier
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    IdBasedComment:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    IdBasedComment:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/IdBasedComment"
