---
openapi: 3.0.3
info:
  title: Part Site Information As Built
  version: v2
  x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:2.0.0#PartSiteInformationAsBuilt"
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/part-site-information-as-built:
    get:
      tags:
      - PartSiteInformationAsBuilt
      operationId: getPartSiteInformationAsBuilt
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/PartSiteInformationAsBuilt"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/PartSiteInformationAsBuilt"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    BpnsTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnsTrait"
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two alphanumeric letters."
      pattern: "^BPNS[a-zA-Z0-9]{12}$"
    FunctionCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:2.0.0#FunctionCharacteristic"
      description: Describes the characteristics of the function for a site related
        to the respective part.
      enum:
      - production
      - warehouse
      - spare part warehouse
    SitesEntity:
      description: "Describes the ID and function of a site for the associated part\
        \ in the AsBuilt context(e.g. SerialPart, Batch, jIS)."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:2.0.0#SitesEntity"
      type: object
      properties:
        catenaXsiteId:
          description: "The identifier of the site according to Catena-X BPDM. The\
            \ catenaXsiteId must be a valid Catena-X BPN. The BPN is a unique, unchangeable\
            \ identifier for Business Partners / company locations from foundation\
            \ to closure, regardless of the different business relationships / structures\
            \ between or within the Business Partners or company locations."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:2.0.0#catenaXsiteId"
          $ref: "#/components/schemas/BpnsTrait"
        function:
          description: The function of the site in relation to the part(i.e. the activity
            within the value chain of the part that is performed at the site)
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:2.0.0#function"
          $ref: "#/components/schemas/FunctionCharacteristic"
      required:
      - catenaXsiteId
      - function
    SitesCharacteristic:
      description: Sites Characteristic
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:2.0.0#SitesCharacteristic"
      type: array
      items:
        $ref: "#/components/schemas/SitesEntity"
      uniqueItems: true
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    PartSiteInformationAsBuilt:
      description: The aspect provides site related information for a given item(i.e.
        a part type or part instance that is uniquely identifiable within Catena-X
        via its Catena-X ID). A site is a delimited geographical area where a legal
        entity does business. In this context all potentially related sites are listed
        including all sites where e.g. production of this part(type).
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:2.0.0#PartSiteInformationAsBuilt"
      properties:
        sites:
          description: "A site is a delimited geographical area where a legal entity\
            \ does business(geographical address with geo coordinates).A site always\
            \ has a primary physical address. It is possible that further physical\
            \ addresses are specified for the site. P.O. box details are only possible\
            \ in addition to the physical address. A site has a 1:n relation to addresses,\
            \ means at least 1 address is necessary and multiple addresses are possible."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:2.0.0#sites"
          $ref: "#/components/schemas/SitesCharacteristic"
        catenaXId:
          description: "The Catena-X ID of the given item(i.e. a part type or part\
            \ instance), valid for the Catena-X dataspace."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:2.0.0#catenaXId"
          $ref: "#/components/schemas/UuidV4Trait"
      required:
      - sites
      - catenaXId
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    PartSiteInformationAsBuilt:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    PartSiteInformationAsBuilt:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PartSiteInformationAsBuilt"
      required: true
