---
openapi: 3.0.3
info:
  title: Stock of Items
  version: v2
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/item-stock:
    get:
      tags:
      - ItemStock
      operationId: getItemStock
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/ItemStock'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemStock'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_samm_io.catenax.item_stock_2.0.0_OrderIdCharacteristic:
      type: string
      description: "This is a proprietary order ID, generated by either the supplier\
        \ side or customer side."
    urn_samm_io.catenax.item_stock_2.0.0_OrderPositionIdCharacteristic:
      type: string
      description: The position ID is unique for an order and used within business
        context to refer to a position.
    urn_samm_io.catenax.item_stock_2.0.0_OrderPositionReferenceCharacteristic:
      description: "The order position reference includes reference numbers for the\
        \ order and the ID. As these information are meant for the customer, the customer\
        \ reference numbers are mandatory."
      type: object
      properties:
        supplierOrderId:
          description: "This is the order number on the supplier side that is given\
            \ by e.g., the supplier's enterprise resource planning system."
          $ref: '#/components/schemas/urn_samm_io.catenax.item_stock_2.0.0_OrderIdCharacteristic'
        customerOrderId:
          description: "This is the order number on the customer side that can be\
            \ given by e.g., the customer's enterprise resource planning system."
          $ref: '#/components/schemas/urn_samm_io.catenax.item_stock_2.0.0_OrderIdCharacteristic'
        customerOrderPositionId:
          description: "This is an identifier for the position of an order defined\
            \ by the customer. It's not a technical identifier, such as an UUID. This\
            \ identifier is used within the business context when talking about the\
            \ position."
          $ref: '#/components/schemas/urn_samm_io.catenax.item_stock_2.0.0_OrderPositionIdCharacteristic'
      required:
      - customerOrderId
      - customerOrderPositionId
    urn_samm_io.catenax.shared.quantity_2.0.0_QuantityValueCharacteristic:
      type: number
      description: The quantity value associated with the unit expressed as float.
    urn_samm_io.catenax.shared.quantity_2.0.0_ItemUnitEnumeration:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      description: Enumeration for common item units.
      enum:
      - unit:piece
      - unit:set
      - unit:pair
      - unit:page
      - unit:cycle
      - unit:kilowattHour
      - unit:gram
      - unit:kilogram
      - unit:tonneMetricTon
      - unit:tonUsOrShortTonUkorus
      - unit:ounceAvoirdupois
      - unit:pound
      - unit:metre
      - unit:centimetre
      - unit:kilometre
      - unit:inch
      - unit:foot
      - unit:yard
      - unit:squareCentimetre
      - unit:squareMetre
      - unit:squareInch
      - unit:squareFoot
      - unit:squareYard
      - unit:cubicCentimetre
      - unit:cubicMetre
      - unit:cubicInch
      - unit:cubicFoot
      - unit:cubicYard
      - unit:litre
      - unit:millilitre
      - unit:hectolitre
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hourUnitOfTime
      - unit:day
    urn_samm_io.catenax.item_stock_2.0.0_QuantityCharacteristic:
      description: Describes the quantity on stock of the item defined by a quantity
        value and the measurement unit in which the quantity is measured.
      type: object
      properties:
        value:
          description: The quantity value associated with the unit.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.quantity_2.0.0_QuantityValueCharacteristic'
        unit:
          description: "The unit of an item. Common units may be related to mass,\
            \ count, linear, area, volume or misc."
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.quantity_2.0.0_ItemUnitEnumeration'
      required:
      - value
      - unit
    urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnsTrait:
      type: string
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two alphanumeric letters."
      pattern: "^BPNS[a-zA-Z0-9]{12}$"
    urn_samm_io.catenax.item_stock_2.0.0_IsBlockedCharacteristic:
      type: boolean
      description: Boolean characteristic indicating whether a stock is blocked (true)
        or not (false).
    urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnaTrait:
      type: string
      description: "The provided regular expression ensures that the BPNA is composed\
        \ of prefix 'BPNA', 10 digits and two alphanumeric letters."
      pattern: "^BPNA[a-zA-Z0-9]{12}$"
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    urn_samm_io.catenax.item_stock_2.0.0_AllocatedStock:
      description: "This is the quantity of items on stock at a location. A stock\
        \ can either be\n- from a certain supplier and ready to be consumed by a customer\
        \ or\n- from a supplier and ready to be shipped to a certain customer. \n\n\
        In case of stocks \"from a supplier ready to be shipped to a certain customer\"\
        , the stock may refer to an order position of a customer. This stock consists\
        \ only of the good-finished items."
      type: object
      properties:
        quantityOnAllocatedStock:
          description: "This is the quantity of the material on stock. In case of\
            \ stocks \"from a supplier ready to be shipped to a certain customer\"\
            , the stock may refer to an order position of a customer."
          $ref: '#/components/schemas/urn_samm_io.catenax.item_stock_2.0.0_QuantityCharacteristic'
        stockLocationBPNS:
          description: BPNS identifying the site the stock is located at. One stock
            has always one location.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnsTrait'
        isBlocked:
          description: |-
            A set of finished items that are located on the blocked stock area, quarantine area, etc. waiting to be released.

            Example: Stock is in review and not released due to customer complaint regarding a recent batch.
          $ref: '#/components/schemas/urn_samm_io.catenax.item_stock_2.0.0_IsBlockedCharacteristic'
        stockLocationBPNA:
          description: BPNA identifying the address the stock is located at. One stock
            has always one location.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnaTrait'
        lastUpdatedOnDateTime:
          description: Date and time at which the position has been updated by the
            reporting partner's system. Date and time are set according to a timezone.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Timestamp'
      required:
      - quantityOnAllocatedStock
      - stockLocationBPNS
      - isBlocked
      - stockLocationBPNA
      - lastUpdatedOnDateTime
    urn_samm_io.catenax.item_stock_2.0.0_AllocatedStockSet:
      description: Set of allocated stocks that may relate to different stock locations.
        Per location there could be at maximum one blocked and one non blocked stock
        at the same time.
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.item_stock_2.0.0_AllocatedStock'
      uniqueItems: true
    urn_samm_io.catenax.item_stock_2.0.0_Position:
      description: "The Position can be located at several stocks. \nIn case of a\
        \ supplier's stock for a customer, a position may be either anonymous or reference\
        \ a position within a customer order. \nIn case of a customer's stock for\
        \ a supplier, the order position reference MUST NOT be set."
      type: object
      properties:
        orderPositionReference:
          description: The order position reference contains information to identify
            a position within an order.
          $ref: '#/components/schemas/urn_samm_io.catenax.item_stock_2.0.0_OrderPositionReferenceCharacteristic'
        allocatedStocks:
          description: Stocks that have been already allocated to the customer or
            delivered by a specific supplier. An allocated stock always refers to
            a stock location.
          $ref: '#/components/schemas/urn_samm_io.catenax.item_stock_2.0.0_AllocatedStockSet'
      required:
      - allocatedStocks
    urn_samm_io.catenax.item_stock_2.0.0_PositionsSet:
      description: "If any stock is available, then there is at least one position.\
        \ \n\nIn case of a supplier's stock for a customer, the supplier can  differentiate\
        \ the stock according to the order positions of his customer. In this case\
        \ multiple positions can be given. There could also be only one position without\
        \ an OrderPositionReference indicating an anonymous stock which is allocated\
        \ to the customer.\n\nIn case of a customer's stock delivered by a supplier,\
        \ there is exactly one position without order position references."
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.item_stock_2.0.0_Position'
      uniqueItems: true
    urn_samm_io.catenax.shared.uuid_2.0.0_UuidV4Trait:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_samm_io.catenax.item_stock_2.0.0_DirectionCharacteristic:
      type: string
      description: |-
        If a supplier provides stock information to a customer, use "OUTBOUND".
        If a customer provides stock information to a supplier, use "INBOUND".
      enum:
      - INBOUND
      - OUTBOUND
    ItemStock:
      description: This aspect represents the latest quantities of a partner's items
        that are on stock. The stock represent the build-to-order (BTO) stocks already
        available.
      type: object
      properties:
        positions:
          description: "In case of a supplier's stocks for a customer, these stocks\
            \ may reference the order position for that they have been produced. \n\
            In case of a customer's stock delivered by a supplier, there is exactly\
            \ one position.\n\nIn case there is no item on stock, positions MUST be\
            \ empty."
          $ref: '#/components/schemas/urn_samm_io.catenax.item_stock_2.0.0_PositionsSet'
        materialGlobalAssetId:
          description: Identifier used uniquely to identify part type twin.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.uuid_2.0.0_UuidV4Trait'
        direction:
          description: Direction of the stock from data provider perspective.
          $ref: '#/components/schemas/urn_samm_io.catenax.item_stock_2.0.0_DirectionCharacteristic'
      required:
      - positions
      - materialGlobalAssetId
      - direction
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ItemStock:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    ItemStock:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ItemStock'
