---
openapi: 3.0.3
info:
  title: Product Description
  version: v1
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/product-description:
    get:
      tags:
      - ProductDescription
      operationId: getProductDescription
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/ProductDescription'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductDescription'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text:
      type: string
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_EquipmentVariantEntity:
      description: describes different vehicle equipment variants
      type: object
      properties:
        code:
          description: The equipment variants code
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text'
        description:
          description: The equipment variants description
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text'
        group:
          description: The equipment variants group
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text'
      required:
      - code
      - description
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_EquipmentVariantCharacteristic:
      description: "Characteristic to describe a set of equipment codes identified\
        \ by a code, group and description. The list will undergo further standardization\
        \ in upcoming versions."
      type: array
      items:
        $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_EquipmentVariantEntity'
      uniqueItems: true
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_DateTimestamp:
      type: string
      format: date
      description: Characteristic to describe a time stamp
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_CubicCapacity:
      type: number
      description: cubic capacity of the engine
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_EnginePower:
      type: number
      description: engine power expressed in kilowatt
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_EngineCharacteristic:
      description: Characteristic to describe the more specific details of the engine
      type: object
      properties:
        size:
          description: size of the engine in cubic capacity
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_CubicCapacity'
        power:
          description: engine power is the power that an engine can put out
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_EnginePower'
      required:
      - size
      - power
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_Distance:
      type: number
      description: distance in kilometre
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_LifecyclePhases:
      type: string
      description: "temporary definition of lifecycle phases as following in enumeration\
        \ for: as specified by OEM, as built by OEM, as maintained by workshop, as\
        \ recieved by dismantling"
      enum:
      - as maintained by workshop
      - as recieved by dismantling
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_MileageEntity:
      description: definition of mileage attributes
      type: object
      properties:
        mileageDistance:
          description: distance the vehicle has travelled
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_Distance'
        mileagePhase:
          description: Lifecycle phase in which the mileage was measured.
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_LifecyclePhases'
        mileageTimestamp:
          description: timestamp when the mileage was measured
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_DateTimestamp'
      required:
      - mileageDistance
      - mileagePhase
      - mileageTimestamp
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_MileageCharacteristic:
      description: definition of mileage of a vehicle
      type: array
      items:
        $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_MileageEntity'
      uniqueItems: true
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_FuelType:
      type: string
      description: enumeration of possible fuel types of a vehicle
      enum:
      - Unbekannt
      - Diesel
      - Benzin
      - Vielstoff
      - Elektro
      - Flüssiggas
      - Benzin/Flüssiggas
      - Benzin/komp.Erdgas
      - Hybr.Benzin/E
      - Erdgas NG
      - Hybr.Diesel/E
      - Wasserstoff
      - Hybr.Wasserst./E
      - Wasserstoff/Benzin
      - Wasserst./Benzin/E
      - BZ/Wasserstoff
      - BZ/Benzin
      - BZ/Methanol
      - BZ/Ethanol
      - Hybr.Vielstoff/E
      - Methan
      - Benzin/Methan
      - Hybr.Erdgas/E
      - Benzin/Ethanol
      - Hybr.Flüssiggas/E
      - Hybr.B/E ext.aufl.
      - Hybr.D/E ext.aufl.
      - Hybr.LPG/E ext.aufl.
      - Hybr.W/E ext.aufl.
      - Hybr.V/E ext.aufl.
      - Hybr.NG/E ext.aufl.
      - Hybr.Wod.B/Eext.aufl
      - Wasserstoff/NG
      - Hybr.W/NG/E ext.aufl
      - Ethanol
      - Hybr.BZ/W/E
      - Hybr.BZ/W/E ext. aufl.
      - Zweistoff LNG/Diesel
      - Verflüssigtes Erdgas (LNG)
      - Andere
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_Weight:
      type: number
      description: weight of an object
    urn_bamm_io.catenax.vehicle.product_description_1.0.0_KbaVariant:
      type: string
      description: 'Current version of the Enumeration is sub-set of list defined
        from the German Federal Office for motor vehicles. '
      enum:
      - Limousine
      - Schräghecklimousine
      - Kombilimousine
      - Coupé
      - Kabrio-Limousine
      - Cabrio-Limousine
      - Mehrzweckfahrzeug
      - Pkw-Pick-up
      - Van
      - Pick-up
    ProductDescription:
      description: vehicle specific data
      type: object
      properties:
        equipmentVariants:
          description: equipment variants which are build into a specific vehicle
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_EquipmentVariantCharacteristic'
        productionDateGMT:
          description: the production data in GMT time zone
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_DateTimestamp'
        engine:
          description: engine of the vehicle
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_EngineCharacteristic'
        mileage:
          description: mileage of the vehicle
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_MileageCharacteristic'
        fuel:
          description: the fuel type of the vehicle
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_FuelType'
        emptyWeight:
          description: "The empty weight of the vehicle in kg as specified. For motor\
            \ vehicles of class M1 registered up to December 31, 1996: Empty weight\
            \ according to vehicle registration certificate or registration certificate\
            \ Part I minus weight of tank contents at 90 percent filling. For motor\
            \ vehicles of category M1 registered on or after January 1, 1997: Empty\
            \ weight according to vehicle registration certificate or registration\
            \ certificate Part I minus weight of tank contents at 90 percent filling\
            \ and minus weight of driver (75 kg). For motor vehicles of class N1:\
            \ empty weight according to the vehicle registration document or registration\
            \ certificate Part I minus the weight of the tank contents with a 90 percent\
            \ filling and minus the weight of the driver (75 kg)."
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_Weight'
        vehicleModel:
          description: base model / basic vehicle type
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text'
        bodyVariant:
          description: "vehicle variant - Body shapes: Sedan, station wagon, hatchback,\
            \ coupe, convertible, SUV, pickup, Doka (double cab), etc. Also special\
            \ models that may differ from the basic shapes (e.g. BMW M-series, Audi\
            \ S-series, Long version, right-hand drive, special vehicles (armor).\
            \ etc. )."
          $ref: '#/components/schemas/urn_bamm_io.catenax.vehicle.product_description_1.0.0_KbaVariant'
        anonymisedIdentifier:
          description: anonymised IdentifierVehicle. Can be an anonymised number converted
            from a VIN
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text'
      required:
      - equipmentVariants
      - productionDateGMT
      - engine
      - mileage
      - fuel
      - emptyWeight
      - vehicleModel
      - bodyVariant
      - anonymisedIdentifier
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ProductDescription:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    ProductDescription:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductDescription'
