---
openapi: 3.0.3
info:
  title: single level usage as planned
  version: v3
  x-samm-aspect-model-urn: "urn:samm:io.catenax.single_level_usage_as_planned:3.0.0#SingleLevelUsageAsPlanned"
servers:
- url: catenax.io/api/v3
  variables:
    api-version:
      default: v3
paths:
  /{tenant-id}/single-level-usage-as-planned:
    get:
      tags:
      - SingleLevelUsageAsPlanned
      operationId: getSingleLevelUsageAsPlanned
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/SingleLevelUsageAsPlanned"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/SingleLevelUsageAsPlanned"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    QuantityValueCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:3.0.0#QuantityValueCharacteristic"
      description: The quantity value associated with the unit expressed as float.
    ItemUnitEnumeration:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:3.0.0#ItemUnitEnumeration"
      description: Enumeration for common item units.
      enum:
      - unit:piece
      - unit:set
      - unit:pair
      - unit:page
      - unit:cycle
      - unit:kilowattHour
      - unit:gram
      - unit:kilogram
      - unit:tonneMetricTon
      - unit:tonUsOrShortTonUkorus
      - unit:ounceAvoirdupois
      - unit:pound
      - unit:metre
      - unit:centimetre
      - unit:kilometre
      - unit:inch
      - unit:foot
      - unit:yard
      - unit:squareCentimetre
      - unit:squareMetre
      - unit:squareInch
      - unit:squareFoot
      - unit:squareYard
      - unit:cubicCentimetre
      - unit:cubicMetre
      - unit:cubicInch
      - unit:cubicFoot
      - unit:cubicYard
      - unit:litre
      - unit:millilitre
      - unit:hectolitre
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hourUnitOfTime
      - unit:day
    ItemQuantityCharacteristic:
      description: "Characteristic for measurements of an item (mass, count, linear,\
        \ area, volume, misc)."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:3.0.0#ItemQuantityCharacteristic"
      type: object
      properties:
        value:
          description: The quantity value associated with the unit.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:3.0.0#quantityValue"
          $ref: "#/components/schemas/QuantityValueCharacteristic"
        unit:
          description: "The unit of an item. Common units may be related to mass,\
            \ count, linear, area, volume or misc."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:3.0.0#itemUnit"
          $ref: "#/components/schemas/ItemUnitEnumeration"
      required:
      - value
      - unit
    Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Timestamp"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    BpnlTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnlTrait"
      description: "The provided regular expression ensures that the BPNL is composed\
        \ of prefix 'BPNL', 10 digits and two alphanumeric letters."
      pattern: "^BPNL[a-zA-Z0-9]{12}$"
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    ValidityPeriodCharacteristic:
      description: Characteristic  for a validity period defined by an (optional)start
        and an (optional)end timestamp.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#ValidityPeriodCharacteristic"
      type: object
      properties:
        validTo:
          description: End date of validity period.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#validTo"
          $ref: "#/components/schemas/Timestamp"
        validFrom:
          description: Start date and time of validity period.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#validFrom"
          $ref: "#/components/schemas/Timestamp"
    ParentData:
      description: globalAssetId and meta data of the parent part.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.single_level_usage_as_planned:3.0.0#ParentData"
      type: object
      properties:
        quantity:
          description: Quantity of which the child part will be assembled into or
            used in the parent part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.single_level_usage_as_planned:3.0.0#quantity"
          $ref: "#/components/schemas/ItemQuantityCharacteristic"
        createdOn:
          description: Timestamp when the relation between the parent part and the
            child part was created
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#createdOn"
          $ref: "#/components/schemas/Timestamp"
        businessPartner:
          description: The supplier of the given child item.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#businessPartner"
          $ref: "#/components/schemas/BpnlTrait"
        globalAssetId:
          description: The fully anonymous ID in the dataspace of the part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#globalAssetId"
          $ref: "#/components/schemas/UuidV4Trait"
        lastModifiedOn:
          description: Timestamp when the assembly or usage relationship between parent
            part and child part was last modified.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#lastModifiedOn"
          $ref: "#/components/schemas/Timestamp"
        validityPeriod:
          description: |-
            The period of time during which the parent-child relation is valid. This relates to whether a child part can be built into or used in the production of the parent part at a given time.
            If no validity period is given the relation is considered valid at any point in time.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#validityPeriod"
          $ref: "#/components/schemas/ValidityPeriodCharacteristic"
      required:
      - quantity
      - createdOn
      - businessPartner
      - globalAssetId
    SetOfParentItemsCharacteristic:
      description: Set of parent items the given child object will be assembled into
        or used (one structural level up).
      x-samm-aspect-model-urn: "urn:samm:io.catenax.single_level_usage_as_planned:3.0.0#SetOfParentItemsCharacteristic"
      type: array
      items:
        $ref: "#/components/schemas/ParentData"
      uniqueItems: true
    ListOfCustomers:
      description: A list of customers and their related parent items.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#ListOfCustomers"
      type: array
      items:
        type: string
        x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnlTrait"
        description: "The provided regular expression ensures that the BPNL is composed\
          \ of prefix 'BPNL', 10 digits and two alphanumeric letters."
        pattern: "^BPNL[a-zA-Z0-9]{12}$"
    SingleLevelUsageAsPlanned:
      description: |-
        The aspect provides the information in which parent part(s)/product(s)the given item is to be assembled into or used. This could be a 1:1 relationship in terms of a e.g. a brake component or 1:n for e.g. coatings. The given item as well as the parent item must refer to an object from the as-planned lifecycle phase.
        If multiple versions of parent parts exist that the child part can be assembled into or used, all versions of the parent part are included in the usage list.
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.single_level_usage_as_planned:3.0.0#SingleLevelUsageAsPlanned"
      properties:
        parentItems:
          description: "Set of parent parts, in which the given child object will\
            \ be assembled into or used (one structural level up)."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.single_level_usage_as_planned:3.0.0#parentItems"
          $ref: "#/components/schemas/SetOfParentItemsCharacteristic"
        customers:
          description: |-
            A list of all customers of this item. If the parent items in which this item is assembled into are known, they should be listed as well.

            For serialized items the list should contain only one customer with one parent item.
            As different subsets of a batch might be sold to different customers this is a list.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#customers"
          $ref: "#/components/schemas/ListOfCustomers"
        globalAssetId:
          description: The fully anonymous ID in the dataspace of the part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#globalAssetId"
          $ref: "#/components/schemas/UuidV4Trait"
      required:
      - parentItems
      - customers
      - globalAssetId
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    SingleLevelUsageAsPlanned:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    SingleLevelUsageAsPlanned:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SingleLevelUsageAsPlanned"
      required: true
