---
openapi: 3.0.3
info:
  title: Traction Battery Code
  version: v2
  x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#TractionBatteryCode"
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/traction-battery-code:
    get:
      tags:
      - TractionBatteryCode
      operationId: getTractionBatteryCode
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/TractionBatteryCode"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/TractionBatteryCode"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    TractionBatteryCodeTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#TractionBatteryCodeTrait"
      description: The traction battery code as required by the National Standard
        of the People's Republic of China according to GB/T 34014-2017 published by
        the Standardization Administration of China (SAC). It can have a length of
        either 24 or 18 characters.
      pattern: "(^[A-Z0-9]{3}[PMC]{1}[A-GZ]{1}[A-Z0-9]{2}[A-Z0-9]{7}[1-9A-GH-NPR-Y]{1}[1-9A-C]{1}[0-9A-GH-NPR-Y]{1}[0-9]{7}$)|(^[A-Z0-9]{3}[PMC]{1}[A-GZ]{1}[A-Z0-9]{2}[1-9A-GH-NPR-Y]{1}[1-9A-C]{1}[0-9A-GH-NPR-Y]{1}[0-9]{7}[R]{1}[PMC]{1}$)"
    ComponentTypeCharacterstic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#ComponentTypeCharacterstic"
      enum:
      - pack
      - module
      - cell
    TractionBatteryComponent:
      description: A battery component like a cell or a module.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#TractionBatteryComponent"
      type: object
      properties:
        tractionBatteryCode:
          description: "Traction Battery Code identifying a single traction battery\
            \ component like a pack, module or cell. "
          x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#tractionBatteryCode"
          $ref: "#/components/schemas/TractionBatteryCodeTrait"
        subcomponents:
          description: "Subcomponents of the component, if applicable. The relationship\
            \ between traction battery codes are as follows:\n\nIf this traction battery\
            \ code is given for a cell subcomponents are not required. \nIf this traction\
            \ battery code is given for a battery module a list of cells are required\
            \ to be registered as subcomponents.\nIf this traction battery code is\
            \ given for a battery pack a list of modules are required to be registered\
            \ as subcomponents (containing each a list of cell subcomponents respectively)."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#subcomponents"
          $ref: "#/components/schemas/ComponentList"
        productType:
          description: "The type of the battery component, e.g. a pack, a module or\
            \ a cell."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#productType"
          $ref: "#/components/schemas/ComponentTypeCharacterstic"
      required:
      - tractionBatteryCode
      - productType
    ComponentList:
      description: A list of battery components like modules or cells.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#ComponentList"
      type: array
      items:
        $ref: "#/components/schemas/TractionBatteryComponent"
    TractionBatteryCode:
      description: "The traction battery code is an identification code for any automotive\
        \ traction battery, ultracapacitor and other reachargeble energy storage device.\
        \ It allows to carry information as required by the National Standard of the\
        \ People's Republic of China according to GB/T 34014-2017 published by the\
        \ Standardization Administration of China (SAC)."
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#TractionBatteryCode"
      properties:
        tractionBatteryCode:
          description: "Traction Battery Code identifying a single traction battery\
            \ component like a pack, module or cell. "
          x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#tractionBatteryCode"
          $ref: "#/components/schemas/TractionBatteryCodeTrait"
        subcomponents:
          description: "Subcomponents of the component, if applicable. The relationship\
            \ between traction battery codes are as follows:\n\nIf this traction battery\
            \ code is given for a cell subcomponents are not required. \nIf this traction\
            \ battery code is given for a battery module a list of cells are required\
            \ to be registered as subcomponents.\nIf this traction battery code is\
            \ given for a battery pack a list of modules are required to be registered\
            \ as subcomponents (containing each a list of cell subcomponents respectively)."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#subcomponents"
          $ref: "#/components/schemas/ComponentList"
        productType:
          description: "The type of the battery component, e.g. a pack, a module or\
            \ a cell."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.traction_battery_code:2.0.0#productType"
          $ref: "#/components/schemas/ComponentTypeCharacterstic"
      required:
      - tractionBatteryCode
      - productType
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    TractionBatteryCode:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    TractionBatteryCode:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TractionBatteryCode"
      required: true
