---
openapi: 3.0.3
info:
  title: Marketplace Offer
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#MarketplaceOffer"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/marketplace-offer:
    get:
      tags:
      - MarketplaceOffer
      operationId: getMarketplaceOffer
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/MarketplaceOffer"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/MarketplaceOffer"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    Text:
      type: string
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text"
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    QuantityCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#QuantityCharacteristic"
      description: Describes a quantity as decimal number.
    ConditionCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#ConditionCharacteristic"
      description: Condition of the article as enumeration.
      enum:
      - New
      - Used
      - Refurbished
      - Other
    LongitudeCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#LongitudeCharacteristic"
    LatitudeCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#LatitudeCharacteristic"
    GeographicalCoordinates:
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#GeographicalCoordinates"
      type: object
      properties:
        longitude:
          description: The longitude of the 2D sphere coordinates.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#longitude"
          $ref: "#/components/schemas/LongitudeCharacteristic"
        latitude:
          description: The latitude of the 2D sphere coordinates.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#latitude"
          $ref: "#/components/schemas/LatitudeCharacteristic"
      required:
      - longitude
      - latitude
    Value:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#Value"
    Price:
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#Price"
      type: object
      properties:
        value:
          description: The absolute value of the price
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#value"
          $ref: "#/components/schemas/Value"
        currency:
          description: The currency of the price.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#currency"
          $ref: "#/components/schemas/Text"
      required:
      - value
      - currency
    LocationCharacteristic:
      type: string
      format: uri
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#LocationCharacteristic"
      description: Location with an URI.
    ImageFile:
      description: Image of the object.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#ImageFile"
      type: object
      properties:
        name:
          description: Name or title of the object.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#name"
          $ref: "#/components/schemas/Text"
        location:
          description: Location of the object.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#location"
          $ref: "#/components/schemas/LocationCharacteristic"
      required:
      - name
      - location
    AttachmentEntity:
      description: attachment for the article.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#AttachmentEntity"
      type: object
      properties:
        name:
          description: Name or title of the object.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#name"
          $ref: "#/components/schemas/Text"
        location:
          description: Location of the object.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#location"
          $ref: "#/components/schemas/LocationCharacteristic"
      required:
      - name
      - location
    Attachment:
      description: Links the referenced attachment.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#Attachment"
      type: array
      items:
        $ref: "#/components/schemas/AttachmentEntity"
      uniqueItems: true
    BundleOffer:
      type: boolean
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#BundleOffer"
    MainCategory:
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#MainCategory"
      type: array
      items:
        type: string
    SubCategory:
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#SubCategory"
      type: array
      items:
        type: string
    CategoryCharacteristic:
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#CategoryCharacteristic"
      type: object
      properties:
        mainCategory:
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#mainCategory"
          $ref: "#/components/schemas/MainCategory"
        subCategory:
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#subCategory"
          $ref: "#/components/schemas/SubCategory"
      required:
      - mainCategory
      - subCategory
      description: The category of the listing within the marketplace.
    ProductLinkCharacteristic:
      type: string
      format: uri
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#ProductLinkCharacteristic"
    TechnicalSpecificationEntity:
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#TechnicalSpecificationEntity"
      type: object
      properties:
        key:
          description: The key of the key value pair
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#key"
          $ref: "#/components/schemas/Text"
        technicalValue:
          description: The value of the key value pair.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#technicalValue"
          $ref: "#/components/schemas/Text"
      required:
      - key
      - technicalValue
    TechnicalSpecification:
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#TechnicalSpecification"
      type: array
      items:
        $ref: "#/components/schemas/TechnicalSpecificationEntity"
      uniqueItems: true
    ProductCharacteristic:
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#ProductCharacteristic"
      type: object
      properties:
        productDescription:
          description: The description of the product on the marketplace.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#productDescription"
          $ref: "#/components/schemas/Text"
        brand:
          description: The brandname of the offered product.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#brand"
          $ref: "#/components/schemas/Text"
        category:
          description: Category within the marketplace for classification of listings.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#category"
          $ref: "#/components/schemas/CategoryCharacteristic"
        originalManufacturer:
          description: The original manufacturer of a product.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#originalManufacturer"
          $ref: "#/components/schemas/Text"
        manufacturerPartNumber:
          description: The unique identifier of the product from the manufacturer.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#manufacturerPartNumber"
          $ref: "#/components/schemas/Text"
        productLink:
          description: A link to either the product on the original marketplace/webshop
            or a link to the product specifications document.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#productLink"
          $ref: "#/components/schemas/ProductLinkCharacteristic"
        oeNumber:
          description: The original equipment number.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#oeNumber"
          $ref: "#/components/schemas/Text"
        technicalSpecification:
          description: Further technical specifications.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#technicalSpecification"
          $ref: "#/components/schemas/TechnicalSpecification"
      required:
      - productDescription
      - brand
      - category
      - technicalSpecification
    Boolean:
      type: boolean
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#Boolean"
    AvailabilityDateCharacteristic:
      type: string
      format: date
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#AvailabilityDateCharacteristic"
      description: The availability date when the product is in stock.
    MileageCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#MileageCharacteristic"
      description: The value describing the mileage of the item.
    CatenaXIdTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#CatenaXIdTrait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens)."
      pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    MarketplaceOffer:
      description: Description of all needed information to place a market place offer
        on the marketplace.
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#MarketplaceOffer"
      properties:
        sku:
          description: Stock Keeping Unit is an unique identifier of the dealer providing
            the product
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#sku"
          $ref: "#/components/schemas/Text"
        quantity:
          description: The available quantity of an offered product.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#quantity"
          $ref: "#/components/schemas/QuantityCharacteristic"
        unitOfMeasure:
          description: The unit of measure (related to quantity).
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#unitOfMeasure"
          $ref: "#/components/schemas/Text"
        condition:
          description: The condition of the offered product.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#condition"
          $ref: "#/components/schemas/ConditionCharacteristic"
        pickupLocation:
          description: The pickup location for the offered item.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#pickupLocation"
          $ref: "#/components/schemas/GeographicalCoordinates"
        incoterms:
          description: The incoterms.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#incoterms"
          $ref: "#/components/schemas/Text"
        price:
          description: The price of the product.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#price"
          $ref: "#/components/schemas/Price"
        image:
          description: Images of the product.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#image"
          $ref: "#/components/schemas/ImageFile"
        attachment:
          description: Attachments related to the product.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#attachment"
          $ref: "#/components/schemas/Attachment"
        bundleOffer:
          description: If this is a single product or a lot of products (group) not
            being necessarly of the same part number.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#bundleOffer"
          $ref: "#/components/schemas/BundleOffer"
        marketplaceProduct:
          description: The description of the product within the marketplace that
            might differ from the digital twin.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#marketplaceProduct"
          $ref: "#/components/schemas/ProductCharacteristic"
        missingParts:
          description: "Completeness of the product, e.g. missing parts are not acceptable."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#missingParts"
          $ref: "#/components/schemas/Boolean"
        dismantled:
          description: Information on whether the product has been dismantled.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#dismantled"
          $ref: "#/components/schemas/Boolean"
        mechanicalDamage:
          description: "Information on mechanical damage to the part, e.g. two broken\
            \ ribs or part deformation indicate mechanical damage."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#mechanicalDamage"
          $ref: "#/components/schemas/Boolean"
        corroded:
          description: Information on whether the product has corrosion.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#corroded"
          $ref: "#/components/schemas/Boolean"
        discolored:
          description: Information on whether the product has been discoloured.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#discolored"
          $ref: "#/components/schemas/Boolean"
        availabilityDate:
          description: The availability date when the product is in stock.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#availabilityDate"
          $ref: "#/components/schemas/AvailabilityDateCharacteristic"
        mileage:
          description: The mileage the item was ins use.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#mileage"
          $ref: "#/components/schemas/MileageCharacteristic"
        burned:
          description: Information on whether the product has been fired and suffered
            damage from heat.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#burned"
          $ref: "#/components/schemas/Boolean"
        catenaXId:
          description: "The fully anonymous Catena-X ID of the offer, valid for the\
            \ Catena-X dataspace."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.market_place_offer:1.4.0#catenaXId"
          $ref: "#/components/schemas/CatenaXIdTrait"
      required:
      - quantity
      - unitOfMeasure
      - pickupLocation
      - price
      - bundleOffer
      - marketplaceProduct
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    MarketplaceOffer:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    MarketplaceOffer:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MarketplaceOffer"
      required: true
