---
openapi: 3.0.3
info:
  title: Week-Based Capacity Group
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#WeekBasedCapacityGroup"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/week-based-capacity-group:
    get:
      tags:
      - WeekBasedCapacityGroup
      operationId: getWeekBasedCapacityGroup
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/WeekBasedCapacityGroup"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/WeekBasedCapacityGroup"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    UUIDv4IdTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#UUIDv4IdTrait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens)."
      pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    CapacityGroupName:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#CapacityGroupName"
      description: "The name of a capacity group, used to distinguish it from other\
        \ capacity groups."
    BPNSSetTrait:
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two uppercase letters."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#BPNSSetTrait"
      type: array
      items:
        type: string
      uniqueItems: true
      pattern: "^BPNS[0-9]{8}[a-zA-Z0-9]{4}$"
    BPNLTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#BPNLTrait"
      description: "The provided regular expression ensures that the BPNL is composed\
        \ of prefix 'BPNL', 10 digits and two uppercase letters."
      pattern: "^BPNL[0-9]{8}[a-zA-Z0-9]{4}$"
    UnitOfMeasure:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#UnitOfMeasure"
      description: The Enumeration lists a selection of allowed units of measure referenced
        by their official code according to Codes for Units of Measure Used in International
        Trade
      enum:
      - GRM
      - KGM
      - TNE
      - STN
      - ONZ
      - LBR
      - CMT
      - MTR
      - KTM
      - INH
      - FOT
      - YRD
      - CMK
      - MTK
      - INK
      - FTK
      - YDK
      - CMQ
      - MTQ
      - INQ
      - FTQ
      - YDQ
      - MLT
      - LTR
      - HLT
      - H87
      - SET
      - PR
      - ZP
      - KWH
      - ""
    MaterialNumber:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#MaterialNumber"
      description: "The material number is a multi-character string, usually assigned\
        \ by an ERP system."
    BPNSTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#BPNSTrait"
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two uppercase letters."
      pattern: "^BPNS[0-9]{8}[a-zA-Z0-9]{4}$"
    DemandCategoryDefault:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - '0001'
      required:
      - demandCategoryCode
    DemandCategoryAfterSales:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - A1S1
      required:
      - demandCategoryCode
    DemandCategorySeries:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - SR99
      required:
      - demandCategoryCode
    DemandCategoryPhaseInPeriod:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - PI01
      required:
      - demandCategoryCode
    DemandCategorySingleOrder:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - OS01
      required:
      - demandCategoryCode
    DemandCategorySmallSeries:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - OI01
      required:
      - demandCategoryCode
    DemandCategoryExtraordinaryDemand:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - ED01
      required:
      - demandCategoryCode
    DemandCategoryPhaseOutPeriod:
      type: object
      properties:
        demandCategoryCode:
          description: The code identifying a demand category.
          type: string
          enum:
          - PO01
      required:
      - demandCategoryCode
    DemandCategory:
      description: The classification of demands used to prioritize or allocate capacities.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#DemandCategory"
      type: object
      oneOf:
      - $ref: "#/components/schemas/DemandCategoryDefault"
      - $ref: "#/components/schemas/DemandCategoryAfterSales"
      - $ref: "#/components/schemas/DemandCategorySeries"
      - $ref: "#/components/schemas/DemandCategoryPhaseInPeriod"
      - $ref: "#/components/schemas/DemandCategorySingleOrder"
      - $ref: "#/components/schemas/DemandCategorySmallSeries"
      - $ref: "#/components/schemas/DemandCategoryExtraordinaryDemand"
      - $ref: "#/components/schemas/DemandCategoryPhaseOutPeriod"
    LinkedDemandSeries:
      description: Encapsulates information used to reference a specific demand series.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#LinkedDemandSeries"
      type: object
      properties:
        materialNumberCustomer:
          description: Material identifier as assigned by customer. This material
            number identifies the material (as planned) in the customer's database.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#materialNumberCustomer"
          $ref: "#/components/schemas/MaterialNumber"
        materialNumberSupplier:
          description: "Material identifier as assigned by supplier. This material\
            \ number identifies the material (as planned) in the supplier's database.\
            \ Used as informational field only, not for assigning demand series to\
            \ capacity groups."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#materialNumberSupplier"
          $ref: "#/components/schemas/MaterialNumber"
        customerLocation:
          description: The BPNS number of the site at which the customer needs the
            specified material for the referenced demand series.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#customerLocation"
          $ref: "#/components/schemas/BPNSTrait"
        demandCategory:
          description: Type of demand of the referenced demand series.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#demandCategory"
          $ref: "#/components/schemas/DemandCategory"
      required:
      - materialNumberCustomer
      - customerLocation
      - demandCategory
    LinkedDemandSeriesSet:
      description: A set of demand series assigned to a certain capacity group.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#LinkedDemandSeriesSet"
      type: array
      items:
        $ref: "#/components/schemas/LinkedDemandSeries"
      uniqueItems: true
    CalendarWeek:
      type: string
      format: date
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#CalendarWeek"
      description: An ISO calendar week in which a given capacity will be provided.
        Must be given as date of the Monday in the week.
    QuantityTrait:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#QuantityTrait"
      description: Constraint to ensure a non-negative value for quantities.
      maximum: 999999999999999999.999
      exclusiveMaximum: false
      minimum: 0
      exclusiveMinimum: false
    Capacity:
      description: "A supplier's realistically planned output per calendar week and\
        \ material for a specific customer in a specific unit of measure, considering\
        \ all positive or negative impacts on this capacity."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#Capacity"
      type: object
      properties:
        calendarWeek:
          description: ISO Calendar Week of the given time series entry. Must be given
            as date of the Monday in the week.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#calendarWeek"
          $ref: "#/components/schemas/CalendarWeek"
        actualCapacity:
          description: "The actual capacity is the realistically planned output per\
            \ calendar week and material for a specific customer in a specific unit\
            \ of measure, considering all positive or negative impacts on this capacity."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#actualCapacity"
          $ref: "#/components/schemas/QuantityTrait"
        maximumCapacity:
          description: "The supplier maximum capacity is the maximal available output\
            \ per calendar week and material for a specific customer in a specific\
            \ unit of measure. The maximum capacity thereby restricts the flexible\
            \ capacity, as the flexible capacity is obtained from the difference of\
            \ a suppliers maximum capacity minus actual capacity."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#maximumCapacity"
          $ref: "#/components/schemas/QuantityTrait"
      required:
      - calendarWeek
      - actualCapacity
      - maximumCapacity
    CapacityTimeSeries:
      description: The weekly actual and maximum capacities in a given time period.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#CapacityTimeSeries"
      type: array
      items:
        $ref: "#/components/schemas/Capacity"
      uniqueItems: true
    Timestamp:
      type: string
      format: date-time
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#Timestamp"
      description: Point in time.
    WeekBasedCapacityGroup:
      description: An entity made up of the weekly actual and maximum capacities for
        a specific customer in a given time period. A capacity group is used to compare
        demand and capacity data for one or several similar bundled materials in a
        defined unit of measure.
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#WeekBasedCapacityGroup"
      properties:
        capacityGroupId:
          description: The Capacity Group ID uniquely identifies the capacity group
            within the business relationship between a supplier and its customer.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#capacityGroupId"
          $ref: "#/components/schemas/UUIDv4IdTrait"
        name:
          description: Name of the capacity group.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#name"
          $ref: "#/components/schemas/CapacityGroupName"
        supplierLocations:
          description: Set of BPNS indicating the supplier sites that will be fulfilling
            the demands associated with this capacity group.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#supplierLocations"
          $ref: "#/components/schemas/BPNSSetTrait"
        customer:
          description: The Business Partner Number (BPNL) of the party requesting
            materials from a supplier.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#customer"
          $ref: "#/components/schemas/BPNLTrait"
        supplier:
          description: The Business Partner Number (BPNL) of the party providing materials
            to a customer.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#supplier"
          $ref: "#/components/schemas/BPNLTrait"
        unitOfMeasure:
          description: Unit of measurement for capacity quantities.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#unitOfMeasure"
          $ref: "#/components/schemas/UnitOfMeasure"
        linkedDemandSeries:
          description: Set of demand series assigned to this capacity group.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#linkedDemandSeries"
          $ref: "#/components/schemas/LinkedDemandSeriesSet"
        capacities:
          description: A time series with week-based granularity along a given time
            period containing the capacity values.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#capacities"
          $ref: "#/components/schemas/CapacityTimeSeries"
        changedAt:
          description: "Point in time when the content (any property according to\
            \ the data model) of the capacity group was changed, at the supplier,\
            \ either by a human user or an automated process."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.week_based_capacity_group:1.0.1#changedAt"
          $ref: "#/components/schemas/Timestamp"
      required:
      - capacityGroupId
      - name
      - customer
      - supplier
      - unitOfMeasure
      - linkedDemandSeries
      - capacities
      - changedAt
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    WeekBasedCapacityGroup:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    WeekBasedCapacityGroup:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WeekBasedCapacityGroup"
      required: true
