---
openapi: 3.0.3
info:
  title: QualityTasks
  version: v2
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/quality-task:
    get:
      tags:
      - QualityTask
      operationId: getQualityTask
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/QualityTask'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/QualityTask'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_samm_io.catenax.quality_task_2.0.0_RecordStatusEnumeration:
      type: string
      description: Defining the enumeration for the record status
      enum:
      - new
      - update
      - delete
      - same
    urn_samm_io.catenax.quality_task_2.0.0_Date:
      type: string
      format: date
      description: Describes a Property which contains the date and time with an optional
        timezone.
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text:
      type: string
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    urn_samm_io.catenax.quality_task_2.0.0_DataDeletionEnumeration:
      type: string
      description: Enumeration of possible data deletions entries.
      enum:
      - delete-data-after-closing
      - no-deletion-after-closing
      - delete-data-after-closing
      - no-deletion-after-closing
    urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_samm_io.catenax.quality_task_2.0.0_StatusCharacteristic:
      type: string
      description: Enumeration of the different status values
      enum:
      - new
      - in progress
      - completed
      - closed
      - new
      - in progress
      - completed
      - closed
    urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait:
      type: string
      description: "The provided regular expression ensures that the BPNL is composed\
        \ of prefix 'BPNL', 10 digits and two uppercase letters."
      pattern: "^BPNL[0-9]{8}[a-zA-Z0-9]{4}$"
    urn_samm_io.catenax.shared.contact_information_3.0.0_EMailTrait:
      type: string
      description: Regular expression for mail address as defined in W3C.
      pattern: "^[a-zA-Z0-9.!#$%&?*+\\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$"
    urn_samm_io.catenax.quality_task_2.0.0_Company:
      description: One company involved in this qTask
      type: object
      properties:
        cxBusinessPartnerNumber:
          description: The Catena-X business partner number for this company.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnlTrait'
        name:
          description: Name of the company
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        email:
          description: An email address.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.contact_information_3.0.0_EMailTrait'
      required:
      - cxBusinessPartnerNumber
    urn_samm_io.catenax.quality_task_2.0.0_ListOfCompanies:
      description: A list of all companies involved in this qTask
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_Company'
    urn_samm_io.catenax.quality_task_2.0.0_SingleQualityTask:
      description: "A quality task (qTask) defines why data is exchanged between 2\
        \ or more companies and what insights should be generated out of the transferred\
        \ data. In addition there is a flag, what happens with the transferred data\
        \ when this qTask is closed"
      type: object
      properties:
        recordStatus:
          description: "The record operation enumeration can be used to realize delta\
            \ update concept.\nDelta update concept means:\n- You transfer an initial\
            \ load of data\n- After the first week only the delta to the initial load\
            \ is transferred\n\n\nThe record status describes whether this record\
            \ is:\n- new=>This record is transferred the first time\n- update=> Some\
            \ properties of this record have changed compared to a previous transfer\n\
            - delete=> This record was transferred in the initial load or in a previous\
            \ delta update, but is not \nused any more and therefore it should be\
            \ deleted on data consumer side\n- same=> This record was transferred\
            \ in the initial load or in a previous delta update"
          $ref: '#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_RecordStatusEnumeration'
        creationDate:
          description: Timestamp when this qTask was created
          $ref: '#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_Date'
        component:
          description: The component that should be investigated in this qTask.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        dataDeletion:
          description: What should be done with the data after this qTask is closed
          $ref: '#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_DataDeletionEnumeration'
        description:
          description: Description what should be done in this qTask
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        qualityTaskId:
          description: A unique quality task identifier within the Catena-X dataspace.
            The unique id uses the Catena-X UUID trait.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait'
        status:
          description: Status of this quality task
          $ref: '#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_StatusCharacteristic'
        title:
          description: Working title for this qTask
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        listOfCompanies:
          description: A list of companies involved in this quality task
          $ref: '#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_ListOfCompanies'
      required:
      - qualityTaskId
    urn_samm_io.catenax.quality_task_2.0.0_QualityTaskList:
      description: The list of quality tasks itself.
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_SingleQualityTask'
    urn_samm_io.catenax.quality_task_2.0.0_MetaCharacteristic:
      description: Characteristic for the meta information.
      type: object
      properties:
        selectionCriteria:
          description: Describes the selection criteria a Catena-X data provider has
            applied to create this data set.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        selectionStart:
          description: Describes the starting point for providing records in this
            data set.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
        selectionEnd:
          description: Describes the end point for providing records in this data
            set.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text'
      required:
      - selectionCriteria
    QualityTask:
      description: 'A list of quality tasks (qTask). '
      type: object
      properties:
        listOfQualityTasks:
          description: Property for the list of quality tasks.
          $ref: '#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_QualityTaskList'
        metaInformation:
          description: 'This meta information is valid for all entries in this data
            set. The meta information is used to tell the data consumer which selection
            criteria were applied by the data provider. '
          $ref: '#/components/schemas/urn_samm_io.catenax.quality_task_2.0.0_MetaCharacteristic'
      required:
      - listOfQualityTasks
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    QualityTask:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    QualityTask:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/QualityTask'
