---
openapi: 3.0.3
info:
  title: Customs Information
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#CustomsInformation"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/customs-information:
    get:
      tags:
      - CustomsInformation
      operationId: getCustomsInformation
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/CustomsInformation"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/CustomsInformation"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    TradeRelationTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#TradeRelationTrait"
      description: Regular expression to restrict the trade relation based on the
        ISO 3166.
      pattern: "^([A-Z]{2})-([A-Z]{2})$"
    CommercialCountryOfOriginTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#CommercialCountryOfOriginTrait"
      description: Regular expression to restrict a country code or federal state
        based on the ISO 3166.
      pattern: "^[A-Z]{2}$"
    FederalStateTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#FederalStateTrait"
      description: Regular expression to restrict a country code or federal state
        based on the ISO 3166.
      enum:
      - BW
      - BY
      - BW
      - BB
      - HB
      - HH
      - HE
      - MV
      - NI
      - NW
      - RP
      - SL
      - SN
      - ST
      - SH
      - TH
      - 99
      pattern: "^[A-Z]{2}$"
    PreferredStatusEnumeration:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#PreferredStatusEnumeration"
      description: Characteristic of the preferred status property defined as an enumeration.
      enum:
      - Y-Certified
      - N-NotCertified
      - NoLongerUsed
      - NoLongerSupplied
    ValueCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#ValueCharacteristic"
      description: 'Characteristic of the value property defined as double. '
    CurrencyTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#CurrencyTrait"
      description: Regular expression to restrict the currency based on the ISO 4217.
      pattern: "^[A-Z]{3}$"
    TracedWorthCharacteristic:
      description: Characteristic of the traced worth property.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#TracedWorthCharacteristic"
      type: object
      properties:
        value:
          description: Value of traced Value  depending on the currency.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#value"
          $ref: "#/components/schemas/ValueCharacteristic"
        currency:
          description: This is the currency of the traced value.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#currency"
          $ref: "#/components/schemas/CurrencyTrait"
      required:
      - value
      - currency
    ContactPersionCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#ContactPersionCharacteristic"
      description: Characteristic of the contact person defined as String.
    JobTitleCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#JobTitleCharacteristic"
      description: Characteristic of the job title defined as String.
    EmailCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#EmailCharacteristic"
      description: Characteristic of the e-mail defined as String.
    PhoneNumberCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#PhoneNumberCharacteristic"
      description: Characteristic of the phone number defined as String.
    ContactInformationCharacteristic:
      description: Characteristic of the contact information property.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#ContactInformationCharacteristic"
      type: object
      properties:
        contactPerson:
          description: Name of the person responsible for the customs information
            provided.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#contactPerson"
          $ref: "#/components/schemas/ContactPersionCharacteristic"
        jobTitle:
          description: Jobtitle of the responsible for the customs information provided.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#jobTitle"
          $ref: "#/components/schemas/JobTitleCharacteristic"
        email:
          description: E-Mail of the responsible for the customs information provided.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#email"
          $ref: "#/components/schemas/EmailCharacteristic"
        phoneNumber:
          description: Phone number of the responsible for the customs information
            provided.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#phoneNumber"
          $ref: "#/components/schemas/PhoneNumberCharacteristic"
      required:
      - contactPerson
      - jobTitle
      - email
      - phoneNumber
    LongitudeAndLatitudeCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#LongitudeAndLatitudeCharacteristic"
      description: 'Characteristic of the geological position for the manufacturing
        origin defined as double. '
    OriginOfManufacturingCharacteristic:
      description: Characteristic of the origin of manufacturing.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#OriginOfManufacturingCharacteristic"
      type: object
      properties:
        longitude:
          description: Longitude of the manufacturing place.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#longitude"
          $ref: "#/components/schemas/LongitudeAndLatitudeCharacteristic"
        latitude:
          description: Latiitude of the manufacturing place.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#latitude"
          $ref: "#/components/schemas/LongitudeAndLatitudeCharacteristic"
      required:
      - longitude
      - latitude
    OriginInformationCharacteristic:
      description: Characteristic of the origin information property.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#OriginInformationCharacteristic"
      type: object
      properties:
        tradeRelation:
          description: The trade relation (preferential agreement)for which origin
            information has been provided.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#tradeRelation"
          $ref: "#/components/schemas/TradeRelationTrait"
        commercialCountryOfOrigin:
          description: "The term \"Commercial Country Of Origin\" specifically refers\
            \ to the country where the goods were originally produced, manufactured\
            \ or significantly transformed"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#commercialCountryOfOrigin"
          $ref: "#/components/schemas/CommercialCountryOfOriginTrait"
        federalState:
          description: German federal state in which the part was manufactured.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#federalState"
          $ref: "#/components/schemas/FederalStateTrait"
        preferredStatus:
          description: This is the preference status of the part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#preferredStatus"
          $ref: "#/components/schemas/PreferredStatusEnumeration"
        tracedWorth:
          description: Material value of the part in a currency unit.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#tracedWorth"
          $ref: "#/components/schemas/TracedWorthCharacteristic"
        contactInformation:
          description: Contact information for the responsible.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#contactInformation"
          $ref: "#/components/schemas/ContactInformationCharacteristic"
        originOfManufacturing:
          description: Information of the Manufacturing place.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#originOfManufacturing"
          $ref: "#/components/schemas/OriginOfManufacturingCharacteristic"
      required:
      - tradeRelation
      - preferredStatus
      - contactInformation
    DateCharacteristic:
      type: string
      format: date
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#DateCharacteristic"
      description: Characteristic to define the date for one or more properties.
    TypeEnumaration:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#TypeEnumaration"
      description: Characteristic of the type property defined as an Enumeration.
      enum:
      - AnnualRequest
      - InitialRequest
      - Reminder-1
      - Reminder-2
      - Reminder-3
      - ReVocation
    StatusEnumeration:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#StatusEnumeration"
      description: Characteristic of the status property defined as an Enumeration.
      enum:
      - Not-Completed
      - Committed
    CustomsInformationEntity:
      description: Entity of the customs information.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#CustomsInformationEntity"
      type: object
      properties:
        originInformation:
          description: "OriginInformation contains all the information required to\
            \ determine that the part is eligible for preferential treatment, i.e.\
            \ the determination of preferential origin."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#originInformation"
          $ref: "#/components/schemas/OriginInformationCharacteristic"
        confirmationDate:
          description: Confirmation Date is the date of issue of a long-term supplier's
            declaration.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#confirmationDate"
          $ref: "#/components/schemas/DateCharacteristic"
        validFrom:
          description: Valid From is the date from which a long-term supplier declaration
            is valid. This date can be in the future.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#validFrom"
          $ref: "#/components/schemas/DateCharacteristic"
        type:
          description: Type is the reason for submitting a long-term supplier's declaration.
            This may be due to a recurring annual enquiry by the customer or at the
            start of a supply relationship.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#type"
          $ref: "#/components/schemas/TypeEnumaration"
        status:
          description: Status represents the stage of a long-term supplier's declaration.
            Committed indicates to the data recipient that all data has been provided
            correctly.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#status"
          $ref: "#/components/schemas/StatusEnumeration"
      required:
      - originInformation
      - confirmationDate
      - validFrom
      - type
      - status
    CustomsInformationSet:
      description: Characteristic of the customs information property defined as a
        Set.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#CustomsInformationSet"
      type: array
      items:
        $ref: "#/components/schemas/CustomsInformationEntity"
      uniqueItems: true
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    CustomsInformation:
      description: |-
        To carry out a preference calculation, customs-specific master data is required for all installed parts within a product. For this purpose, the manufacturer of the product requests this information from the relevant suppliers for all purchased parts (part numbers)and uses it for the preference calculation.

        The exchange takes place peer-to-peer from one value-added participant across the two tier levels.
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#CustomsInformation"
      properties:
        customsInformation:
          description: "CustomsInformation contains all customs-related information\
            \ for a long-term supplier's declaration for a part. Long-term supplier's\
            \ declarations (LLE)are one-off declarations that are valid for deliveries\
            \ over a longer period of time, provided that the delivered goods are\
            \ expected to have the same origin status."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#customsInformation"
          $ref: "#/components/schemas/CustomsInformationSet"
        catenaXId:
          description: "The fully anonymous Catena-X ID of the corresponding part,\
            \ valid for the Catena-X dataspace."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.customs_information:1.0.0#catenaXId"
          $ref: "#/components/schemas/UuidV4Trait"
      required:
      - customsInformation
      - catenaXId
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    CustomsInformation:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    CustomsInformation:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CustomsInformation"
      required: true
