---
openapi: 3.0.3
info:
  title: Parts Analysis
  version: v3
  x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#PartsAnalyses"
servers:
- url: catenax.io/api/v3
  variables:
    api-version:
      default: v3
paths:
  /{tenant-id}/parts-analyses:
    get:
      tags:
      - PartsAnalyses
      operationId: getPartsAnalyses
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/PartsAnalyses"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/PartsAnalyses"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    RecordStatusEnumeration:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#RecordStatusEnumeration"
      description: Defining the enumeration for the record status
      enum:
      - new
      - update
      - delete
      - same
    UniqueID:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#UniqueID"
      description: "Characteristic for a unique id: every linked property to this\
        \ characteristic is a unique ID"
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:1.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    Boolean:
      type: boolean
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Boolean"
      description: Represents a boolean value (i.e. a "flag").
    Text:
      type: string
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text"
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    StatusCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#StatusCharacteristic"
      description: Enumeration of the different status values
      enum:
      - new
      - in progress
      - completed
      - closed
    AdditionalInformation:
      description: Additional information is stored as list of keys and list of values
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#AdditionalInformation"
      type: object
      properties:
        key:
          description: The unique key for this additional information
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#key"
          $ref: "#/components/schemas/UniqueID"
        value:
          description: The value for this additional information that refers to the
            linked unique key.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#value"
          $ref: "#/components/schemas/Text"
      required:
      - key
      - value
    AdditionalInformationList:
      description: A list of additional information
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#AdditionalInformationList"
      type: array
      items:
        $ref: "#/components/schemas/AdditionalInformation"
    PartAnalysis:
      description: The analysis results of ONE part
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#PartAnalysis"
      type: object
      properties:
        recordStatus:
          description: |-
            The record operation enumeration can be used to realize delta update concept.
            Delta update concept means:
            - You transfer an initial load of data
            - After the first week only the delta to the initial load is transferred


            The record status describes whether this record is:
            - new=>This record is transferred the first time
            - update=> Some properties of this record have changed compared to a previous transfer
            - delete=> This record was transferred in the initial load or in a previous delta update, but is not used any more and therefore it should be deleted on data consumer side
            - same=> This record was transferred in the initial load or in a previous delta update
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#recordStatus"
          $ref: "#/components/schemas/RecordStatusEnumeration"
        anonymizedVIN:
          description: OEM-specific hashed VIN. Unique within OEM.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#anonymizedVIN"
          $ref: "#/components/schemas/UniqueID"
        catenaXPartId:
          description: The fully anonymous Catena-X ID of the analysed part - only
            available after digital twin registry is fully operational.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#catenaXPartId"
          $ref: "#/components/schemas/UuidV4Trait"
        catenaXQualityTaskId:
          description: The fully anonymous and unique Catena-X ID of this quality
            task. This id is unique inside Catena-X data space.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#catenaXQualityTaskId"
          $ref: "#/components/schemas/UuidV4Trait"
        isDefect:
          description: "True: Analysis turned out that analysed part is defect according\
            \ part's specification."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#isDefect"
          $ref: "#/components/schemas/Boolean"
        manufacturerAnalysisID:
          description: Internal identifier for this analysis at manufacturer.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#manufacturerAnalysisID"
          $ref: "#/components/schemas/UniqueID"
        manufacturerPartName:
          description: "Part name given from  the manufacturer or supplier of this\
            \ part, component, sub component or raw material. A manufacturer part\
            \ name is NOT unique: All parts of the same kind share the same part name."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#manufacturerPartName"
          $ref: "#/components/schemas/Text"
        manufacturerPartNumber:
          description: "Part number given from  the manufacturer or supplier of this\
            \ part, component, sub component or raw material. A manufacturer part\
            \ number is NOT unique: All parts of the same kind share the same part\
            \ number."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#manufacturerPartNumber"
          $ref: "#/components/schemas/Text"
        manufacturerSerialNumber:
          description: "Serial number given from the manufacturer or supplier of this\
            \ part, component, sub component. A manufacturer serial number is unique:\
            \ With the serial number the produced part can be traced within the manufacturer."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#manufacturerSerialNumber"
          $ref: "#/components/schemas/UniqueID"
        parentAnalysisID:
          description: |-
            Internal identifier for this analysis on parent level.
            If the manufacturer is a TIER1 supplier -> parent level is OEM.
            If the manufacturer is TIER2 supplier -> parent level is TIER1 supplier.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#parentAnalysisID"
          $ref: "#/components/schemas/Text"
        parentPartNumber:
          description: |-
            Internal part number of the analysed part.
            If the manufacturer is a TIER1 supplier -> parent level is OEM.
            If the manufacturer is a TIER2 supplier -> parent level is TIER1 supplier.
            A parent part number is NOT unique: All parent parts of the same kind share the same parent part number.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#parentPartNumber"
          $ref: "#/components/schemas/Text"
        parentSerialNumber:
          description: |-
            Serial number of the analysed part.
            If the manufacturer is a TIER1 supplier -> parent level is OEM.
            If the manufacturer is a TIER2 supplier -> parent level is TIER1 supplier.
            A parent serial number is unique: With the serial number the produced part can be traced within the parent company.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#parentSerialNumber"
          $ref: "#/components/schemas/UniqueID"
        resultsDescription:
          description: Detailed description of part analysis results.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#resultsDescription"
          $ref: "#/components/schemas/Text"
        status:
          description: Status of this part analysis
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#status"
          $ref: "#/components/schemas/StatusCharacteristic"
        listOfAddtionalInformation:
          description: You can use this key:value list for additional properties that
            were not defined in this aspect model.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#listOfAddtionalInformation"
          $ref: "#/components/schemas/AdditionalInformationList"
      required:
      - anonymizedVIN
    PartsAnalysesList:
      description: A list for multiple part analyses
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#PartsAnalysesList"
      type: array
      items:
        $ref: "#/components/schemas/PartAnalysis"
    MetaCharacteristic:
      description: Characteristic for the meta information.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#MetaCharacteristic"
      type: object
      properties:
        selectionCriteria:
          description: Describes the selection criteria a Catena-X data provider has
            applied to create this data set.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#selectionCriteria"
          $ref: "#/components/schemas/Text"
        selectionStart:
          description: Describes the starting point for providing records in this
            data set.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#selectionStart"
          $ref: "#/components/schemas/Text"
        selectionEnd:
          description: Describes the end point for providing records in this data
            set.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#selectionEnd"
          $ref: "#/components/schemas/Text"
      required:
      - selectionCriteria
    PartsAnalyses:
      description: Parts analysis that are related to one quality task
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#PartsAnalyses"
      properties:
        listOfPartAnalyses:
          description: A list of several part analyses
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#listOfPartAnalyses"
          $ref: "#/components/schemas/PartsAnalysesList"
        metaInformation:
          description: 'This meta information is valid for all entries in this data
            set. The meta information is used to tell the data consumer which selection
            criteria were applied by the data provider. '
          x-samm-aspect-model-urn: "urn:samm:io.catenax.parts_analyses:3.0.0#metaInformation"
          $ref: "#/components/schemas/MetaCharacteristic"
      required:
      - listOfPartAnalyses
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    PartsAnalyses:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    PartsAnalyses:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PartsAnalyses"
      required: true
