---
openapi: 3.0.3
info:
  title: Packing List
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#PackingList"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/packing-list:
    get:
      tags:
      - PackingList
      operationId: getPackingList
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/PackingList"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/PackingList"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    DateCharacteristic:
      type: string
      format: date
      x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#DateCharacteristic"
      description: "Describes the date in the following format: YYYY-MM-DD."
    QuantityValueCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#QuantityValueCharacteristic"
      description: The quantity value associated with the unit expressed as float.
    ItemUnitEnumeration:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#ItemUnitEnumeration"
      description: Enumeration for common item units.
      enum:
      - unit:piece
      - unit:set
      - unit:pair
      - unit:page
      - unit:cycle
      - unit:kilowattHour
      - unit:gram
      - unit:kilogram
      - unit:tonneMetricTon
      - unit:tonUsOrShortTonUkorus
      - unit:ounceAvoirdupois
      - unit:pound
      - unit:metre
      - unit:centimetre
      - unit:kilometre
      - unit:inch
      - unit:foot
      - unit:yard
      - unit:squareCentimetre
      - unit:squareMetre
      - unit:squareInch
      - unit:squareFoot
      - unit:squareYard
      - unit:cubicCentimetre
      - unit:cubicMetre
      - unit:cubicInch
      - unit:cubicFoot
      - unit:cubicYard
      - unit:litre
      - unit:millilitre
      - unit:hectolitre
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hourUnitOfTime
      - unit:day
    ItemQuantityCharacteristic:
      description: "Characteristic for measurements of an item (mass, count, linear,\
        \ area, volume, misc)."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#ItemQuantityCharacteristic"
      type: object
      properties:
        value:
          description: The quantity value associated with the unit.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#quantityValue"
          $ref: "#/components/schemas/QuantityValueCharacteristic"
        unit:
          description: "The unit of an item. Common units may be related to mass,\
            \ count, linear, area, volume or misc."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#itemUnit"
          $ref: "#/components/schemas/ItemUnitEnumeration"
      required:
      - value
      - unit
    QuantityCharacteristic:
      description: Describes the quantity of the itemby providing a quantity value
        and the measurement unit in which the quantity is measured.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#QuantityCharacteristic"
      type: object
      properties:
        itemQuantityProperty:
          description: "This property defines common units and the value for items.\
            \ Items may be measured as mass, countable, miscellaneous, linear, area\
            \ or volume."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.quantity:2.0.0#itemQuantityProperty"
          $ref: "#/components/schemas/ItemQuantityCharacteristic"
      required:
      - itemQuantityProperty
    PositionCharacteristic:
      type: number
      maximum: 2147483647
      minimum: -2147483648
      x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#PositionCharacteristic"
      description: 'Describes the position in a numeric form. '
    Text:
      type: string
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text"
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    ListData:
      description: Catena-X ID and data of the packing list item.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#ListData"
      type: object
      properties:
        quantity:
          description: Quantity of the item.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#quantity"
          $ref: "#/components/schemas/QuantityCharacteristic"
        position:
          description: Numbering of all positions or items in the packing list.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#position"
          $ref: "#/components/schemas/PositionCharacteristic"
        itemDescription:
          description: Describes the item in the packing list.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#itemDescription"
          $ref: "#/components/schemas/Text"
        itemName:
          description: Name of the item seen in the packing list.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#itemName"
          $ref: "#/components/schemas/Text"
        catenaXId:
          description: "The Catena-X ID of the given part (e.g. the assembly), valid\
            \ for the Catena-X dataspace."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#catenaXId"
          $ref: "#/components/schemas/UuidV4Trait"
      required:
      - quantity
      - position
      - itemName
    SetOfListItems:
      description: Set Of List Items of the packing list.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#SetOfListItems"
      type: array
      items:
        $ref: "#/components/schemas/ListData"
      uniqueItems: true
    BpnaTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnaTrait"
      description: "The provided regular expression ensures that the BPNA is composed\
        \ of prefix 'BPNA', 10 digits and two alphanumeric letters."
      pattern: "^BPNA[a-zA-Z0-9]{12}$"
    SenderAddressCharacteristic:
      description: Characteristic for the Sender Address.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#SenderAddressCharacteristic"
      type: object
      properties:
        bpnaProperty:
          description: Property based on a BPNA.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#bpnaProperty"
          $ref: "#/components/schemas/BpnaTrait"
      required:
      - bpnaProperty
    ReceiverAddressCharacteristic:
      description: Characteristic for the Receiver Address.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#ReceiverAddressCharacteristic"
      type: object
      properties:
        bpnaProperty:
          description: Property based on a BPNA.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#bpnaProperty"
          $ref: "#/components/schemas/BpnaTrait"
      required:
      - bpnaProperty
    PackingList:
      description: "This model represents a commonly used packing list used in logistics\
        \ and shipment of goods. It displays goods and their corresponding quantity,\
        \ as well as, if given the Catena-X Id of the good."
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#PackingList"
      properties:
        shippingDate:
          description: Date once item(s) are shipped.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#shippingDate"
          $ref: "#/components/schemas/DateCharacteristic"
        listItems:
          description: Set of items part of the packing list.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#listItems"
          $ref: "#/components/schemas/SetOfListItems"
        senderAddress:
          description: "Sender of the delivery, including the name and address."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#senderAddress"
          $ref: "#/components/schemas/SenderAddressCharacteristic"
        receiverAddress:
          description: "Receiver of the delivery, including the name and address."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.packing_list:1.0.0#receiverAddress"
          $ref: "#/components/schemas/ReceiverAddressCharacteristic"
      required:
      - shippingDate
      - listItems
      - senderAddress
      - receiverAddress
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    PackingList:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    PackingList:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PackingList"
      required: true
