---
openapi: 3.0.3
info:
  title: material for recycling
  version: v1
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/material-for-recycling:
    get:
      tags:
      - MaterialForRecycling
      operationId: getMaterialForRecycling
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/MaterialForRecycling'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MaterialForRecycling'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text:
      type: string
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    urn_bamm_io.catenax.material_for_recycling_1.1.0_MaterialClass:
      type: string
      description: Class according to the refernced standard the material belongs
        to. The IMDS recommendations and the IMDS rules are exclusevily accessible
        within the IMDS portal to members of the IMDS association. In order to access
        the data one needs to be member of the association.
    urn_bamm_io.catenax.material_for_recycling_1.1.0_AggregateState:
      type: string
      enum:
      - solid
      - liquid
      - gasenous
    urn_bamm_io.catenax.material_for_recycling_1.1.0_Percentage:
      type: number
      description: Percentage of already recycled material contained.
    urn_bamm_io.openmanufacturing_characteristic_2.0.0_UnitReference:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      description: Describes a Property containing a reference to one of the units
        in the Unit Catalog.
    urn_bamm_io.catenax.material_for_recycling_1.1.0_Value:
      type: number
      description: Quantifiable value as double in reference to the measurementUnit
    urn_bamm_io.catenax.material_for_recycling_1.1.0_QuantityCharacteristic:
      description: quantity characteristic for the material expressed in value and
        unit
      type: object
      properties:
        unit:
          description: |-
            Unit of Measurement for the quantity of serialized objects.
            The recommended units are the SI units such as unit:kilogram or  additional unit:percent
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_UnitReference'
        value:
          description: Measurement value as a double. The unit is saved in the property
            measurementUnit
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_recycling_1.1.0_Value'
      required:
      - unit
      - value
    urn_bamm_io.catenax.material_for_recycling_1.1.0_ComponentEntity:
      description: The properties that describe a component
      type: object
      properties:
        aggregateState:
          description: The aggregate state the materialis in at the timepoint the
            item is disassembled
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_recycling_1.1.0_AggregateState'
        recycledContent:
          description: Indicates if the material was is recycled. Percentage of how
            much of the material was recycled. This can be an aggregation regarding
            the materials below.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_recycling_1.1.0_Percentage'
        materialAbbreviation:
          description: A short abbreviation of the materialName
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text'
        materialClass:
          description: The class of a material following the referenced standard.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_recycling_1.1.0_MaterialClass'
        materialName:
          description: The commercial name of a material
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text'
        quantity:
          description: quantity of the material expressed in value and unit
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_recycling_1.1.0_QuantityCharacteristic'
      required:
      - materialClass
      - materialName
    urn_bamm_io.catenax.material_for_recycling_1.1.0_ComponentCharacteristic:
      description: Describes the consistency
      type: array
      items:
        $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_recycling_1.1.0_ComponentEntity'
      uniqueItems: true
    MaterialForRecycling:
      description: This model depicts a material as seen by the recycler at the end
        of the lifecycle of a product. If a material consists of only one single component
        the name and class for the aspect are not used
      type: object
      properties:
        materialName:
          description: The commercial name of a material
          $ref: '#/components/schemas/urn_bamm_io.openmanufacturing_characteristic_2.0.0_Text'
        materialClass:
          description: The class of a material following the referenced standard.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_recycling_1.1.0_MaterialClass'
        component:
          description: Components the material consists of
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_recycling_1.1.0_ComponentCharacteristic'
        recycledContent:
          description: Indicates if the material was is recycled. Percentage of how
            much of the material was recycled. This can be an aggregation regarding
            the materials below.
          $ref: '#/components/schemas/urn_bamm_io.catenax.material_for_recycling_1.1.0_Percentage'
      required:
      - component
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    MaterialForRecycling:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    MaterialForRecycling:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MaterialForRecycling'
