---
openapi: 3.0.3
info:
  title: BOM as specified
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#BomAsSpecified"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/bom-as-specified:
    get:
      tags:
      - BomAsSpecified
      operationId: getBomAsSpecified
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/BomAsSpecified"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/BomAsSpecified"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    IdentifierCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#IdentifierCharacteristic"
    Text:
      type: string
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text"
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    IndexCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#IndexCharacteristic"
      description: Characteristic of the index.
    QuantityCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#QuantityCharacteristic"
      description: Characteristic of the quantity.
    UnitReference:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#UnitReference"
      description: Describes a Property containing a reference to one of the units
        in the Unit Catalog.
    NumberOfObjects:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#NumberOfObjects"
      description: Quantifiable number of objects in reference to the measurementUnit.
    PartQuantityCharacteristic:
      description: The characteristic of the part quantity.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#PartQuantityCharacteristic"
      type: object
      properties:
        measurementUnit:
          description: Unit of measurement for the quantity of serialized objects.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#measurementUnit"
          $ref: "#/components/schemas/UnitReference"
        quantityNumber:
          description: The number of objects related to the measurement unit.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#quantityNumber"
          $ref: "#/components/schemas/NumberOfObjects"
      required:
      - measurementUnit
      - quantityNumber
    PartClassificationEntity:
      description: The entity encapsulating the properties of the part classification.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#PartClassificationEntity"
      type: object
      properties:
        key:
          description: Key within the classification.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#key"
          $ref: "#/components/schemas/Text"
        value:
          description: Value within the classification.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#value"
          $ref: "#/components/schemas/Text"
      required:
      - key
      - value
    PartClassificationCharacteristic:
      description: The characteristic of the part classification.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#PartClassificationCharacteristic"
      type: array
      items:
        $ref: "#/components/schemas/PartClassificationEntity"
      uniqueItems: true
    PartEntity:
      description: Entity encapsulating the properies describing a part
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#PartEntity"
      type: object
      properties:
        ownerPartId:
          description: "This is the key field of the component which usually keeps\
            \ the part numbers used in after-sales, e.g. when repairing broken parts\
            \ and searching for a replacement. This ownerPartId itself isn't usually\
            \ bound to one part version, with the assumption that all part versions\
            \ with the same ownerPartId are mutually interchangeable."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#ownerPartId"
          $ref: "#/components/schemas/Text"
        partVersion:
          description: "This is the version of the part. The engineering will at times\
            \ supercede an older part version by a newer one, which might have different\
            \ material aspects, physical dimensions etc., still maintaining compatibility."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#partVersion"
          $ref: "#/components/schemas/Text"
        partQuantity:
          description: This is the quantity how often this part is in the item.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#partQuantity"
          $ref: "#/components/schemas/PartQuantityCharacteristic"
        partDescription:
          description: The description of the part in the primary language of the
            production facility of the product owner.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#partDescription"
          $ref: "#/components/schemas/Text"
        partClassification:
          description: The part classification.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#partClassification"
          $ref: "#/components/schemas/PartClassificationCharacteristic"
      required:
      - ownerPartId
    PartCharacteristic:
      description: Characteristic of the part.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#PartCharacteristic"
      type: array
      items:
        $ref: "#/components/schemas/PartEntity"
      uniqueItems: true
    ItemEntity:
      description: Entity encapsulating the properties that describe an item.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#ItemEntity"
      type: object
      properties:
        itemCategory:
          description: "The BomAsSpecified defines the view of the OEM or producer\
            \ of the whole product, e.g. the OEM of a vehicle. It is free of any supplier-related\
            \ information and specifies the promised and guaranteed content of the\
            \ whole product to the end customer. This “top-down” view is in contrast\
            \ to the “bottom-up” view of the SingleLevelBoMAsPlanned, though several\
            \ sub-aspects are shared. The BomAsSpecified is merely one aspect, which\
            \ is attached to the twin of the whole product and itself does neither\
            \ introduce further twins nor reference them. Instead it merely comprises\
            \ all functional information required by dismantlers, workshops or requestors\
            \ for used parts to search for and to make a match on the market place."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#itemCategory"
          $ref: "#/components/schemas/Text"
        index:
          description: Additional differentiation if multiple items share the same
            the item descriptor.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#index"
          $ref: "#/components/schemas/IndexCharacteristic"
        quantity:
          description: "If the item is provided several times alike, the quantity\
            \ on this level can specify how often. At this level pieces is assumed\
            \ as the only unit. For further differentiation."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#quantity"
          $ref: "#/components/schemas/QuantityCharacteristic"
        part:
          description: The description of the part in the primary language of the
            production facility of the product owner.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#part"
          $ref: "#/components/schemas/PartCharacteristic"
      required:
      - itemCategory
      - part
    ItemCharacteristic:
      description: The characteristic of the items.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#ItemCharacteristic"
      type: array
      items:
        $ref: "#/components/schemas/ItemEntity"
      uniqueItems: true
    BomAsSpecified:
      description: "The BomAsSpecified defines the view of the OEM or producer of\
        \ the whole product, e.g. the OEM of a vehicle. It is free of any supplier-related\
        \ information and specifies the promised and guaranteed content of the whole\
        \ product to the end customer. This “top-down” view is in contrast to the\
        \ “bottom-up” view of the SingleLevelBoMAsPlanned, though several sub-aspects\
        \ are shared. The BomAsSpecified is merely one aspect, which is attached to\
        \ the twin of the whole product and itself does neither introduce further\
        \ twins nor reference them. Instead it merely comprises all functional information\
        \ required by dismantlers, workshops or requestors for used parts to search\
        \ for and to make a match on the market place."
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#BomAsSpecified"
      properties:
        identifier:
          description: "A unique reference for the product owner of this set of items,\
            \ and used by the product owner only for internal referencing. "
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#identifier"
          $ref: "#/components/schemas/IdentifierCharacteristic"
        item:
          description: "Top-level separation of parts which represent a set and shall\
            \ indicate that the individual items are within each other completely\
            \ assembled and treated as a unit, but are separable units, e.g. the \"\
            vehicle\", \"electricCharger\" and the \"winter wheels\" are separated\
            \ and could over lifetime be sold as individual items by the end customer.\n\
            \ \nFor other end-customer products a set might be like \"cordless screwdriver\"\
            \ and 2 times \"supplemental battery\"."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.bom_as_specified:1.0.1#item"
          $ref: "#/components/schemas/ItemCharacteristic"
      required:
      - identifier
      - item
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    BomAsSpecified:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    BomAsSpecified:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BomAsSpecified"
      required: true
