---
openapi: 3.0.3
info:
  title: Delivery information
  version: v1
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/delivery-information:
    get:
      tags:
      - DeliveryInformation
      operationId: getDeliveryInformation
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/DeliveryInformation'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryInformation'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_samm_io.catenax.delivery_information_1.0.0_OrderIdCharacteristic:
      type: string
      description: "This is a proprietary order ID, generated by either the supplier\
        \ side or customer side."
    urn_samm_io.catenax.delivery_information_1.0.0_OrderPositionIdCharacteristic:
      type: string
      description: The position ID is unique for an order and used within business
        context to refer to a position.
    urn_samm_io.catenax.delivery_information_1.0.0_OrderPositionReferenceCharacteristic:
      description: "The order position reference includes reference numbers for the\
        \ order and the position. As these information are meant for the customer,\
        \ the customer reference numbers are mandatory."
      type: object
      properties:
        supplierOrderId:
          description: "This is the order number on the supplier side that is given\
            \ by e.g., the supplier's enterprise resource planning system."
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_OrderIdCharacteristic'
        customerOrderId:
          description: "This is the order number on the customer side that can be\
            \ given by e.g., the customer's enterprise resource planning system."
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_OrderIdCharacteristic'
        customerOrderPositionId:
          description: "This is an identifier for the position of an order defined\
            \ by the customer. It's not a technical identifier, such as an UUID. This\
            \ identifier is used within the business context when talking about the\
            \ position."
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_OrderPositionIdCharacteristic'
      required:
      - customerOrderId
      - customerOrderPositionId
    urn_samm_io.catenax.delivery_information_1.0.0_DateTimeStamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      description: The Date with the timezone.
    urn_samm_io.catenax.shared.quantity_1.0.0_QuantityValueCharacteristic:
      type: number
      description: The quantity value associated with the unit expressed as float.
    urn_samm_io.catenax.shared.quantity_1.0.0_ItemUnitEnumeration:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      description: Enumeration for common item units.
      enum:
      - unit:piece
      - unit:set
      - unit:pair
      - unit:page
      - unit:cycle
      - unit:kilowattHour
      - unit:gram
      - unit:kilogram
      - unit:tonneMetricTon
      - unit:tonUsOrShortTonUkorus
      - unit:ounceAvoirdupois
      - unit:pound
      - unit:metre
      - unit:centimetre
      - unit:kilometre
      - unit:inch
      - unit:foot
      - unit:yard
      - unit:squareCentimetre
      - unit:squareMetre
      - unit:squareInch
      - unit:squareFoot
      - unit:squareYard
      - unit:cubicCentimetre
      - unit:cubicMetre
      - unit:cubicInch
      - unit:cubicFoot
      - unit:cubicYard
      - unit:litre
      - unit:millilitre
      - unit:hectolitre
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hourUnitOfTime
      - unit:day
    urn_samm_io.catenax.delivery_information_1.0.0_QuantityCharacteristic:
      description: Describes the quantity and the unit of measure with which the delivery
        is measured.
      type: object
      properties:
        value:
          description: The quantity value associated with the unit.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_QuantityValueCharacteristic'
        unit:
          description: "The unit of an item. Common units may be related to mass,\
            \ count, linear, area, volume or misc."
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.quantity_1.0.0_ItemUnitEnumeration'
      required:
      - value
      - unit
    urn_samm_io.catenax.delivery_information_1.0.0_EventTypeEnumeration:
      type: string
      description: "Event type is the permutation of actual, estimated and departure,\
        \ arrival."
      enum:
      - estimated-departure
      - estimated-arrival
      - actual-departure
      - actual-arrival
    urn_samm_io.catenax.delivery_information_1.0.0_TransitEvent:
      description: Entity for specifying the departure or arrival time and date.
      type: object
      properties:
        dateTimeOfEvent:
          description: Time of Event signifies the time and date when the products
            leave (or will leave) the origin location of a delivery (i.e. supplier's
            production site) or when the products arrive (or will arrive) at the destination
            location of the delivery (i.e. customer's production site).
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_DateTimeStamp'
        eventType:
          description: Event type describes wether the mentioned timeOfEvent refers
            to a departure or arrival and provides the status of the delivery (estimated
            or actual).
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_EventTypeEnumeration'
      required:
      - dateTimeOfEvent
      - eventType
    urn_samm_io.catenax.delivery_information_1.0.0_TransitEventsTrait:
      description: The TransitEventsSet MUST contain either 1 or 2 TransitEvents.
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_TransitEvent'
      uniqueItems: true
      maxItems: 2
      minItems: 1
    urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnaTrait:
      type: string
      description: "The provided regular expression ensures that the BPNA is composed\
        \ of prefix 'BPNA', 10 digits and two uppercase letters."
      pattern: "^BPNA[0-9]{8}[a-zA-Z0-9]{4}$"
    urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnsTrait:
      type: string
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two uppercase letters."
      pattern: "^BPNS[0-9]{8}[a-zA-Z0-9]{4}$"
    urn_samm_io.catenax.delivery_information_1.0.0_LocationCharacteristic:
      description: Location characteristic describes a particular location of a business
        partner. It MUST include the information of the site and it MAY include the
        exact address.
      type: object
      properties:
        bpnaProperty:
          description: Property based on a BPNA.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnaTrait'
        bpnsProperty:
          description: Property based on a BPNS.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_1.0.0_BpnsTrait'
      required:
      - bpnsProperty
    urn_samm_io.catenax.delivery_information_1.0.0_TransitLocationsCharacteristic:
      description: Transit locations includes origin and destination points in the
        transportation of goods. It refers to specific location of the source or production
        facility (origin) or the designated endpoint (destination).
      type: object
      properties:
        origin:
          description: 'Origin refers to the starting point or the location from which
            the items are being shipped to the customer. '
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_LocationCharacteristic'
        destination:
          description: Destination refers to the final endpoint or intended location
            where the items are meant to arrive (i.e. customer factory).
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_LocationCharacteristic'
      required:
      - origin
      - destination
    urn_samm_io.catenax.delivery_information_1.0.0_TrackingNumberCharacteristic:
      type: string
      description: Alphanumeric string that is defined by the logistics service provider
        in order to track and identify the shipment.
    urn_samm_io.catenax.delivery_information_1.0.0_IncotermEnumeration:
      type: string
      description: All 12 possible values for the incoterms.
      enum:
      - EXW
      - FCA
      - CPT
      - CIP
      - DAP
      - DAT
      - DPU
      - DDP
      - FAS
      - FOB
      - CFR
      - CIF
    urn_samm_io.catenax.delivery_information_1.0.0_Delivery:
      description: "Quantity, origin and destination, time of departure and arrival,\
        \ tracking number and incoterms for a certain delivery."
      type: object
      properties:
        deliveryQuantity:
          description: Amount of items of a delivery between a supplier and a customer.
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_QuantityCharacteristic'
        transitEvents:
          description: Transit dates provide date and time of departure and date and
            time of arrival for a specific delivery. Date and time are set according
            to the timezone.
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_TransitEventsTrait'
        transitLocations:
          description: Physical locations of the origin and destination.
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_TransitLocationsCharacteristic'
        trackingNumber:
          description: "Is a unique alphanumeric code assigned to a shipment by a\
            \ logistics service provider, allowing it to be monitored and traced throughout\
            \ its journey between origin and destination."
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_TrackingNumberCharacteristic'
        incoterm:
          description: Incoterm which is assigned to a delivery.
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_IncotermEnumeration'
      required:
      - deliveryQuantity
      - transitEvents
      - transitLocations
    urn_samm_io.catenax.delivery_information_1.0.0_DeliveryCollection:
      description: "Collection of deliveries that may relate to different origin or\
        \ destination, different quantities and different time of departure or time\
        \ of arrival. It MAY include different tracking numbers and different incoterms."
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_Delivery'
    urn_samm_io.catenax.delivery_information_1.0.0_Position:
      description: The Position can contain one or more deliveries involving one or
        more supplier's and one or more customer's sites. A position may be anonymous
        (no orderPositionReference is set) or may reference a position within an order.
      type: object
      properties:
        orderPositionReference:
          description: The order position reference contains information to identify
            a position within an order.
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_OrderPositionReferenceCharacteristic'
        lastUpdatedOnDateTime:
          description: Date and time at which the position has been updated by the
            data provider. Date and time are set according to the timezone.
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_DateTimeStamp'
        deliveries:
          description: Deliveries are referred to the deliveries of an order position.
            One order position can be split into multiple deliveries. One delivery
            can have a different origin and destination than another delivery.
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_DeliveryCollection'
      required:
      - lastUpdatedOnDateTime
      - deliveries
    urn_samm_io.catenax.delivery_information_1.0.0_PositionsCollection:
      description: "If any delivery for the customer is estimated, then there is at\
        \ least one position. If each order position is assigned to one (or more)\
        \ delivery (an OrderPositionReference is set), then multiple positions can\
        \ be given."
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_Position'
    urn_samm_io.catenax.delivery_information_1.0.0_MaterialNumberCharacteristic:
      type: string
      description: "The material number is a multi-character string, usually assigned\
        \ by an ERP system."
    urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    DeliveryInformation:
      description: "This aspect represents the estimated and actual delivery information\
        \ of one specific item, which is being shipped from the supplier to the customer."
      type: object
      properties:
        positions:
          description: "The positions refer to positions within an order of the given\
            \ item (see material number supplier, material number customer and material\
            \ global asset ID) for which the delivery information is exchanged. The\
            \ positions can be differentiated by the order position reference. If\
            \ no order position reference is given, then there is only one position\
            \ containing all estimated deliveries of the item."
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_PositionsCollection'
        materialNumberCustomer:
          description: "Material identifier as assigned by the customer. This material\
            \ number identifies the material (as estimated) in the customer's database.\
            \ For standard parts (e.g. screws) for which a customer does not have\
            \ an own number, the material number supplier should be set in this field,\
            \ too."
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_MaterialNumberCharacteristic'
        materialGlobalAssetId:
          description: Material identifier used uniquely to identify the Material
            (e.g. PartAsestimated).
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.uuid_1.0.0_UuidV4Trait'
        materialNumberSupplier:
          description: Material identifier as assigned by the supplier. This material
            number identifies the material (as estimated) in the supplier's database.
          $ref: '#/components/schemas/urn_samm_io.catenax.delivery_information_1.0.0_MaterialNumberCharacteristic'
      required:
      - positions
      - materialNumberCustomer
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    DeliveryInformation:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    DeliveryInformation:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeliveryInformation'
