---
openapi: 3.0.3
info:
  title: Batch
  version: v2
  x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#Batch"
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/batch:
    get:
      tags:
      - Batch
      operationId: getBatch
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/Batch"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          $ref: "#/components/schemas/Batch"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:1.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    KeyTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#KeyTrait"
      description: Constraint that ensures that the predefined keys are used.
      pattern: ^(manufacturerId|batchId)$
    ValueCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#ValueCharacteristic"
      description: The value of an identifier.
    KeyValueList:
      description: "A list of key value pairs for local identifiers, which are composed\
        \ of a key and a corresponding value."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#KeyValueList"
      type: object
      properties:
        key:
          description: The key of a local identifier.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#key"
          $ref: "#/components/schemas/KeyTrait"
        value:
          description: The value of an identifier.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#value"
          $ref: "#/components/schemas/ValueCharacteristic"
      required:
      - key
      - value
    LocalIdentifierCharacteristic:
      description: "A batch may have multiple attributes, which uniquely identify\
        \ that batch in a specific dataspace(e.g. the manufacturer`s dataspace)"
      x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#LocalIdentifierCharacteristic"
      type: array
      items:
        $ref: "#/components/schemas/KeyValueList"
      uniqueItems: true
    Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Timestamp"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    ProductionCountryCodeTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#ProductionCountryCodeTrait"
      description: Regular Expression that ensures a three-letter code
      pattern: "^[A-Z]{3}$"
    ManufacturingCharacteristic:
      description: Characteristic to describe manufacturing related data
      x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#ManufacturingCharacteristic"
      type: object
      properties:
        date:
          description: "Timestamp of the manufacturing date as the final step in production\
            \ process(e.g. final quality check, ready-for-shipment event)"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#date"
          $ref: "#/components/schemas/Timestamp"
        country:
          description: Country code where the part was manufactured
          x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#country"
          $ref: "#/components/schemas/ProductionCountryCodeTrait"
      required:
      - date
    PartIdCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#PartIdCharacteristic"
      description: "The part ID is a multi-character string, usually assigned by an\
        \ ERP system"
    PartNameCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#PartNameCharacteristic"
      description: Part Name in string format from the respective system in the value
        chain
    ClassificationCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#ClassificationCharacteristic"
      description: "A part type must be placed into one of the following classes:\
        \ 'component', 'product', 'software', 'assembly', 'tool', or 'raw material'."
      enum:
      - product
      - raw material
      - software
      - assembly
      - tool
      - component
    PartTypeInformationCharacteristic:
      description: The characteristics of the part type
      x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#PartTypeInformationCharacteristic"
      type: object
      properties:
        manufacturerPartId:
          description: Part ID as assigned by the manufacturer of the part. The Part
            ID identifies the part(as designed) in the manufacturer`s dataspace. The
            Part ID does not reference a specific instance of a part and thus should
            not be confused with the serial number or batch number.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#manufacturerPartId"
          $ref: "#/components/schemas/PartIdCharacteristic"
        nameAtManufacturer:
          description: Name of the part as assigned by the manufacturer
          x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#nameAtManufacturer"
          $ref: "#/components/schemas/PartNameCharacteristic"
        classification:
          description: The classification of the part type according to STEP standard
            definition
          x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#classification"
          $ref: "#/components/schemas/ClassificationCharacteristic"
      required:
      - manufacturerPartId
      - nameAtManufacturer
      - classification
    BpnsCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:1.0.0#BpnsCharacteristic"
      description: "BPNS (Business Partner Number Site) represents a site which can\
        \ be a production plant. A site can also be e.g. an office or a warehouse.\
        \ An information related to a site is e.g. needed for reporting issues (How\
        \ many sites does e.g. Beispiel AG have?), status of operation (out of operations\
        \ due to environmental disaster), for certificates on site level (e.g. environment\
        \ certificates) or for internal regulations on site level, (e.g. security\
        \ topics, Corona rules,...). Several addresses (= BPNA with different streets\
        \ and different gates) can belong to one site. A BPNS should be always linked\
        \ to one BPNL via relationship 'belongs to legal entity'."
    FunctionCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:1.0.0#FunctionCharacteristic"
      description: Describes the characteristics of the function for a site related
        to the respective part.
      enum:
      - production
      - warehouse
      - spare part warehouse
    SitesEntity:
      description: "Describes the ID and function of a site for the associated part\
        \ in the AsBuilt context(e.g. SerialPart, Batch, jIS)."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:1.0.0#SitesEntity"
      type: object
      properties:
        catenaXsiteId:
          description: "The identifier of the site according to Catena-X BPDM. The\
            \ catenaXsiteId must be a valid Catena-X BPN. The BPN is a unique, unchangeable\
            \ identifier for Business Partners / company locations from foundation\
            \ to closure, regardless of the different business relationships / structures\
            \ between or within the Business Partners or company locations."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:1.0.0#catenaXsiteId"
          $ref: "#/components/schemas/BpnsCharacteristic"
        function:
          description: The function of the site in relation to the part(i.e. the activity
            within the value chain of the part that is performed at the site)
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:1.0.0#function"
          $ref: "#/components/schemas/FunctionCharacteristic"
      required:
      - catenaXsiteId
      - function
    SitesCharacteristic:
      description: Sites Characteristic
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:1.0.0#SitesCharacteristic"
      type: array
      items:
        $ref: "#/components/schemas/SitesEntity"
      uniqueItems: true
    Batch:
      description: "A batch is a quantity of(semi-) finished products or(raw) material\
        \ product that have been produced under the same circumstances(e.g. same production\
        \ location), as specified groups or amounts, within a certain time frame.\
        \ Every batch can differ in the number or amount of products. Different batches\
        \ can have varied specifications, e.g., different colors. A batch is identified\
        \ via a Batch ID."
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#Batch"
      properties:
        catenaXId:
          description: "The fully anonymous Catena-X ID of the batch, valid for the\
            \ Catena-X dataspace."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#catenaXId"
          $ref: "#/components/schemas/UuidV4Trait"
        localIdentifiers:
          description: "A local identifier enables identification of a part in a specific\
            \ dataspace, but is not unique in Catena-X dataspace. Multiple local identifiers\
            \ may exist."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#localIdentifiers"
          $ref: "#/components/schemas/LocalIdentifierCharacteristic"
        manufacturingInformation:
          description: "Information from manufacturing process, such as manufacturing\
            \ date and manufacturing country"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#manufacturingInformation"
          $ref: "#/components/schemas/ManufacturingCharacteristic"
        partTypeInformation:
          description: The part type of which the batch has been instantiated of.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.batch:2.0.1#partTypeInformation"
          $ref: "#/components/schemas/PartTypeInformationCharacteristic"
        sites:
          description: "A site is a delimited geographical area where a legal entity\
            \ does business(geographical address with geo coordinates).A site always\
            \ has a primary physical address. It is possible that further physical\
            \ addresses are specified for the site. P.O. box details are only possible\
            \ in addition to the physical address. A site has a 1:n relation to addresses,\
            \ means at least 1 address is necessary and multiple addresses are possible."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.part_site_information_as_built:1.0.0#sites"
          $ref: "#/components/schemas/SitesCharacteristic"
      required:
      - catenaXId
      - localIdentifiers
      - manufacturingInformation
      - partTypeInformation
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    Batch:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    Batch:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Batch"
      required: true
