---
openapi: 3.0.3
info:
  title: Bill of Process shared Aspect
  version: v1
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/bill-of-process-shared-aspect:
    get:
      tags:
      - BillOfProcessSharedAspect
      operationId: getBillOfProcessSharedAspect
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: '#/components/responses/BillOfProcessSharedAspect'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_ProcessStepIdentifierList:
      description: List of process step identifiers to reference to  other process
        steps that are part of the bill of process
      type: array
      items:
        type: string
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_StringCharacteristic:
      type: string
      description: Characteristic to express string values
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_SemanticListCharacteristic:
      description: A list containing all semantic references for a parameter
      type: array
      items:
        type: string
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_ParameterKeyCharacteristic:
      type: string
      description: Enumeration that predefines values for the parameter key
      enum:
      - HasValue
      - HasNoValue
      - HasValueRange
      - HasTolerances
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_ValueRange:
      description: Entity for each value range item
      type: object
      properties:
        lowerValue:
          description: Lower border of a value range item
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_StringCharacteristic'
        upperValue:
          description: Upper border for a value range item
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_StringCharacteristic'
        name:
          description: Name of the parameter
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_StringCharacteristic'
      required:
      - lowerValue
      - upperValue
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_ValueRangeList:
      description: List with value ranges for a parameter
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_ValueRange'
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_TolerancesEntity:
      description: Entity to express the tolerances of a parameter
      type: object
      properties:
        lowerLimit:
          description: The lower direct limit of the tolerance
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_StringCharacteristic'
        upperLimit:
          description: Upper direct limit of the tolerance
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_StringCharacteristic'
        name:
          description: Name of the parameter
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_StringCharacteristic'
      required:
      - lowerLimit
      - upperLimit
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_TolerancesCharacteristic:
      description: List with tolerances for a parameter's value
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_TolerancesEntity'
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_Parameter:
      description: "Generic entity to characterize parameters. It distinguished four\
        \ cases: a parameter without a value, a parameter with a value, a parameter\
        \ with a value range and a parameter with tolerances "
      type: object
      properties:
        name:
          description: Name of the parameter
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_StringCharacteristic'
        value:
          description: Value of the parameter
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_StringCharacteristic'
        semanticReference:
          description: Reference to a semantic namespace in which the type of the
            parameter is defined
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_SemanticListCharacteristic'
        parameterKey:
          description: "Enumeration that is used to distinguish whether the parameter\
            \ has no value, has a value, has a value range or has a value with tolerances"
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_ParameterKeyCharacteristic'
        valueRangeList:
          description: List with value ranges for a parameter
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_ValueRangeList'
        tolerances:
          description: 'Tolerances for a parameter '
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_TolerancesCharacteristic'
      required:
      - name
      - semanticReference
      - parameterKey
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_ParameterList:
      description: A list of parameters
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_Parameter'
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_PrecedenceElement:
      description: Entity to link the current process step to its successors
      type: object
      properties:
        successor:
          description: 'List of subsequent process step which can be executed in any
            order '
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_ProcessStepIdentifierList'
      required:
      - successor
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_PrecedenceElementList:
      description: Set of process steps which have to be executed in parallel
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_PrecedenceElement'
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_PrecedenceElements:
      description: List of process steps that must be executed in parallel
      type: object
      properties:
        precedenceElements:
          description: List process steps that must be executed in parallel
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_PrecedenceElementList'
      required:
      - precedenceElements
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_PrecedenceRelationCharacteristic:
      description: 'List to express alternative process sequences '
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_PrecedenceElements'
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_ProcessStepTypeCharacteristic:
      type: string
      description: "Distinguishes 4 cases of process steps: the first and the last\
        \ process step, a process step that is in between the first and the last,\
        \ or a subprocess step "
      enum:
      - IsFirstElement
      - IsLastElement
      - IsProcessElement
      - IsSubprocessElement
    urn_samm_io.catenax.manufacturing_capability_3.0.0_IdCharacteristic:
      type: string
      description: Characteristic for identifiers.
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_ProcessStep:
      description: Entity to characterize single process steps
      type: object
      properties:
        processStepIdentifier:
          description: Unique identifier for a concrete process step
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_ProcessStepIdentifierList'
        inputParameters:
          description: Optional list of parameters that are required to execute the
            corresponding process step
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_ParameterList'
        outputParameters:
          description: Optional list of parameters that are returned from the process
            step and can be used as inputParameters for subsequent steps
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_ParameterList'
        precedenceRelation:
          description: "List of alternative process steps from which the manufacturer\
            \ has to select exactly one step to be executed. In case of no alternative\
            \ process step, the list features only one element. In case of the last\
            \ element, the property is not used, since the process step has no successor"
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_PrecedenceRelationCharacteristic'
        childProcessSteps:
          description: "List of child processes that need to be executed to complete\
            \ the parent process step. It enables the expression of hierarchies between\
            \ capabilities, e.g. a transport capability needs to execute at least\
            \ a pick, a move and a place capability"
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_ProcessStepIdentifierList'
        processStepType:
          description: "Distinguishes process steps based on whether there are the\
            \ first or last process step to be executed, or if they are a subprocess\
            \ step, which subdivides a higher-level process step into smaller process\
            \ steps"
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_ProcessStepTypeCharacteristic'
        capabilityId:
          description: Locally unique identifier for a capability.
          $ref: '#/components/schemas/urn_samm_io.catenax.manufacturing_capability_3.0.0_IdCharacteristic'
      required:
      - processStepIdentifier
      - processStepType
      - capabilityId
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_ProcessStepsList:
      description: Unordered list that contains all process steps to manufacture a
        product. The relation between these process steps are created through the
        precedence relation property
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_ProcessStep'
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_BillOfProcessIdCharacteristic:
      type: string
      description: Characteristic for Bill of process Identifiers
    urn_samm_io.catenax.shared.message_header_2.0.0_SemanticVersioningTrait:
      type: string
      description: Constraint for defining a SemVer version.
      pattern: "^(0|[1-9][0-9]*).(0|[1-9][0-9]*).(0|[1-9][0-9]*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*)(.[0-9A-Za-z-]+)*)?([0-9A-Za-z-]+(.[0-9A-Za-z-]+)*)?$"
    urn_samm_io.catenax.shared.bill_of_process_1.0.0_BillOfProcessCharacteristic:
      description: Characteristic containing a bill of process
      type: object
      properties:
        process:
          description: "List that contains all manufacturing steps of a product, whereat\
            \ each manufacturing step refers to exactly one capability. This list\
            \ contains all process steps that are required to manufacture the product,\
            \ specified with the bill of process  "
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_ProcessStepsList'
        productVersion:
          description: Version of the product whose manufacturing steps are specified
            with the bill of process. It can for example specify a concrete variant
            of a product
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_StringCharacteristic'
        productName:
          description: Name of the product whose production steps are specified within
            the bill of process
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_StringCharacteristic'
        billOfProcessIdentification:
          description: Unique identifier for a bill of process that can be used to
            reference instances of the bill of process
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_BillOfProcessIdCharacteristic'
        version:
          description: The unique identifier of the aspect model defining the structure
            and the semantics of the message's header. The version number should reflect
            the versioning schema of aspect models in Catena-X.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.message_header_2.0.0_SemanticVersioningTrait'
      required:
      - process
      - productVersion
      - productName
      - billOfProcessIdentification
      - version
    BillOfProcessSharedAspect:
      description: Shared aspect for the bill of process data model
      type: object
      properties:
        billOfProcessModel:
          description: Property containing the the bill of process model
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.bill_of_process_1.0.0_BillOfProcessCharacteristic'
      required:
      - billOfProcessModel
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BillOfProcessSharedAspect:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BillOfProcessSharedAspect'
      description: The request was successful.
  requestBodies:
    BillOfProcessSharedAspect:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BillOfProcessSharedAspect'
