name: Validate Semantic Models
description: Validates TTL files with the SDS SDK
inputs:
  added:
    description: 'The changed files, detected by a previous action'
    default: "[]"
    required: false
  modified:
    description: 'The modified files, detected by a previous action'
    default: "[]"
    required: false
  bamm_version: 
    description: The version of the used SAMM SDK
    default: 2.6.0
    required: true
  token:
    description: GitHub token
    required: true
  pr_number:
    description: Number of the pull request that triggered the action
    required: true
  bulk:
    description: Flag that defines whether all files on a branch should be validated
    required: false
    default: "false"
runs:
  using: node16
  main: index.js
