---
openapi: 3.0.3
info:
  title: Business Partner certificate
  version: v3
  x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#BusinessPartnerCertificate"
servers:
- url: catenax.io/api/v3
  variables:
    api-version:
      default: v3
paths:
  /{tenant-id}/business-partner-certificate:
    get:
      tags:
      - BusinessPartnerCertificate
      operationId: getBusinessPartnerCertificate
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: "#/components/responses/BusinessPartnerCertificate"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/BusinessPartnerCertificate"
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    BpnlTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnlTrait"
      description: "The provided regular expression ensures that the BPNL is composed\
        \ of prefix 'BPNL', 10 digits and two alphanumeric letters."
      pattern: "^BPNL[a-zA-Z0-9]{12}$"
    Text:
      type: string
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.1.0#Text"
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    CertificateTypeEntity:
      description: "Detailed entity of the certificate like IS09001:2015, IATF 16949:2015\
        \ or other, valid types are registered at BPN metadatacontroller"
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#CertificateTypeEntity"
      type: object
      properties:
        certificateType:
          description: "Type of the certificate as defined on the document,valid types\
            \ are registered at BPN metadatacontroller"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#certificateType"
          $ref: "#/components/schemas/Text"
        certificateVersion:
          description: "Version of the certificate as defined on the document, usually\
            \ the specific version of a certification standard"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#certificateVersion"
          $ref: "#/components/schemas/Text"
      required:
      - certificateType
    CertificateTypeCharacteristic:
      description: Describes the characteristics of the Certificate Type.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#CertificateTypeCharacteristic"
      type: object
      allOf:
      - $ref: "#/components/schemas/CertificateTypeEntity"
    BpnsTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnsTrait"
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two alphanumeric letters."
      pattern: "^BPNS[a-zA-Z0-9]{12}$"
    EnclosedSiteEntity:
      description: "Entity representing an enclosed site, can be the Business Partner\
        \ Number Site (BPNS) or Business Partner Number Address (BPNA)."
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#EnclosedSiteEntity"
      type: object
      properties:
        enclosedSiteBpn:
          description: The Business Partner Number (BPN) of an enclosed site
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#enclosedSiteBpn"
          $ref: "#/components/schemas/BpnsTrait"
        areaOfApplication:
          description: Details on which areas / application types a certificate is
            valid for a company and/or site.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#areaOfApplication"
          $ref: "#/components/schemas/Text"
      required:
      - enclosedSiteBpn
    EnclosedSitesCharacteristic:
      description: 'Describes the characteristic of the attribute enclosedSites. '
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#EnclosedSitesCharacteristic"
      type: array
      items:
        $ref: "#/components/schemas/EnclosedSiteEntity"
    Date:
      type: string
      format: date
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#Date"
      description: Describes a property which contains the date in english format.
    IssuerCharacteristics:
      description: Issuer name and the Business Partner Number (BPN) Characteristics.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#IssuerCharacteristics"
      type: object
      properties:
        issuerName:
          description: Name of the Issuer i.e. Certifying Authority.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#issuerName"
          $ref: "#/components/schemas/Text"
        issuerBpn:
          description: The Business Partner Number (BPN) of the Issuer.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#issuerBpn"
          $ref: "#/components/schemas/BpnlTrait"
      required:
      - issuerName
    TrustLevelValue:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#TrustLevelValue"
      description: The possible trust level values of certificate
      enum:
      - none
      - low
      - high
      - trusted
    TrustValidatorCharacteristic:
      description: The Business Partner Number (BPN) of the data service provider
        who validated the given certificate
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#TrustValidatorCharacteristic"
      type: object
      properties:
        validatorName:
          description: The optional name of the data service provider who validated
            the given certificate
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#validatorName"
          $ref: "#/components/schemas/Text"
        validatorBpn:
          description: The Business Partner Number (BPN) of the data service provider
            who validated the given certificate
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#validatorBpn"
          $ref: "#/components/schemas/BpnlTrait"
    Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.1.0#Timestamp"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    DocumentIdCharaccteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#DocumentIdCharaccteristic"
      description: The characcteristics of the document ID.
    MimeType:
      type: string
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.1.0#MimeType"
      description: "A MIME type as defined in RFC 2046, for example \"application/pdf\"\
        ."
    ContentBase64Characteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#ContentBase64Characteristic"
      description: 'Describes the document''s encoded value in a Content Base 64 String. '
    DocumentCharacteristic:
      description: Describes the characteristics of the attribute document.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#DocumentCharacteristic"
      type: object
      properties:
        creationDate:
          description: The creation date of the document.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#creationDate"
          $ref: "#/components/schemas/Timestamp"
        documentID:
          description: The id of the certificate document as stored by the data service
            provider.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#documentID"
          $ref: "#/components/schemas/DocumentIdCharaccteristic"
        contentType:
          description: The content type of the document.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#contentType"
          $ref: "#/components/schemas/MimeType"
        contentBase64:
          description: "The data is encoded using the Base64 encoding scheme, which\
            \ converts binary data into a string of ASCII characters. "
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#contentBase64"
          $ref: "#/components/schemas/ContentBase64Characteristic"
      required:
      - creationDate
      - documentID
      - contentType
      - contentBase64
    BusinessPartnerCertificate:
      description: "A business partner certifcate describes a certificate (eg ISO9001,\
        \ IATF-16949) via a certifcate document  of a Catena-X business partner"
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#BusinessPartnerCertificate"
      properties:
        businessPartnerNumber:
          description: The Business Partner Number (BPN) of the certified legal entity
            .
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#businessPartnerNumber"
          $ref: "#/components/schemas/BpnlTrait"
        type:
          description: "Type of the certificate as defined on the document like IS09001,\
            \ IATF 16949 or other"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#type"
          $ref: "#/components/schemas/CertificateTypeCharacteristic"
        registrationNumber:
          description: Registration number of the certificate as defined on the certificate
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#registrationNumber"
          $ref: "#/components/schemas/Text"
        areaOfApplication:
          description: Details on which areas / application types a certificate is
            valid for a company and/or site.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#areaOfApplication"
          $ref: "#/components/schemas/Text"
        enclosedSites:
          description: "Additional sites covered by the certificate, which can be\
            \ either the Business Partner Number Site (BPNS) or Business Partner Number\
            \ Address (BPNA)"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#enclosedSites"
          $ref: "#/components/schemas/EnclosedSitesCharacteristic"
        validFrom:
          description: Valid from date as defined on the certificate.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#validFrom"
          $ref: "#/components/schemas/Date"
        validUntil:
          description: Valid valid until as defined on the certificate. If certificate
            never expires value until expected to be 9999-12-31
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#validUntil"
          $ref: "#/components/schemas/Date"
        issuer:
          description: 'The BPN of the issuing authority e.g. TUEV Sued '
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#issuer"
          $ref: "#/components/schemas/IssuerCharacteristics"
        trustLevel:
          description: "The trust level of the given certificate - none,low, high,\
            \ trusted"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#trustLevel"
          $ref: "#/components/schemas/TrustLevelValue"
        validator:
          description: The Business Partner Number (BPN) of the data service provider
            who validates the given certificate.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#validator"
          $ref: "#/components/schemas/TrustValidatorCharacteristic"
        uploader:
          description: The Business Partner Number (BPN) of the business partner who
            originally provided the certifcate data or document.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#uploader"
          $ref: "#/components/schemas/BpnlTrait"
        document:
          description: The content and ID of the document.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.business_partner_certificate:3.0.0#document"
          $ref: "#/components/schemas/DocumentCharacteristic"
      required:
      - businessPartnerNumber
      - type
      - registrationNumber
      - validFrom
      - validUntil
      - trustLevel
      - document
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    BusinessPartnerCertificate:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PagingSchema"
      description: The request was successful.
  requestBodies:
    BusinessPartnerCertificate:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BusinessPartnerCertificate"
