---
openapi: 3.0.3
info:
  title: ESR Certificate StateS tatistic
  version: v1
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/esr-certificate-state-statistic:
    get:
      tags:
      - EsrCertificateStateStatistic
      operationId: getEsrCertificateStateStatistic
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: '#/components/responses/EsrCertificateStateStatistic'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    urn_bamm_io.catenax.esr_certificates.esr_certificate_state_statistic_1.0.1_CertficateName:
      type: string
      description: String without language tags
      enum:
      - ISO 14001
    urn_bamm_io.catenax.esr_certificates.esr_certificate_state_statistic_1.0.1_CertificatesWithStateValue:
      type: number
      minimum: 0
    urn_bamm_io.catenax.esr_certificates.esr_certificate_state_statistic_1.0.1_CertificateStateStatistic:
      type: object
      properties:
        certificatesWithStateValid:
          description: Number of certificates with state valid
          $ref: '#/components/schemas/urn_bamm_io.catenax.esr_certificates.esr_certificate_state_statistic_1.0.1_CertificatesWithStateValue'
        certificatesWithStateInvalid:
          description: Number of certificates with state invalid
          $ref: '#/components/schemas/urn_bamm_io.catenax.esr_certificates.esr_certificate_state_statistic_1.0.1_CertificatesWithStateValue'
        certificatesWithStateUnknown:
          description: Number of certificates with state unknown
          $ref: '#/components/schemas/urn_bamm_io.catenax.esr_certificates.esr_certificate_state_statistic_1.0.1_CertificatesWithStateValue'
        certificatesWithStateExceptional:
          description: Number of certificates with state exceptional
          $ref: '#/components/schemas/urn_bamm_io.catenax.esr_certificates.esr_certificate_state_statistic_1.0.1_CertificatesWithStateValue'
      required:
      - certificatesWithStateValid
      - certificatesWithStateInvalid
      - certificatesWithStateUnknown
      - certificatesWithStateExceptional
    EsrCertificateStateStatistic:
      description: State statistic for an Environmental and Social Responsibility
        (ESR) certificate
      type: object
      properties:
        certificateName:
          description: Name of the Environmental and Social Responsibility (ESR) certificate
          $ref: '#/components/schemas/urn_bamm_io.catenax.esr_certificates.esr_certificate_state_statistic_1.0.1_CertficateName'
        certificateStateStatistic:
          description: Environmental and Social Responsibility (ESR) certificate state
            statistic
          $ref: '#/components/schemas/urn_bamm_io.catenax.esr_certificates.esr_certificate_state_statistic_1.0.1_CertificateStateStatistic'
      required:
      - certificateName
      - certificateStateStatistic
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    EsrCertificateStateStatistic:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EsrCertificateStateStatistic'
      description: The request was successful.
  requestBodies:
    EsrCertificateStateStatistic:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EsrCertificateStateStatistic'
