---
openapi: 3.0.3
info:
  title: Provide Production Tracking
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#ProvideProductionTracking"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/provide-production-tracking:
    get:
      tags:
      - ProvideProductionTracking
      operationId: getProvideProductionTracking
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: "#/components/responses/ProvideProductionTracking"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    StringCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#StringCharacteristic"
      description: Characteristic to express strings
    ProcessParameterQualityEnumeration:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#ProcessParameterQualityEnumeration"
      description: Enumeration that provides a set of characteristic of a process
        parameter
      enum:
      - ok
      - inexact
      - noValue
    ProcessParameter:
      description: Data Type to provide process parameter with values from process
        step
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#ProcessParameter"
      type: object
      properties:
        processParameterName:
          description: Name of a process parameter
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#processParameterName"
          $ref: "#/components/schemas/StringCharacteristic"
        semanticId:
          description: Reference to a global defined semantic that characterizes the
            process parameter. For eaxample an E-Class reference
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#semanticId"
          $ref: "#/components/schemas/StringCharacteristic"
        processParameterValue:
          description: The concrete value of a process parameter. Becomes mandatory
            in case that the processParameterQuality property is not set to NoValue
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#processParameterValue"
          $ref: "#/components/schemas/StringCharacteristic"
        processParameterQuality:
          description: Enumeration to provide additional information about the significance
            of the parameter.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#processParameterQuality"
          $ref: "#/components/schemas/ProcessParameterQualityEnumeration"
      required:
      - processParameterName
      - semanticId
      - processParameterQuality
    ProcessParameterValueCharacteristic:
      description: Lists all requested process parameter
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#ProcessParameterValueCharacteristic"
      type: array
      items:
        $ref: "#/components/schemas/ProcessParameter"
    ProcessStepIdentifier:
      description: Data type to express process steps with corresponding paramater
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#ProcessStepIdentifier"
      type: object
      properties:
        processStepId:
          description: Id of a concrete process step
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#processStepId"
          $ref: "#/components/schemas/StringCharacteristic"
        processParameterValueList:
          description: "A set of process parameter for the corresponsing process step,\
            \ that corresponds to the requested parameters"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#processParameterValueList"
          $ref: "#/components/schemas/ProcessParameterValueCharacteristic"
      required:
      - processStepId
      - processParameterValueList
    ProcessStepIdentifierListCharacteristic:
      description: 'Characteristic that describes each element of the requested process
        steps '
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#ProcessStepIdentifierListCharacteristic"
      type: array
      items:
        $ref: "#/components/schemas/ProcessStepIdentifier"
    SemanticVersioningTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#SemanticVersioningTrait"
      description: Constraint for defining a SemVer version.
      pattern: "^(0|[1-9][0-9]*).(0|[1-9][0-9]*).(0|[1-9][0-9]*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*)(.[0-9A-Za-z-]+)*)?([0-9A-Za-z-]+(.[0-9A-Za-z-]+)*)?$"
    IdentifierTypeCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#IdentifierTypeCharacteristic"
      description: Enumeration that defines values for the identifier type
      enum:
      - partInstanceId
      - batchId
      - bomId
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    ResponseCharacteristic:
      description: Characteristic describing the response of the production tracking
        data model
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#ResponseCharacteristic"
      type: object
      properties:
        processStepIdentifierList:
          description: "List that contains a set of process steps, where each process\
            \ step provides a list with the values of the requeste parameters"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#processStepIdentifierList"
          $ref: "#/components/schemas/ProcessStepIdentifierListCharacteristic"
        version:
          description: The unique identifier of the aspect model defining the structure
            and the semantics of the message's header. The version number should reflect
            the versioning schema of aspect models in Catena-X.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#version"
          $ref: "#/components/schemas/SemanticVersioningTrait"
        identifierType:
          description: "Distinghuished between a bill of material, a part instanceId\
            \ or a batchId to identify a product"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#identifierType"
          $ref: "#/components/schemas/IdentifierTypeCharacteristic"
        identifierNumber:
          description: Identifier number of a product
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#identifierNumber"
          $ref: "#/components/schemas/StringCharacteristic"
        catenaXId:
          description: "The fully anonymous Catena-X ID of the serialized part, valid\
            \ for the Catena-X dataspace."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.serial_part:3.0.0#catenaXId"
          $ref: "#/components/schemas/UuidV4Trait"
      required:
      - processStepIdentifierList
      - version
      - identifierType
      - identifierNumber
    UuidV4Trait0:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:1.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    ContextCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#ContextCharacteristic"
      description: Defining a string value for the context
    Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Timestamp"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    BpnlTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:1.0.0#BpnlTrait"
      description: "The provided regular expression ensures that the BPNL is composed\
        \ of prefix 'BPNL', 10 digits and two uppercase letters."
      pattern: "^BPNL[0-9]{8}[a-zA-Z0-9]{4}$"
    HeaderCharacteristic:
      description: Characteristic describing the common shared aspect Message Header
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#HeaderCharacteristic"
      type: object
      properties:
        messageId:
          description: "Unique ID identifying the message. The purpose of the ID is\
            \ to uniquely identify a single message, therefore it MUST not be reused."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#messageId"
          $ref: "#/components/schemas/UuidV4Trait0"
        context:
          description: |-
            Information about the context the message should be considered in.
            The value MUST consist of two parts: an identifier of the context (e.g. business domain, etc.) followed by a version number.
            Both the identifier and the version number MUST correspond to the content of the message.
            If the content of a message is described by an aspect model available in the Catena-X Semantic Hub, then the unique identifier of this semantic model (e.g. urn:samm:io.catenax.<ASPECT-MODEL-NAME>:1.x.x) MUST be used as a value of the context field. This is considered the default case.
            In all other cases the value of the context field MUST follow the pattern <domain>-<subdomain>-<object>:<[major] version> (e.g. TRACE-QM-Alert:1.x.x).
            Versioning only refers to major versions in both default and fallback cases.
            Note: The version of the message's header is specified in the version field.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#context"
          $ref: "#/components/schemas/ContextCharacteristic"
        sentDateTime:
          description: Time zone aware timestamp holding the date and the time the
            message was sent by the sending party. The value MUST be formatted according
            to the ISO 8601 standard
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#sentDateTime"
          $ref: "#/components/schemas/Timestamp"
        senderBpn:
          description: The Business Partner Number of the sending party. The value
            MUST be a valid BPN. BPNA and BPNS are not allowed. Applicable constraints
            are defined in the corresponding standard
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#senderBpn"
          $ref: "#/components/schemas/BpnlTrait"
        receiverBpn:
          description: The Business Partner Number of the receiving party. The value
            MUST be a valid BPN. BPNA and BPNS are not allowed. Applicable constraints
            are defined in the corresponding standard.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#receiverBpn"
          $ref: "#/components/schemas/BpnlTrait"
        expectedResponseBy:
          description: Time zone aware timestamp holding the date and time by which
            the sending party expects a certain type of response from the receiving
            party. The meaning and interpretation of the fields's value are context-bound
            and MUST therefore be defined by any business domain or platform capability
            making use of it. The value MUST be formatted according to the ISO 8601
            standard
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#expectedResponseBy"
          $ref: "#/components/schemas/Timestamp"
        relatedMessageId:
          description: Unique ID identifying a message somehow related to the current
            one
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#relatedMessageId"
          $ref: "#/components/schemas/UuidV4Trait0"
        version:
          description: The unique identifier of the aspect model defining the structure
            and the semantics of the message's header. The version number should reflect
            the versioning schema of aspect models in Catena-X.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#version"
          $ref: "#/components/schemas/SemanticVersioningTrait"
      required:
      - messageId
      - context
      - sentDateTime
      - senderBpn
      - receiverBpn
      - version
    ProvideProductionTracking:
      description: Aspect for the production tracking response
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#ProvideProductionTracking"
      properties:
        response:
          description: Response data for the production tracking request
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shopfloor_information.provide_production_tracking:1.0.0#response"
          $ref: "#/components/schemas/ResponseCharacteristic"
        header:
          description: Contains standardized attributes for message processing common
            across several use cases.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.message_header:2.0.0#header"
          $ref: "#/components/schemas/HeaderCharacteristic"
      required:
      - response
      - header
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    ProvideProductionTracking:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProvideProductionTracking"
      description: The request was successful.
  requestBodies:
    ProvideProductionTracking:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProvideProductionTracking"
      required: true
