---
openapi: 3.0.3
info:
  title: SingleLevelUsageAsBuilt
  version: v3
servers:
- url: catenax.io/api/v3
  variables:
    api-version:
      default: v3
paths:
  /{tenant-id}/single-level-usage-as-built:
    get:
      tags:
      - SingleLevelUsageAsBuilt
      operationId: getSingleLevelUsageAsBuilt
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/SingleLevelUsageAsBuilt'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SingleLevelUsageAsBuilt'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_samm_io.catenax.shared.uuid_2.0.0_UuidV4Trait:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    urn_samm_io.catenax.single_level_usage_as_built_3.0.0_ListOfCustomersCharacteristic:
      description: A list of customers and their related parent items.
      type: array
      items:
        type: string
        description: "The provided regular expression ensures that the BPNL is composed\
          \ of prefix 'BPNL', 10 digits and two alphanumeric letters."
        pattern: "^BPNL[a-zA-Z0-9]{12}$"
    urn_samm_io.catenax.shared.quantity_2.0.0_QuantityValueCharacteristic:
      type: number
      description: The quantity value associated with the unit expressed as float.
    urn_samm_io.catenax.shared.quantity_2.0.0_ItemUnitEnumeration:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      description: Enumeration for common item units.
      enum:
      - unit:piece
      - unit:set
      - unit:pair
      - unit:page
      - unit:cycle
      - unit:kilowattHour
      - unit:gram
      - unit:kilogram
      - unit:tonneMetricTon
      - unit:tonUsOrShortTonUkorus
      - unit:ounceAvoirdupois
      - unit:pound
      - unit:metre
      - unit:centimetre
      - unit:kilometre
      - unit:inch
      - unit:foot
      - unit:yard
      - unit:squareCentimetre
      - unit:squareMetre
      - unit:squareInch
      - unit:squareFoot
      - unit:squareYard
      - unit:cubicCentimetre
      - unit:cubicMetre
      - unit:cubicInch
      - unit:cubicFoot
      - unit:cubicYard
      - unit:litre
      - unit:millilitre
      - unit:hectolitre
      - unit:secondUnitOfTime
      - unit:minuteUnitOfTime
      - unit:hourUnitOfTime
      - unit:day
    urn_samm_io.catenax.shared.quantity_2.0.0_ItemQuantityCharacteristic:
      description: "Characteristic for measurements of an item (mass, count, linear,\
        \ area, volume, misc)."
      type: object
      properties:
        value:
          description: The quantity value associated with the unit.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.quantity_2.0.0_QuantityValueCharacteristic'
        unit:
          description: "The unit of an item. Common units may be related to mass,\
            \ count, linear, area, volume or misc."
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.quantity_2.0.0_ItemUnitEnumeration'
      required:
      - value
      - unit
    urn_samm_io.catenax.single_level_usage_as_built_3.0.0_DateTimeTrait:
      type: string
      description: Regular Expression to enable UTC and Timezone formats and the possibility
        to exclude time information.
      pattern: "^-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])(T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?)?$"
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean:
      type: boolean
      description: Represents a boolean value (i.e. a "flag").
    urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnlTrait:
      type: string
      description: "The provided regular expression ensures that the BPNL is composed\
        \ of prefix 'BPNL', 10 digits and two alphanumeric letters."
      pattern: "^BPNL[a-zA-Z0-9]{12}$"
    urn_samm_io.catenax.single_level_usage_as_built_3.0.0_ParentData:
      description: Catena-X ID and meta data of the parent item.
      type: object
      properties:
        quantity:
          description: Quantity of which the child part is assembled into the parent
            part. In general it is '1' for serialized parts.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.quantity_2.0.0_ItemQuantityCharacteristic'
        createdOn:
          description: "Timestamp when the relation between the parent part and the\
            \ child part was created, e.g. when the given child part was assembled\
            \ into the parent part."
          $ref: '#/components/schemas/urn_samm_io.catenax.single_level_usage_as_built_3.0.0_DateTimeTrait'
        lastModifiedOn:
          description: Timestamp when the assembly or usage relationship between parent
            part and child part was last modified.
          $ref: '#/components/schemas/urn_samm_io.catenax.single_level_usage_as_built_3.0.0_DateTimeTrait'
        isOnlyPotentialParent:
          description: |
            Expresses the certainty whether the part has been used as component or input material in the produced item. If the value is false, it can be assumed that the part has been used. If the value is true, there are alternatives for that part, and it is unknown if this part item or an alternative part item has been used.
            This is the case when, e.g. the same item is supplied by two suppliers, and the item is only tracked by a customer part ID during assembly. Thus, these items cannot be differentiated from each other.
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Boolean'
        businessPartner:
          description: The supplier of the given child item.
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnlTrait'
        catenaXId:
          description: "The Catena-X ID of the given part (e.g. the component), valid\
            \ for the Catena-X dataspace."
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.uuid_2.0.0_UuidV4Trait'
      required:
      - createdOn
      - isOnlyPotentialParent
      - businessPartner
      - catenaXId
    urn_samm_io.catenax.single_level_usage_as_built_3.0.0_SetOfParentItemsCharacteristic:
      description: Set of parent items the given child object is assembled in (one
        structural level up).
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.single_level_usage_as_built_3.0.0_ParentData'
      uniqueItems: true
    SingleLevelUsageAsBuilt:
      description: "The aspect provides the information in which parent part(s)/product(s)the\
        \ given item is assembled in. Could be a 1:1 relationship in terms of an e.g.\
        \ a brake component or 1:n for e.g. coatings. The parent item must refer to\
        \ an object from as-built lifecycle phase, i.e. a batch or a serialized part."
      type: object
      properties:
        catenaXId:
          description: "The Catena-X ID of the given part (e.g. the component), valid\
            \ for the Catena-X dataspace."
          $ref: '#/components/schemas/urn_samm_io.catenax.shared.uuid_2.0.0_UuidV4Trait'
        customers:
          description: |-
            A list of all customers of this item. If the parent items in which this item is assembled into are known, they should be listed as well.

            For serialized items the list should contain only one customer with one parent item.
            As different subsets of a batch might be sold to different customers this is a list.
          $ref: '#/components/schemas/urn_samm_io.catenax.single_level_usage_as_built_3.0.0_ListOfCustomersCharacteristic'
        parentItems:
          description: |-
            Set of parent items, in which the given child object is assembled in (one structural level up).

            For serialized items the list should contain only one parent item.
            As different subsets of a batch might be used by a customer in different items this is a list.
          $ref: '#/components/schemas/urn_samm_io.catenax.single_level_usage_as_built_3.0.0_SetOfParentItemsCharacteristic'
      required:
      - catenaXId
      - customers
      - parentItems
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    SingleLevelUsageAsBuilt:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    SingleLevelUsageAsBuilt:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SingleLevelUsageAsBuilt'
