---
openapi: 3.0.3
info:
  title: composition
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#Composition"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/composition:
    get:
      tags:
      - Composition
      operationId: getComposition
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: "#/components/responses/Composition"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    WeightCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#WeightCharacteristic"
      description: Weight Characteristic
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    MaterialsCharacteristic:
      description: materials characteristic
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#MaterialsCharacteristic"
      type: object
      properties:
        materialWeight:
          description: Weight of a material in a part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#materialWeight"
          $ref: "#/components/schemas/WeightCharacteristic"
        globalAssetId:
          description: The fully anonymous ID in the dataspace of the part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#globalAssetId"
          $ref: "#/components/schemas/UuidV4Trait"
      required:
      - materialWeight
      - globalAssetId
    Composition:
      description: "The Composition aspect model defines a standardized and interoperable\
        \ representation of material compositions, capturing material shares of a\
        \ digital twin in a consistent and machine-readable manner."
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#Composition"
      properties:
        materials:
          description: List of all materials.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#materials"
          $ref: "#/components/schemas/MaterialsCharacteristic"
        globalAssetId:
          description: The fully anonymous ID in the dataspace of the part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#globalAssetId"
          $ref: "#/components/schemas/UuidV4Trait"
      required:
      - materials
      - globalAssetId
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    Composition:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Composition"
      description: The request was successful.
  requestBodies:
    Composition:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Composition"
      required: true
