---
openapi: 3.0.3
info:
  title: recycling information
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#RecyclingInformation"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/recycling-information:
    get:
      tags:
      - RecyclingInformation
      operationId: getRecyclingInformation
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: "#/components/responses/RecyclingInformation"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    MaterialShareTrait:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#MaterialShareTrait"
      description: limits the values for material shares to 0-100
      maximum: 100.0
      exclusiveMaximum: false
      minimum: 0.0
      exclusiveMinimum: false
    OriginEnumeration:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#OriginEnumeration"
      description: Enum of origins
      enum:
      - EU
      - Non-EU
    ConsumerShareEntity:
      description: Set of shares from automotive and non automotive material shares.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#ConsumerShareEntity"
      type: object
      properties:
        automotive:
          description: Share of automotive material
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#automotive"
          $ref: "#/components/schemas/MaterialShareTrait"
        nonAutomotive:
          description: Share of non-automotive material.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#nonAutomotive"
          $ref: "#/components/schemas/MaterialShareTrait"
      required:
      - automotive
      - nonAutomotive
    ConsumerShareCharacteristic:
      description: Set of shares from automotive and non automotive material shares.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#ConsumerShareCharacteristic"
      type: object
      allOf:
      - $ref: "#/components/schemas/ConsumerShareEntity"
    MaterialSourceEntity:
      description: Material Source Entity.
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#MaterialSourceEntity"
      type: object
      properties:
        secondaryMaterial:
          description: "Material share from all materials obtained from waste, by-products\
            \ and production residues sources. In the material cycle diagrams, this\
            \ corresponds to the material flows PrC, PoC and ReU-M.  This includes\
            \ substances and mixtures of substances that are intended for the manufacture\
            \ of products. This can include both secondary raw materials and more\
            \ highly processed substances and mixtures of substances. Secondary material\
            \ can be used as a substitute for primary material in processes."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#secondaryMaterial"
          $ref: "#/components/schemas/MaterialShareTrait"
        primaryMaterial:
          description: 'Material share from Substances and mixtures of substances
            intended for the manufacture of products and used for the first time in
            a production process. '
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#primaryMaterial"
          $ref: "#/components/schemas/MaterialShareTrait"
      required:
      - secondaryMaterial
      - primaryMaterial
    MaterialSourceSingleEntity:
      description: Material Source SingleEntity
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#MaterialSourceSingleEntity"
      type: object
      allOf:
      - $ref: "#/components/schemas/MaterialSourceEntity"
    Text:
      type: string
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text"
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    RecyclingInformation:
      description: "The RecyclingInformation aspect model defines a standardized and\
        \ interoperable representation of recycling-related material shares, including\
        \ material origin, reutilization, pre- and post-consumer shares, and primary\
        \ and secondary material sources, in a consistent and machine-readable manner."
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#RecyclingInformation"
      properties:
        reutilizationMaterialShare:
          description: "Material share from reutilization of materials such as rework,\
            \ regrind, or scrap materials generated within the process and capable\
            \ of being reused within the same process that generated it."
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#reutilizationMaterialShare"
          $ref: "#/components/schemas/MaterialShareTrait"
        origin:
          description: Information on material origin.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#origin"
          $ref: "#/components/schemas/OriginEnumeration"
        preConsumerShares:
          description: Set of pre consumer material shares.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#preConsumerShares"
          $ref: "#/components/schemas/ConsumerShareCharacteristic"
        postConsumerShares:
          description: Set of post consumer material shares.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#postConsumerShares"
          $ref: "#/components/schemas/ConsumerShareCharacteristic"
        materialSourceShares:
          description: Shares of primary and secondary materials
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#materialSourceShares"
          $ref: "#/components/schemas/MaterialSourceSingleEntity"
        otherInformation:
          description: "Document or evidence verifying the origin, quality, or compliance\
            \ of a material"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#otherInformation"
          $ref: "#/components/schemas/Text"
        globalAssetId:
          description: The fully anonymous ID in the dataspace of the part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#globalAssetId"
          $ref: "#/components/schemas/UuidV4Trait"
      required:
      - reutilizationMaterialShare
      - origin
      - preConsumerShares
      - postConsumerShares
      - materialSourceShares
      - otherInformation
      - globalAssetId
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    RecyclingInformation:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RecyclingInformation"
      description: The request was successful.
  requestBodies:
    RecyclingInformation:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RecyclingInformation"
      required: true
