---
openapi: 3.0.3
info:
  title: waste code
  version: v1
  x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#WasteCode"
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/waste-code:
    get:
      tags:
      - WasteCode
      operationId: getWasteCode
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: "#/components/responses/WasteCode"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    WasteCodeEnum:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#WasteCodeEnum"
      description: Enumeration of waste codes according to EWC (european waste directory).
      enum:
      - 16 01 99
      - 16 01 22
      - 16 01 21
      - 16 01 16
      - 16 01 15
      - 16 01 14
      - 16 01 13
      - 16 01 12
      - 16 01 11
      - 16 01 10
      - 16 01 09
      - 16 01 08
      - 16 01 07
      - 16 01 06
      - 16 01 04
      - 16 01 03
    UuidV4Trait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.uuid:2.0.0#UuidV4Trait"
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    WasteCode:
      description: "The WasteCode aspect model defines a standardized and interoperable\
        \ representation of waste categorization information, including European Waste\
        \ Catalogue (EWC) codes and their descriptions, to classify vehicles, parts\
        \ or materials in a consistent and machine-readable manner."
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#WasteCode"
      properties:
        wasteCode:
          description: The waste code is used to identify the type of waste on part
            or material level.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material:1.0.0#wasteCode"
          $ref: "#/components/schemas/WasteCodeEnum"
        globalAssetId:
          description: The fully anonymous ID in the dataspace of the part.
          x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.industry_core.common:1.0.0#globalAssetId"
          $ref: "#/components/schemas/UuidV4Trait"
      required:
      - wasteCode
      - globalAssetId
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    WasteCode:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WasteCode"
      description: The request was successful.
  requestBodies:
    WasteCode:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WasteCode"
      required: true
