---
openapi: 3.0.3
info:
  title: Certificate of Destruction
  version: v2
  x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#CertificateOfDestruction"
servers:
- url: catenax.io/api/v2
  variables:
    api-version:
      default: v2
paths:
  /{tenant-id}/certificate-of-destruction:
    get:
      tags:
      - CertificateOfDestruction
      operationId: getCertificateOfDestruction
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: "#/components/responses/CertificateOfDestruction"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    DateCharacteristic:
      type: string
      format: date
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#DateCharacteristic"
      description: Date characteristic
    Text:
      type: string
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text"
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    Boolean:
      type: boolean
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Boolean"
      description: Represents a boolean value (i.e. a "flag").
    ZipTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#ZipTrait"
      description: The maximal length of the the postal code is restricted to 14 chracters
      maxLength: 14
    CountryCodeTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#CountryCodeTrait"
      description: Constraint to be conform with the ISO 3166-1 alpha-2 code with
        two upper case characters
      pattern: "^[A-Z]{2}$"
    Address:
      description: Address characteristic which corresponds to the information given
        in the certificate of destruction
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#Address"
      type: object
      properties:
        street:
          description: The street name
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#street"
          $ref: "#/components/schemas/Text"
        houseNumber:
          description: The house number of the address
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#houseNumber"
          $ref: "#/components/schemas/Text"
        zip:
          description: The postal code
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#zip"
          $ref: "#/components/schemas/ZipTrait"
        location:
          description: The location or city of the address
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#location"
          $ref: "#/components/schemas/Text"
        name:
          description: "Name of the private individual, company or authority"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#name"
          $ref: "#/components/schemas/Text"
        country:
          description: Country code
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#country"
          $ref: "#/components/schemas/CountryCodeTrait"
      required:
      - street
      - houseNumber
      - zip
      - location
      - name
      - country
    VehicleOwnerCharacteristic:
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#VehicleOwnerCharacteristic"
      type: object
      properties:
        isVehicleOwnerInformationComplete:
          description: "Boolean flag to indicate whether the information in the data\
            \ set is complete. If the data set contains unknown fields, the value\
            \ is false"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#isVehicleOwnerInformationComplete"
          $ref: "#/components/schemas/Boolean"
        vehicleOwnerAddress:
          description: 'Address of the vehicle owner '
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#vehicleOwnerAddress"
          $ref: "#/components/schemas/Address"
        citizenship:
          description: Citizenship of the vehicle owner
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#citizenship"
          $ref: "#/components/schemas/CountryCodeTrait"
      required:
      - isVehicleOwnerInformationComplete
      - vehicleOwnerAddress
      - citizenship
      description: Characteristic to describe the vehicle owner attributes
    Weight:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#Weight"
      description: weight of the vehicle
    VehicleCharacteristic:
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#VehicleCharacteristic"
      type: object
      properties:
        isVehicleInformationComplete:
          description: "Boolean flag to indicate whether the information in the data\
            \ set is complete. If the data set contains unknown fields, the value\
            \ is false"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#isVehicleInformationComplete"
          $ref: "#/components/schemas/Boolean"
        emptyWeight:
          description: Empty weight in accordance with ยง2Abs.1 Nr.23 AltfahrzeugV
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#emptyWeight"
          $ref: "#/components/schemas/Weight"
        firstRegistration:
          description: The first time this vehicle got registered with an initial
            license plate
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#firstRegistration"
          $ref: "#/components/schemas/Text"
        licensePlate:
          description: Current (i.e. last) assigned number/ license plate to the vehicle
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#licensePlate"
          $ref: "#/components/schemas/Text"
        licenseAbbreviation:
          description: The first characters on the license plate
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#licenseAbbreviation"
          $ref: "#/components/schemas/Text"
        identification:
          description: 'The unique vehicle identification number (VIN) of the vehicle '
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#identification"
          $ref: "#/components/schemas/Text"
        model:
          description: Vehicle model
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#model"
          $ref: "#/components/schemas/Text"
        brand:
          description: Brand name
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#brand"
          $ref: "#/components/schemas/Text"
        class:
          description: Vehicle class the vehicle refers to
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#class"
          $ref: "#/components/schemas/Text"
      required:
      - isVehicleInformationComplete
      - emptyWeight
      - firstRegistration
      - licensePlate
      - licenseAbbreviation
      - identification
      - model
      - brand
      - class
      description: Characteristic to describe the vehicle attributes
    PhoneTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#PhoneTrait"
      description: "Phone constraint allow only numbers, whitespaces and an optional\
        \ leading plus sign"
      pattern: "[+]?[0-9 ]+"
    ContactCharacteristic:
      description: Contact characteristic based on the contact information available
        in the certificate of destruction
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#ContactCharacteristic"
      type: object
      properties:
        phone:
          description: Phone number
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#phone"
          $ref: "#/components/schemas/PhoneTrait"
        fax:
          description: Fax number
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#fax"
          $ref: "#/components/schemas/PhoneTrait"
      required:
      - phone
    ReceivingCharacteristic:
      description: Characteristic to describe the receiving attributes
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#ReceivingCharacteristic"
      type: object
      properties:
        isVehicleWithdrawnFromService:
          description: True if the vehicle has been withdrawn from the service and
            out of circulation
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#isVehicleWithdrawnFromService"
          $ref: "#/components/schemas/Boolean"
        receiverAuditorAddress:
          description: 'The address of the auditor '
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#receiverAuditorAddress"
          $ref: "#/components/schemas/Address"
        issueDate:
          description: The date of issue of the certificate
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#issueDate"
          $ref: "#/components/schemas/DateCharacteristic"
        expiryDate:
          description: The date of expiration of the certificate
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#expiryDate"
          $ref: "#/components/schemas/DateCharacteristic"
        receiverContact:
          description: Contact information of the receiving company
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#receiverContact"
          $ref: "#/components/schemas/ContactCharacteristic"
        receiverAuditorContact:
          description: Auditor contact information
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#receiverAuditorContact"
          $ref: "#/components/schemas/ContactCharacteristic"
        receiverAddress:
          description: 'The address of the receiver '
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#receiverAddress"
          $ref: "#/components/schemas/Address"
      required:
      - isVehicleWithdrawnFromService
      - receiverAuditorAddress
      - issueDate
      - expiryDate
      - receiverContact
      - receiverAuditorContact
      - receiverAddress
    DismantlerCharacterisitc:
      description: Characteristic to describe the dismantler attributes
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#DismantlerCharacterisitc"
      type: object
      properties:
        isVehicleWithdrawnFromService:
          description: True if the vehicle has been withdrawn from the service and
            out of circulation
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#isVehicleWithdrawnFromService"
          $ref: "#/components/schemas/Boolean"
        dismantlerAddress:
          description: Address for the dismantling company
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#dismantlerAddress"
          $ref: "#/components/schemas/Address"
        governmentAddress:
          description: The address of the public government
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#governmentAddress"
          $ref: "#/components/schemas/Address"
        receiverAuditorAddress:
          description: 'The address of the auditor '
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#receiverAuditorAddress"
          $ref: "#/components/schemas/Address"
        issueDate:
          description: The date of issue of the certificate
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#issueDate"
          $ref: "#/components/schemas/DateCharacteristic"
        expiryDate:
          description: The date of expiration of the certificate
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#expiryDate"
          $ref: "#/components/schemas/DateCharacteristic"
        dismantlerContact:
          description: Dismantler contact information
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#dismantlerContact"
          $ref: "#/components/schemas/ContactCharacteristic"
        dismantlerAuditorAddress:
          description: Information about the auditor address
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#dismantlerAuditorAddress"
          $ref: "#/components/schemas/Address"
        dismantlerAuditorContact:
          description: Information about the auditor contact
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#dismantlerAuditorContact"
          $ref: "#/components/schemas/ContactCharacteristic"
      required:
      - isVehicleWithdrawnFromService
      - dismantlerAddress
      - governmentAddress
      - receiverAuditorAddress
      - issueDate
      - expiryDate
      - dismantlerContact
      - dismantlerAuditorAddress
      - dismantlerAuditorContact
    CertificateOfDestruction:
      description: "Information on the certificate of destruction. In german: Verwertungsnachweis"
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#CertificateOfDestruction"
      properties:
        dismantlingDate:
          description: Date of issue of the certificate of destruction
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#dismantlingDate"
          $ref: "#/components/schemas/DateCharacteristic"
        serialNumber:
          description: Serial number to identify the certificate of destruction
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#serialNumber"
          $ref: "#/components/schemas/Text"
        vehicleOwnerProperties:
          description: Properties under the first section of the certificate of destruction
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#vehicleOwnerProperties"
          $ref: "#/components/schemas/VehicleOwnerCharacteristic"
        vehicleProperties:
          description: Properties under the second section of the certificate of destruction
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#vehicleProperties"
          $ref: "#/components/schemas/VehicleCharacteristic"
        returnPointProperties:
          description: Properties under the third section of the certificate of destruction
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#returnPointProperties"
          $ref: "#/components/schemas/ReceivingCharacteristic"
        dismantlerProperties:
          description: Properties under the fourth section of the certificate of destruction
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#dismantlerProperties"
          $ref: "#/components/schemas/DismantlerCharacterisitc"
        companyNumber:
          description: Company number as an dismantler
          x-samm-aspect-model-urn: "urn:samm:io.catenax.certificate_of_destruction:2.0.0#companyNumber"
          $ref: "#/components/schemas/Text"
      required:
      - dismantlingDate
      - serialNumber
      - vehicleOwnerProperties
      - vehicleProperties
      - returnPointProperties
      - dismantlerProperties
      - companyNumber
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    CertificateOfDestruction:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CertificateOfDestruction"
      description: The request was successful.
  requestBodies:
    CertificateOfDestruction:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CertificateOfDestruction"
      required: true
