#######################################################################
# Copyright (c) 2023 Robert Bosch Manufacturing Solutions GmbH
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This work is made available under the terms of the
# Creative Commons Attribution 4.0 International (CC-BY-4.0) license,
# which is available at
# https://creativecommons.org/licenses/by/4.0/legalcode.
#
# SPDX-License-Identifier: CC-BY-4.0
#######################################################################

name: Bulk Validation
on:
  workflow_dispatch:
    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install Node dependencies
        working-directory: ./.github/actions/model-validation
        run: npm install
      - name: validate models
        uses: ./.github/actions/model-validation
        with:
          samm_version: 2.11.1
          bulk: true
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: full-validation-report
          path: output
