---
openapi: 3.0.3
info:
  title: Material Flow Simulation Result Aspect
  version: v3
  x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#MaterialFlowSimulationResultAspect"
servers:
- url: catenax.io/api/v3
  variables:
    api-version:
      default: v3
paths:
  /{tenant-id}/material-flow-simulation-result-aspect:
    get:
      tags:
      - MaterialFlowSimulationResultAspect
      operationId: getMaterialFlowSimulationResultAspect
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          $ref: "#/components/responses/MaterialFlowSimulationResultAspect"
        "400":
          $ref: "#/components/responses/ClientError"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFoundError"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    Text:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#Text"
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    Timestamp:
      type: string
      pattern: "-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\\
        .[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?"
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Timestamp"
      description: Describes a Property which contains the date and time with an optional
        timezone.
    BpnsTrait:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.shared.business_partner_number:2.0.0#BpnsTrait"
      description: "The provided regular expression ensures that the BPNS is composed\
        \ of prefix 'BPNS', 10 digits and two alphanumeric letters."
      pattern: "^BPNS[a-zA-Z0-9]{12}$"
    BusinessPartnerSite:
      description: "Identifier for the physical location of a business partner plant\
        \ or site, (e.g. BPNS in Catena-X context)"
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#BusinessPartnerSite"
      type: object
      properties:
        bpnsProperty:
          description: Property based on BPNS
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#bpnsProperty"
          $ref: "#/components/schemas/BpnsTrait"
      required:
      - bpnsProperty
    OwnerCharacteristic:
      description: Site identifier of the simulation originator
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#OwnerCharacteristic"
      type: object
      allOf:
      - $ref: "#/components/schemas/BusinessPartnerSite"
    DataQualityOptions:
      type: number
      minimum: 0
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#DataQualityOptions"
      description: Possible values determining data quality
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    Text0:
      type: string
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Text"
      description: "Describes a Property which contains plain text. This is intended\
        \ exclusively for human readable strings, not for identifiers, measurement\
        \ values, etc."
    DestinationCharacteristic:
      description: Address where the shipment is immediately delivered to (by logistician)
        or provided for pickup (by producer)
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#DestinationCharacteristic"
      type: object
      allOf:
      - $ref: "#/components/schemas/BusinessPartnerSite"
    RecipientCharacteristic:
      description: Location identifier of the final recipient of the shipment
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#RecipientCharacteristic"
      type: object
      allOf:
      - $ref: "#/components/schemas/BusinessPartnerSite"
    Boolean:
      type: boolean
      x-samm-aspect-model-urn: "urn:samm:org.eclipse.esmf.samm:characteristic:2.2.0#Boolean"
      description: Represents a boolean value (i.e. a "flag").
    LogisticsCharacteristic:
      description: Site identifier of the logistician executing the shipment
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#LogisticsCharacteristic"
      type: object
      allOf:
      - $ref: "#/components/schemas/BusinessPartnerSite"
    PrecedingCharacteristic:
      description: Reference of preceding shipments
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#PrecedingCharacteristic"
      type: object
      allOf:
      - $ref: "#/components/schemas/BusinessPartnerSite"
    VolumeCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#VolumeCharacteristic"
      description: Volumetric value determining the volume of the handling unit
    WeightCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#WeightCharacteristic"
      description: Amount of weight of the handling unit
    AmountCharacteristic:
      type: number
      minimum: 1
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#AmountCharacteristic"
      description: Number describing handling units with identical pieces
    QuantityCharacteristic:
      type: number
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#QuantityCharacteristic"
      description: Number of materials contained within a handling unit
    UnitOfMeasurementCharacteristic:
      type: string
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#UnitOfMeasurementCharacteristic"
      description: Possible options for units of measurement
      enum:
      - KG
      - Liter
      - Piece
    MaterialBatch:
      description: Material Batches are part of a handling unit
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#MaterialBatch"
      type: object
      properties:
        batchSerialNumber:
          description: can be used to uniquely identify a singe product part
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#batchSerialNumber"
          $ref: "#/components/schemas/Text"
        materialNumber:
          description: ID of the material contained in the batch
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#materialNumber"
          $ref: "#/components/schemas/Text"
        materialName:
          description: Name of the material
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#materialName"
          $ref: "#/components/schemas/Text"
        materialHazardousGoods:
          description: Flags hazardous goods
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#materialHazardousGoods"
          $ref: "#/components/schemas/Boolean"
        batchExpirationTimestamp:
          description: Expiration date of batch
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#batchExpirationTimestamp"
          $ref: "#/components/schemas/Timestamp"
        quantity:
          description: Amount of materials
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#quantity"
          $ref: "#/components/schemas/QuantityCharacteristic"
        unitOfMeasurement:
          description: Unit used for measuring the quantity
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#unitOfMeasurement"
          $ref: "#/components/schemas/UnitOfMeasurementCharacteristic"
        batchNumber:
          description: "Number of the batch, generated by originator (e.g. from ERP\
            \ system, no uuid)"
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#batchNumber"
          $ref: "#/components/schemas/Text"
        batchOrderId:
          description: Order ID to which the batch belongs
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#batchOrderId"
          $ref: "#/components/schemas/Text"
      required:
      - batchSerialNumber
      - materialNumber
      - materialName
      - materialHazardousGoods
      - batchExpirationTimestamp
      - quantity
      - unitOfMeasurement
      - batchNumber
      - batchOrderId
    BatchList:
      description: List of material batches
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#BatchList"
      type: array
      items:
        $ref: "#/components/schemas/MaterialBatch"
    HandlingUnit:
      description: Handling Unit is the smallest shipment unit and cannot be divided
        into several shipments
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#HandlingUnit"
      type: object
      properties:
        handlingUnitId:
          description: ID of the handling unit
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#handlingUnitId"
          $ref: "#/components/schemas/Text"
        name:
          description: Name of the type of handling unit
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#name"
          $ref: "#/components/schemas/Text"
        volume:
          description: Volume of the handling unit
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#volume"
          $ref: "#/components/schemas/VolumeCharacteristic"
        weight:
          description: Weight of the handling unit
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#weight"
          $ref: "#/components/schemas/WeightCharacteristic"
        amount:
          description: Number of handling units with identical content
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#amount"
          $ref: "#/components/schemas/AmountCharacteristic"
        batches:
          description: List of material batches contained within a handling unit
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#batches"
          $ref: "#/components/schemas/BatchList"
      required:
      - handlingUnitId
      - name
      - volume
      - weight
      - amount
      - batches
    HandlingUnitList:
      description: List of handling units included in the shipment
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#HandlingUnitList"
      type: array
      items:
        $ref: "#/components/schemas/HandlingUnit"
    Shipment:
      description: Delivery item from a sender to a recipient containing goods
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#Shipment"
      type: object
      properties:
        shipmentId:
          description: ID to identify the shipment
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#shipmentId"
          $ref: "#/components/schemas/Text0"
        destination:
          description: Address where the shipment is immediately delivered to (by
            logistician) or provided for pickup (by producer)
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#destination"
          $ref: "#/components/schemas/DestinationCharacteristic"
        destinationTimestamp:
          description: Time when delivery arrives or is ready at goods issue
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#destinationTimestamp"
          $ref: "#/components/schemas/Timestamp"
        recipient:
          description: Address of final recipient of shipment
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#recipient"
          $ref: "#/components/schemas/RecipientCharacteristic"
        recipientTimestampPlanned:
          description: Planned delivery time
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#recipientTimestampPlanned"
          $ref: "#/components/schemas/Timestamp"
        splittingAllowed:
          description: Permission to split the shipment into individual deliveries
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#splittingAllowed"
          $ref: "#/components/schemas/Boolean"
        logistics:
          description: Address of logistician executing the shipment
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#logistics"
          $ref: "#/components/schemas/LogisticsCharacteristic"
        preceding:
          description: Reference ID of a preceding shipment
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#preceding"
          $ref: "#/components/schemas/PrecedingCharacteristic"
        handlingUnits:
          description: List of Handling Units
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#handlingUnits"
          $ref: "#/components/schemas/HandlingUnitList"
      required:
      - shipmentId
      - destination
      - destinationTimestamp
      - recipient
      - recipientTimestampPlanned
      - splittingAllowed
      - logistics
      - preceding
      - handlingUnits
    ShipmentList:
      description: List of shipments contained in the simulation
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#ShipmentList"
      type: array
      items:
        $ref: "#/components/schemas/Shipment"
    MaterialFlowSimulationResultCharacteristic:
      description: Characteristic describing the aspect material flow simulation result
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#MaterialFlowSimulationResultCharacteristic"
      type: object
      properties:
        description:
          description: Verbal description
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#description"
          $ref: "#/components/schemas/Text"
        runId:
          description: Id of the simulation run
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#runId"
          $ref: "#/components/schemas/Text"
        comment:
          description: Additional comments
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#comment"
          $ref: "#/components/schemas/Text"
        expirationTimestamp:
          description: Date and time when the simulation is expired
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#expirationTimestamp"
          $ref: "#/components/schemas/Timestamp"
        owner:
          description: Site identifier of the simulation originator
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#owner"
          $ref: "#/components/schemas/OwnerCharacteristic"
        dataQuality:
          description: Information on quality of simulation results
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#dataQuality"
          $ref: "#/components/schemas/DataQualityOptions"
        shipments:
          description: List of shipments
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#shipments"
          $ref: "#/components/schemas/ShipmentList"
        timestamp:
          description: Timestamp of simulation run
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#timestamp"
          $ref: "#/components/schemas/Timestamp"
      required:
      - description
      - runId
      - comment
      - expirationTimestamp
      - owner
      - dataQuality
      - shipments
      - timestamp
    MaterialFlowSimulationResultAspect:
      description: Aspect Model for the result of a Material Flow Simulation
      type: object
      x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#MaterialFlowSimulationResultAspect"
      properties:
        materialFlowSimulationResult:
          description: Contains standardized attributes for the result of a material
            flow simulation
          x-samm-aspect-model-urn: "urn:samm:io.catenax.material_flow_simulation_result:3.0.0#materialFlowSimulationResult"
          $ref: "#/components/schemas/MaterialFlowSimulationResultCharacteristic"
      required:
      - materialFlowSimulationResult
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources.
    NotFoundError:
      description: The requested resource has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more information.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    MaterialFlowSimulationResultAspect:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MaterialFlowSimulationResultAspect"
      description: The request was successful.
  requestBodies:
    MaterialFlowSimulationResultAspect:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MaterialFlowSimulationResultAspect"
      required: true
